Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2023-07, with the labels that each got.

#2154 Revert rutile yield from garnet processing to it's pre-nerf values
  src/main/java/gregtech/loaders/postload/chains/GT_BauxiteRefineChain.java
Labels: Affects Balance

#2142 First Modular Upgrade Casings Implementation
  src/main/java/gregtech/api/multitileentity/enums/GT_MultiTileUpgradeCasing.java
  src/main/java/gregtech/api/multitileentity/interfaces/UpgradableModularMuTE.java
  src/main/java/gregtech/api/multitileentity/machine/MultiTileBasicMachine.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/Controller.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
  src/main/java/gregtech/api/util/GT_StructureUtilityMuTE.java
  src/main/java/gregtech/common/tileentities/casings/upgrade/Heater.java
  src/main/java/gregtech/common/tileentities/casings/upgrade/Insulator.java
  src/main/java/gregtech/common/tileentities/machines/multiblock/LayeredCokeBattery.java
  src/main/java/gregtech/loaders/preload/GT_Loader_MultiTileEntities.java
  src/main/resources/assets/gregtech/textures/blocks/multitileentity/heater/base.png
  src/main/resources/assets/gregtech/textures/blocks/multitileentity/insulator/base.png
Labels: MuTE

#2166 Make DD Great Again(Adding Tritanium Ore)
  src/main/java/gregtech/api/enums/Materials.java
Labels: Affects Balance

#2160 Add Crafting Input Buffer (ME)
  dependencies.gradle
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/gui/modularui/GT_UITextures.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_ExtendedPowerMultiBlockBase.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_CraftingInput_ME.java
  src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_CraftingInput_Slave.java
  src/main/java/gregtech/common/tileentities/machines/IDualInputHatch.java
  src/main/java/gregtech/common/tileentities/machines/IDualInputInventory.java
  src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java
  src/main/resources/assets/gregtech/textures/gui/overlay_slot/pattern_me.png
Labels: need to be tested, RFC, Affects Balance

#2173 Add a config to enable seeing average ns per tick in waila
  src/main/java/gregtech/api/interfaces/tileentity/IGregTechTileEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
  src/main/java/gregtech/common/GT_Proxy.java
  src/main/java/gregtech/loaders/preload/GT_PreLoad.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#2185 Add more API to ParallelHelper and rework OverclockCalculator
  src/main/java/gregtech/api/logic/ComplexParallelProcessingLogic.java
  src/main/java/gregtech/api/logic/ProcessingLogic.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_ExtendedPowerMultiBlockBase.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
  src/main/java/gregtech/api/recipe/check/CheckRecipeResultRegistry.java
  src/main/java/gregtech/api/util/GT_OverclockCalculator.java
  src/main/java/gregtech/api/util/GT_ParallelHelper.java
  src/main/java/gregtech/api/util/GT_Utility.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_ElectricBlastFurnace.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_FusionComputer.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_NanoForge.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_ProcessingArray.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PyrolyseOven.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_TranscendentPlasmaMixer.java
  src/main/java/gregtech/nei/FusionSpecialValueFormatter.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/test/java/gregtech/overclock/GT_OverclockCalculator_UnitTest.java
Labels: Affects Balance

#2165 Less hostile user interfaces (Buffer/Filter/Input bus)
  src/main/java/gregtech/api/enums/MachineType.java
  src/main/java/gregtech/api/gui/modularui/GT_UITextures.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_BasicMachine_Bronze.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_FilterBase.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_InputBus.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_SpecialFilter.java
  src/main/java/gregtech/api/util/GT_LanguageManager.java
  src/main/java/gregtech/common/covers/GT_Cover_ItemFilter.java
  src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_ChestBuffer.java
  src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_Filter.java
  src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_ItemDistributor.java
  src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_RecipeFilter.java
  src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_Regulator.java
  src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_SuperBuffer.java
  src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_TypeFilter.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/gui/overlay_button/one_stack_limit.png
  src/main/resources/assets/gregtech/textures/gui/overlay_button/sorting_mode.png
Labels: enhancement, Affects Balance
