Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2023-09, with the labels that each got.

#2216 Add TickableTask
  src/main/java/gregtech/api/enums/GT_Values.java
  src/main/java/gregtech/api/interfaces/tileentity/IMachineProgress.java
  src/main/java/gregtech/api/logic/ComplexParallelProcessingLogic.java
  src/main/java/gregtech/api/logic/PollutionLogic.java
  src/main/java/gregtech/api/logic/interfaces/PollutionLogicHost.java
  src/main/java/gregtech/api/multitileentity/base/MultiTileEntity.java
  src/main/java/gregtech/api/multitileentity/base/TickableMultiTileEntity.java
  src/main/java/gregtech/api/multitileentity/machine/MultiTileBasicMachine.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/ComplexParallelController.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/Controller.java
  src/main/java/gregtech/api/task/TaskHost.java
  src/main/java/gregtech/api/task/TickableTask.java
  src/main/java/gregtech/api/task/tasks/PollutionTask.java
  src/main/java/gregtech/common/tileentities/machines/multiblock/CokeOven.java
Labels: MuTE

#2280 Makes Fool's Ruby use its proper scientific name
  src/main/java/gregtech/api/enums/Materials.java
Labels: enhancement

#2289 Adds Metrics Transmitter Cover and Advanced GT Sensor Card for Information Panels
  src/main/java/gregtech/api/enums/GT_Values.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/api/interfaces/metatileentity/IMetricsExporter.java
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
  src/main/java/gregtech/api/util/GT_CoverBehaviorBase.java
  src/main/java/gregtech/common/GT_Proxy.java
  src/main/java/gregtech/common/covers/CoverInfo.java
  src/main/java/gregtech/common/covers/GT_Cover_Metrics_Transmitter.java
  src/main/java/gregtech/common/events/BaseMetricsCoverEvent.java
  src/main/java/gregtech/common/events/MetricsCoverDataEvent.java
  src/main/java/gregtech/common/events/MetricsCoverHostDeconstructedEvent.java
  src/main/java/gregtech/common/events/MetricsCoverSelfDestructEvent.java
  src/main/java/gregtech/common/items/GT_AdvancedSensorCard_Item.java
  src/main/java/gregtech/common/items/GT_MetaGenerated_Item_03.java
  src/main/java/gregtech/common/items/GT_SensorCard_Item.java
  src/main/java/gregtech/common/items/behaviors/Behaviour_Cover_Tool.java
  src/main/java/gregtech/common/misc/GlobalMetricsCoverDatabase.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_DrillerBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_OilDrillBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_OreDrillingPlantBase.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/java/gregtech/loaders/preload/GT_Loader_Item_Block_And_Fluid.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_METRICS_TRANSMITTER.png
  src/main/resources/assets/gregtech/textures/items/gt.advancedsensorcard.png
  src/main/resources/assets/gregtech/textures/items/gt.advancedsensorcardburned.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.03/232.png
Labels: enhancement

#2301 [MuTE] Refactor MuTE processing logic
  src/main/java/gregtech/api/logic/AbstractProcessingLogic.java
  src/main/java/gregtech/api/logic/ComplexParallelProcessingLogic.java
  src/main/java/gregtech/api/logic/MuTEProcessingLogic.java
  src/main/java/gregtech/api/logic/ProcessingLogic.java
  src/main/java/gregtech/api/logic/interfaces/ProcessingLogicHost.java
  src/main/java/gregtech/api/multitileentity/machine/MultiTileBasicMachine.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/Controller.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/PowerController.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/StackableController.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
  src/main/java/gregtech/api/task/tasks/ProcessingTask.java
  src/main/java/gregtech/common/tileentities/machines/multiblock/logic/CokeOvenProcessingLogic.java
  src/main/java/gregtech/common/tileentities/machines/multiblock/logic/LayeredCokeBatteryProcessingLogic.java
  src/main/java/gregtech/common/tileentities/machines/multiblock/logic/MaceratorProcessingLogic.java
Labels: MuTE

#2298 Fix void protection for mutes
  src/main/java/gregtech/api/util/GT_ParallelHelper.java
  src/main/java/gregtech/api/util/VoidProtectionHelper.java
Labels: MuTE

#2303 Adds a Simple PowerOutput task and cleans up some of the code.
  src/main/java/gregtech/api/interfaces/IGlobalWirelessEnergy.java
  src/main/java/gregtech/api/interfaces/tileentity/IEnergyConnected.java
  src/main/java/gregtech/api/logic/PowerLogic.java
  src/main/java/gregtech/api/logic/interfaces/FluidInventoryLogicHost.java
  src/main/java/gregtech/api/logic/interfaces/ItemInventoryLogicHost.java
  src/main/java/gregtech/api/logic/interfaces/PowerLogicHost.java
  src/main/java/gregtech/api/logic/interfaces/ProcessingLogicHost.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Wireless_Dynamo.java
  src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Wireless_Hatch.java
  src/main/java/gregtech/api/multitileentity/base/MultiTileEntity.java
  src/main/java/gregtech/api/multitileentity/machine/MultiTileBasicMachine.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/ComplexParallelController.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/Controller.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/MultiBlockPart.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/PowerController.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/StackableController.java
  src/main/java/gregtech/api/task/tasks/PowerOutputTask.java
  src/main/java/gregtech/common/GT_Proxy.java
  src/main/java/gregtech/common/misc/GT_Command.java
  src/main/java/gregtech/common/misc/WirelessNetworkManager.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_TranscendentPlasmaMixer.java
  src/test/java/gregtech/globalenergymap/IGlobalWirelessEnergy_UnitTest.java
Labels: MuTE

#2282 Cleanup MuTEMaster code
  src/main/java/gregtech/api/metatileentity/BaseTileEntity.java
  src/main/java/gregtech/api/multitileentity/MultiTileEntityBlock.java
  src/main/java/gregtech/api/multitileentity/MultiTileEntityItemInternal.java
  src/main/java/gregtech/api/multitileentity/base/MultiTileEntity.java
  src/main/java/gregtech/api/multitileentity/machine/MultiTileBasicMachine.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/ComplexParallelController.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/Controller.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/MultiBlockPart.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/StackableController.java
  src/main/java/gregtech/common/tileentities/machines/multiblock/AdvChemicalProcessor.java
  src/main/java/gregtech/common/tileentities/machines/multiblock/LayeredCokeBattery.java
Labels: MuTE

#2311 Fix DTPF discount increasing too quickly
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PlasmaForge.java
Labels: Affects Balance

#2316 Clean up a lil bit and fix some issues with MuTEs
  src/main/java/gregtech/api/logic/ComplexParallelProcessingLogic.java
  src/main/java/gregtech/api/multitileentity/MultiTileEntityBlock.java
  src/main/java/gregtech/api/multitileentity/MultiTileEntityItemInternal.java
  src/main/java/gregtech/api/multitileentity/interfaces/IMultiBlockController.java
  src/main/java/gregtech/api/multitileentity/machine/MultiTileBasicMachine.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/Controller.java
  src/main/java/gregtech/api/task/tasks/ProcessingTask.java
Labels: MuTE
