Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2024-08, with the labels that each got.

#2727 Hot salt ehe support
  src/main/java/goodgenerator/loader/RecipeLoader_02.java
Labels: Affects Balance

#2805 MFE buffs
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
Labels: Affects Balance

#2810 Switch to using the vanilla fortune logic for raw ores.
  src/main/java/gregtech/common/blocks/GT_TileEntity_Ores.java
Labels: Affects Balance

#2806 Swap Tiering of XL Gas and SH Steam and Lower Ichorium Turbine Multipliers
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gtPlusPlus/core/recipe/RECIPES_Machines.java
  src/main/java/gtPlusPlus/core/recipe/common/CI.java
Labels: Affects Balance

#2795 Cryofreezer buff
  src/main/java/gtPlusPlus/core/recipe/RECIPES_Machines.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialVacuumFreezer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/GregtechMetaTileEntity_Adv_EBF.java
Labels: Affects Balance

#2840 Adds halfway starts in Platline/Rare earth processing to QFT
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoader_ChemicalSkips.java
Labels: Affects Balance

#2762 Add New Butane Crafting Option for Anti-Knock Agent
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/loaders/postload/recipes/ChemicalRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/DistilleryRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/MixerRecipes.java
Labels: Affects Balance

#2764 Change Cracking LCR Recipe Tier to HV
  src/main/java/gregtech/common/GT_Proxy.java
Labels: Affects Balance

#2842 Plasma Line buffs, EHE nerfs, Unstable Naquadah rebalance
  src/main/java/goodgenerator/blocks/tileEntity/SupercriticalFluidTurbine.java
  src/main/java/goodgenerator/items/MyMaterial.java
  src/main/java/goodgenerator/loader/RecipeLoader_02.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingCell.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/GT_MTE_LargeTurbine_SCSteam.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoader_Nuclear.java
Labels: Affects Balance

#2847 Buff later naqfuels and misc changes
  src/main/java/goodgenerator/api/recipe/GoodGeneratorRecipeMaps.java
  src/main/java/goodgenerator/blocks/tileEntity/FuelRefineFactory.java
  src/main/java/goodgenerator/blocks/tileEntity/MultiNqGenerator.java
  src/main/java/goodgenerator/loader/FuelRecipeLoader.java
  src/main/java/gregtech/common/gui/modularui/UIHelper.java
  src/main/resources/assets/goodgenerator/lang/en_US.lang
Labels: Affects Balance

#2815 Removing the LEG
  dependencies.gradle
  src/main/java/goodgenerator/crossmod/thaumcraft/Research.java
  src/main/java/goodgenerator/loader/Loaders.java
Labels: RFC, Affects Balance

#2804 Fix multi bonuses taking too much power
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialLaserEngraver.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiCanner.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiLathe.java
Labels: RFC

#2859 Retier Laser Hatch amperage, add Laser Mirror, add customizable amperage to Laser Hatches
  src/main/java/com/github/bartimaeusnek/bartworks/system/material/BW_NonMeta_MaterialItems.java
  src/main/java/com/github/technus/tectech/loader/recipe/Assembler.java
  src/main/java/com/github/technus/tectech/loader/recipe/ResearchStationAssemblyLine.java
  src/main/java/com/github/technus/tectech/loader/thing/MachineLoader.java
  src/main/java/com/github/technus/tectech/thing/CustomItemList.java
  src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_DynamoMulti.java
  src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_DynamoTunnel.java
  src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_EnergyMulti.java
  src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_EnergyTunnel.java
  src/main/java/com/github/technus/tectech/thing/metaTileEntity/pipe/GT_MetaTileEntity_Pipe_EnergyMirror.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/interfaces/IItemContainer.java
  src/main/java/kubatech/api/enums/ItemList.java
  src/main/java/net/glease/ggfab/GGItemList.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/blocks/iconsets/EM_LASERMIRROR.png
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: Affects Balance

#2818 Europium bee line
  src/main/java/gregtech/common/items/CombType.java
  src/main/java/gregtech/common/items/DropType.java
  src/main/java/gregtech/common/items/ItemComb.java
  src/main/java/gregtech/loaders/misc/GT_BeeDefinition.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/lang/zh_CN.lang
Labels: Affects Balance

#2966 Extractor multi
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialExtractor.java
  src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_EMS.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_INDUSTRIAL_EXTRACTOR.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_INDUSTRIAL_EXTRACTOR_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_INDUSTRIAL_EXTRACTOR_ACTIVE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_INDUSTRIAL_EXTRACTOR_GLOW.png
Labels: Affects Balance

#2849 Backend Rework of the Quantum Computer (QC)
  src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_Rack.java
  src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_computer.java
Labels: Affects Balance
