Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2024-09, with the labels that each got.

#2507 Add bee in courtesy to DaddyDiddy
  dependencies.gradle
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/common/items/CombType.java
  src/main/java/gregtech/common/items/GT_MetaGenerated_Item_01.java
  src/main/java/gregtech/common/items/ItemComb.java
  src/main/java/gregtech/loaders/misc/GT_BeeDefinition.java
  src/main/java/gregtech/loaders/misc/GT_Bees.java
  src/main/java/gregtech/loaders/misc/bees/GT_AlleleEffect.java
  src/main/java/gregtech/loaders/misc/bees/GT_EffectMachineBoost.java
  src/main/java/gregtech/loaders/misc/bees/GT_EffectTreeTwister.java
  src/main/java/gregtech/loaders/misc/bees/GT_Flowers.java
  src/main/java/gregtech/loaders/postload/recipes/SifterRecipes.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/414.png
Labels: Affects Balance

#3022 fix switch fall-through for gt++ plasma values
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenPlasma.java
Labels: bug fix

#3024 Laser Engraver fixes
  src/main/java/gregtech/api/util/LaserRenderingUtil.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_EMS.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_LASER.png
Labels: bug fix

#3025 fluid canner fix
  src/main/java/gregtech/loaders/postload/GTPostLoad.java
Labels: bug fix

#3026 fixed getGlassBlock2 returning glass 1
  src/main/java/bartworks/API/BorosilicateGlass.java
Labels: bug fix

#3028 Re-add lapis plate recipe
  src/main/java/gregtech/loaders/postload/recipes/CompressorRecipes.java
Labels: bug fix

#3023 Improve unification for blocks
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/blocks/BlockMetal.java
Labels: enhancement, refactor, bug fix

#3036 fix semi-fluid gens
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/generators/MTESemiFluidGenerator.java
Labels: bug fix

#3041 Fixes #17207
  src/main/java/goodgenerator/blocks/tileEntity/MTEComponentAssemblyLine.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEPreciseAssembler.java
  src/main/java/gregtech/api/logic/AbstractProcessingLogic.java
  src/main/java/gregtech/api/util/OverclockCalculator.java
  src/main/java/gregtech/api/util/ParallelHelper.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPCBFactory.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialAlloySmelter.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMixer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEIndustrialRockBreaker.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/mega/MTEMegaAlloyBlastSmelter.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEDEFusionCrafter.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge_modules/MTEBaseModule.java
  src/main/java/tectech/util/GodforgeMath.java
  src/test/java/gregtech/overclock/GT_OverclockCalculator_UnitTest.java
Labels: bug fix

#3042 Implement itemInputsUnsafe
  src/main/java/gregtech/api/recipe/RecipeMapBackend.java
  src/main/java/gregtech/api/util/GTOreDictUnificator.java
  src/main/java/gregtech/api/util/GTRecipe.java
  src/main/java/gregtech/api/util/GTRecipeBuilder.java
Labels: enhancement

#3044 Fix Overflows with Burn Times and adjust burn-time when the super efficiency increase logic reaches max efficiency
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeBoiler.java
Labels: bug fix

#3043 Add support to disable pattern optimization in CRIBs
  src/main/java/gregtech/api/gui/modularui/GTUITextures.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
  src/main/resources/assets/gregtech/textures/gui/overlay_button/pattern_optimize.png
Labels: enhancement

#3046 change naquadah fuel refinery to 4/4 overclock
  src/main/java/goodgenerator/blocks/tileEntity/MTEFuelRefineFactory.java
Labels: enhancement

#3047 Fix the new code based oredict tweaks
  src/main/java/gregtech/api/enums/ManualOreDictTweaks.java
Labels: bug fix

#3048 fix pyro vent recipes
  src/main/java/gtPlusPlus/core/recipe/RecipesGeneral.java
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
Labels: bug fix

#3052 Readd advanced alloy recipe
  src/main/java/gregtech/loaders/postload/recipes/CompressorRecipes.java
Labels: bug fix

#3053 Remove hard dep on mobs-info
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/kubatech/api/DynamicInventory.java
  src/main/java/kubatech/api/EIGDynamicInventory.java
  src/main/java/kubatech/api/helpers/GTHelper.java
  src/main/java/kubatech/loaders/TCLoader.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEMegaIndustrialApiary.java
Labels: bug fix

#3051 Rework Indium comb Processing
  src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
  src/main/java/gregtech/common/items/ItemComb.java
Labels: Affects Balance

#3055 Fix tiering of cable recipes
  src/main/java/gregtech/loaders/oreprocessing/ProcessingWire.java
Labels: bug fix

#3037 Delete/modify some reflection + more renaming
  dependencies.gradle
  src/main/java/bartworks/API/WerkstoffAPI.java
  src/main/java/bartworks/system/material/WerkstoffLoader.java
  src/main/java/bartworks/system/material/gtenhancement/PlatinumSludgeOverHaul.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/CraftingMaterialLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/MoltenCellLoader.java
  src/main/java/bartworks/util/CachedReflectionUtils.java
  src/main/java/bwcrossmod/GTpp/loader/RadioHatchCompat.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/objects/GTChunkManager.java
  src/main/java/gregtech/api/objects/GTRenderedTexture.java
  src/main/java/gregtech/api/threads/RunnableMachineUpdate.java
  src/main/java/gregtech/api/util/GTChunkAssociatedData.java
  src/main/java/gregtech/api/util/GTModHandler.java
  src/main/java/gregtech/asm/GTCorePlugin.java
  src/main/java/gregtech/common/GTWorldgenerator.java
  src/main/java/gregtech/common/render/GTCopiedBlockTextureRender.java
  src/main/java/gregtech/common/render/GTCopiedCTMBlockTexture.java
  src/main/java/gregtech/common/render/GTRenderedTexture.java
  src/main/java/gregtech/common/render/GTSidedTextureRender.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEWorldAccelerator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEWormholeGenerator.java
  src/main/java/gregtech/loaders/misc/GTBeeDefinition.java
  src/main/java/gregtech/loaders/misc/bees/GTEffectTreeTwister.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
  src/main/java/gtPlusPlus/core/block/machine/BlockProjectTable.java
  src/main/java/gtPlusPlus/core/common/CommonProxy.java
  src/main/java/gtPlusPlus/core/item/general/books/ItemBaseBook.java
  src/main/java/gtPlusPlus/core/lib/GTPPCore.java
  src/main/java/gtPlusPlus/core/util/minecraft/PlayerUtils.java
  src/main/java/gtPlusPlus/everglades/gen/gt/WorldGen_GT_Base.java
  src/main/java/gtPlusPlus/preloader/asm/transformers/Preloader_Transformer_Handler.java
  src/main/java/gtPlusPlus/xmod/forestry/bees/custom/GTPPBeeDefinition.java
  src/main/java/gtPlusPlus/xmod/forestry/bees/custom/GTPPBees.java
  src/main/java/gtPlusPlus/xmod/forestry/bees/custom/GTPPBranchDefinition.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GTPPMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIsaMill.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/MTEChemicalPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechConduits.java
  src/main/java/gtneioreplugin/util/GT5OreSmallHelper.java
  src/main/java/tectech/loader/recipe/BaseRecipeLoader.java
Labels: refactor

#3065 crops++ ids
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
Labels: refactor

#3073 fix energy core tier
  src/main/java/goodgenerator/loader/RecipeLoader2.java
Labels: bug fix

#3067 update steam multi tooltips
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMixer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWaterPump.java
Labels: enhancement

#3057 Fix up tooltips, crib acceptance, and normalize the lathe to use all item pipe casings
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiAutoclave.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiLathe.java
Labels: bug fix

#3078 Fix LSC voiding energy on placement in some cases
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
Labels: bug fix

#2808 Multiblock machine for Fluid Solidifier
  src/main/java/gregtech/api/enums/GTValues.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/common/blocks/BlockCasings10.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_MS160.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/RADIATOR_MS160.png
Labels: Affects Balance, new feature

#3049 Reducing Hypogen consumption in Naqfuel MK4 recipes
  src/main/java/goodgenerator/loader/FuelRecipeLoader.java
Labels: Affects Balance

#3091 fix for use new mui2 version
  src/main/java/gtPlusPlus/core/block/machine/BlockDecayablesChest.java
Labels: bug fix

#3090 add label requirement
  .github/workflows/labels.yml
Labels: new feature

#3097 Black hole render
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gregtech/common/blocks/BlockBlackholeRenderer.java
  src/main/java/gregtech/common/render/BlackholeRenderer.java
  src/main/java/gregtech/common/tileentities/render/TileEntityBlackhole.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
  src/main/resources/assets/gregtech/shaders/blackhole.frag.glsl
  src/main/resources/assets/gregtech/shaders/blackhole.vert.glsl
  src/main/resources/assets/gregtech/shaders/laser.frag.glsl
  src/main/resources/assets/gregtech/shaders/laser.vert.glsl
  src/main/resources/assets/gregtech/textures/model/blackhole.obj
  src/main/resources/assets/gregtech/textures/model/blackhole.png
  src/main/resources/assets/gregtech/textures/model/laser.png
Labels: enhancement

#3093 Fix overlapped IDs for sounds and add two new sounds
  src/main/java/gregtech/api/enums/SoundResource.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiAutoclave.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiLathe.java
  src/main/resources/assets/gregtech/sounds.json
  src/main/resources/assets/gregtech/sounds/MultiAutoclaveLoop.ogg
  src/main/resources/assets/gregtech/sounds/MultiLatheLoop.ogg
Labels: enhancement, bug fix

#3094 Fluid solidifer multiblock balance and cleanup
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: Affects Balance

#3074 Remove a bunch more reflection
  dependencies.gradle
  src/main/java/bwcrossmod/galacticgreg/MTEVoidMinerBase.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEYottaFluidTank.java
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEWirelessEnergy.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
  src/main/java/gregtech/loaders/preload/GTPreLoad.java
  src/main/java/gtPlusPlus/api/objects/data/AutoMap.java
  src/main/java/gtPlusPlus/core/block/base/BlockBaseOre.java
  src/main/java/gtPlusPlus/core/gui/widget/GuiValueField.java
  src/main/java/gtPlusPlus/core/handler/PacketHandler.java
  src/main/java/gtPlusPlus/core/item/chemistry/AgriculturalChem.java
  src/main/java/gtPlusPlus/core/item/chemistry/MilledOreProcessing.java
  src/main/java/gtPlusPlus/core/item/tool/misc/ItemGregtechPump.java
  src/main/java/gtPlusPlus/core/lib/GTPPCore.java
  src/main/java/gtPlusPlus/core/material/MaterialStack.java
  src/main/java/gtPlusPlus/core/tileentities/machines/TileEntityPestKiller.java
  src/main/java/gtPlusPlus/core/util/minecraft/ItemUtils.java
  src/main/java/gtPlusPlus/core/util/minecraft/MiningUtils.java
  src/main/java/gtPlusPlus/core/util/reflect/ReflectionUtils.java
  src/main/java/gtPlusPlus/plugin/agrichem/item/algae/ItemAgrichemBase.java
  src/main/java/gtPlusPlus/plugin/fixes/vanilla/VanillaBedHeightFix.java
  src/main/java/gtPlusPlus/xmod/bop/BiomesOPlentyHandler.java
  src/main/java/gtPlusPlus/xmod/forestry/bees/registry/GTPP_BeeDefinition.java
  src/main/java/gtPlusPlus/xmod/forestry/bees/registry/GTPP_Bees.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchNaquadah.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GTPPMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenFluidCanning.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenRecycling.java
  src/main/java/gtPlusPlus/xmod/tinkers/HandlerTinkers.java
  src/main/java/gtPlusPlus/xmod/tinkers/material/BaseTinkersMaterial.java
  src/main/java/gtPlusPlus/xmod/tinkers/util/TinkersDryingRecipe.java
  src/main/java/gtPlusPlus/xmod/tinkers/util/TinkersUtils.java
  src/main/java/gtnhlanth/common/tileentity/MTELINAC.java
Labels: refactor

#3083 Followup for the great renaming & cleanup IMC for NEI
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gtneioreplugin/GTNEIOrePlugin.java
  src/main/java/gtneioreplugin/plugin/IMCForNEI.java
  src/main/java/gtneioreplugin/plugin/NEIPluginConfig.java
  src/main/java/kubatech/ClientProxy.java
  src/main/java/kubatech/nei/IMCForNEI.java
  src/main/java/kubatech/nei/NEIConfig.java
Labels: refactor, bug fix

#3087 Fix AAL tooltips
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/resources/assets/ggfab/lang/en_US.lang
  src/main/resources/assets/ggfab/lang/zh_CN.lang
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: bug fix

#3098 Rebalance DSS + Proto-Halkonite
  src/main/java/gregtech/loaders/postload/recipes/PlasmaForgeRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/VacuumFreezerRecipes.java
Labels: Affects Balance

#3060 Finishing touches on black hole compressor
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gregtech/common/blocks/BlockBlackholeRenderer.java
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/common/render/BlackholeRenderer.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEHIPCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEHeatSensor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEIndustrialCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTENeutroniumCompressor.java
  src/main/java/gregtech/common/tileentities/render/TileEntityBlackhole.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingPlate.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCompressor.java
  src/main/resources/assets/gregtech/shaders/blackhole.frag.glsl
  src/main/resources/assets/gregtech/shaders/blackhole.vert.glsl
  src/main/resources/assets/gregtech/shaders/laser.frag.glsl
  src/main/resources/assets/gregtech/shaders/laser.vert.glsl
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_HATCH_HEAT_SENSOR.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_HATCH_HEAT_SENSOR_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_BLACKHOLE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_BLACKHOLE_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_BLACKHOLE_ACTIVE.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_BLACKHOLE_ACTIVE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_BLACKHOLE_ACTIVE_GLOW.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_BLACKHOLE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_BLACKHOLE_UNSTABLE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_BLACKHOLE_UNSTABLE.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_BLACKHOLE_UNSTABLE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_BLACKHOLE_UNSTABLE_GLOW.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_NEUTRONIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_NEUTRONIUM_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_NEUTRONIUM_ACTIVE.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_NEUTRONIUM_ACTIVE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_NEUTRONIUM_ACTIVE_GLOW.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MULTI_NEUTRONIUM_GLOW.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/418.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/418.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/419.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/419.png.mcmeta
  src/main/resources/assets/gregtech/textures/model/blackhole.obj
  src/main/resources/assets/gregtech/textures/model/blackhole.png
  src/main/resources/assets/gregtech/textures/model/laser.png
Labels: refactor, bug fix

#3100 Update MUI2
  dependencies.gradle
  src/main/java/gtPlusPlus/core/block/machine/BlockDecayablesChest.java
Labels: refactor

#3103 Temp fix attempt
  src/main/java/tectech/thing/block/RenderForgeOfGods.java
Labels: bug fix

#3092 Change Cinobite alternative breeding requirement to Arcanite
  src/main/java/gregtech/loaders/misc/GTBeeDefinition.java
Labels: Affects Balance

#3101 Add chore label
  .github/workflows/labels.yml
Labels: enhancement

#3102 Fix more broken NEI caused by renaming
  src/main/java/bartworks/neiHandler/BioLabNEIHandler.java
  src/main/java/bartworks/neiHandler/BioVatNEIHandler.java
  src/main/java/bartworks/neiHandler/NEIBWConfig.java
  src/main/java/bartworks/neiHandler/OreNEIHandler.java
  src/main/java/gtPlusPlus/core/proxy/ClientProxy.java
  src/main/java/gtPlusPlus/nei/LFTRSpargingNEIHandler.java
  src/main/java/gtPlusPlus/nei/NEIGTPPConfig.java
Labels: bug fix

#3107 Fix waterline bugs
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitOzonation.java
Labels: bug fix

#3109 Gorge render attempt #2
  src/main/java/tectech/thing/block/RenderForgeOfGods.java
  src/main/java/tectech/util/StructureVBO.java
Labels: bug fix

#3111 Gorge fixed with jank
  src/main/java/tectech/thing/block/RenderForgeOfGods.java
  src/main/java/tectech/util/FaceVisibility.java
  src/main/java/tectech/util/StructureVBO.java
  src/main/resources/assets/tectech/shaders/fadebypass.frag.glsl
  src/main/resources/assets/tectech/shaders/fadebypass.vert.glsl
Labels: bug fix

#3112 fix GT Stones not being generated
  src/main/java/gregtech/common/StoneBuilder.java
  src/main/java/gregtech/common/WorldgenStone.java
Labels: bug fix

#3114 Fix Black Hole amperage
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
Labels: bug fix

#3123 Add waterline debug mode
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBase.java
Labels: enhancement

#3119 Fix some mistakes in GT++ stuff
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechAmazonWarehouse.java
  src/main/resources/assets/miscutils/lang/en_US.lang
Labels: bug fix

#3110 Replace neutronium compressor with neutronium compressor
  src/main/java/bartworks/common/loaders/ElectricImplosionCompressorRecipes.java
  src/main/java/goodgenerator/loader/RecipeLoader2.java
  src/main/java/kekztech/common/recipeLoaders/AssemblyLine.java
  src/main/java/kubatech/loaders/RecipeLoader.java
Labels: Affects Balance

#3085 Adds Infinite Spray Can, left click event for item behaviors
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/SoundResource.java
  src/main/java/gregtech/api/interfaces/IItemBehaviour.java
  src/main/java/gregtech/api/items/MetaBaseItem.java
  src/main/java/gregtech/api/net/GTPacketInfiniteSpraycan.java
  src/main/java/gregtech/api/net/GTPacketTypes.java
  src/main/java/gregtech/client/GTMouseEventHandler.java
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gregtech/common/items/IDMetaItem01.java
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColor.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColorInfinite.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColorRemover.java
  src/main/resources/assets/gregtech/sounds.json
  src/main/resources/assets/gregtech/sounds/spraycan.ogg
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/468.png
Labels: Affects Balance, new feature

#3124 add logs for Nq recipes being patched by GG for its naq changes
  src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
  src/main/java/goodgenerator/main/GGConfigLoader.java
  src/main/java/goodgenerator/main/GoodGenerator.java
Labels: enhancement, refactor

#3121 log recipes edited/removed by BW platinum overhaul
  src/main/java/bartworks/system/material/gtenhancement/PlatinumSludgeOverHaul.java
Labels: enhancement, refactor

#3126 Fix crop manager tooltip being incorrect
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTECropHarvestor.java
Labels: bug fix

#3089 scrollable multiblock status display
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/kubatech/api/implementations/KubaTechGTMultiBlockBase.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeIndustrialGreenhouse.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEMegaIndustrialApiary.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge_modules/MTEBaseModule.java
Labels: new feature

#3127 fixed ross128b & ross128ba oregen
  src/main/java/bartworks/system/oregen/BWWorldGenRoss128b.java
  src/main/java/bartworks/system/oregen/BWWorldGenRoss128ba.java
Labels: bug fix

#3120 Add astral array amount tooltips to EOH
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEyeOfHarmony.java
Labels: new feature

#3058 Cleanup detrav
  src/main/java/detrav/commands/DetravScannerCommand.java
  src/main/java/detrav/enums/IDDetraveMetaGeneratedTool01.java
  src/main/java/detrav/items/DetravMetaGeneratedTool01.java
  src/main/java/detrav/items/behaviours/BehaviourDetravToolElectricProspector.java
  src/main/java/detrav/items/behaviours/BehaviourDetravToolProspector.java
  src/main/java/detrav/items/processing/ProcessingDetravToolProspector.java
  src/main/java/detrav/items/tools/DetravProspector.java
  src/main/java/detrav/items/tools/DetravToolElectricProspector.java
  src/main/java/detrav/items/tools/DetravToolElectricProspectorBase.java
  src/main/java/detrav/proxies/ClientProxy.java
  src/main/java/detrav/proxies/CommonProxy.java
  src/main/java/detrav/utils/FluidColors.java
Labels: refactor

#3128 add null checks to the replacement logs
  src/main/java/bartworks/system/material/gtenhancement/PlatinumSludgeOverHaul.java
  src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
Labels: bug fix

#3129 Gorge fixed with jank part 2
  src/main/java/tectech/thing/block/RenderForgeOfGods.java
  src/main/java/tectech/util/StructureVBO.java
  src/main/java/tectech/util/TextureUpdateRequester.java
Labels: bug fix

#3084 Remove findRecipe methods
  src/main/java/bartworks/common/tileentities/multis/MTEWindmill.java
  src/main/java/bartworks/common/tileentities/tiered/GT_MetaTileEntity_RadioHatch.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEMultiNqGenerator.java
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicGenerator.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachineBronze.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachineWithRecipe.java
  src/main/java/gregtech/api/recipe/FindRecipeQuery.java
  src/main/java/gregtech/api/recipe/RecipeMap.java
  src/main/java/gregtech/api/recipe/check/SingleRecipeCheck.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEBoxinator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIntegratedOreFactory.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEOreDrillingPlantBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPrimitiveBlastFurnace.java
  src/main/java/gregtech/common/tileentities/machines/steam/MTESteamMaceratorBronze.java
  src/main/java/gregtech/common/tileentities/machines/steam/MTESteamMaceratorSteel.java
  src/main/java/gregtech/common/tools/ToolHardHammer.java
  src/main/java/gregtech/common/tools/ToolJackHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/generators/MTERocketFuelGeneratorBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/generators/MTERTGenerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTESpargeTower.java
  src/main/java/gtnhlanth/common/tileentity/MTESourceChamber.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEMicrowave.java
Labels: refactor

#3062 Remove Dynamic Adjustment logic and instead apply the adjustment right away if a fuel is eligible for super eff increase
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeBoiler.java
Labels: refactor

#3131 Fix wrong packager recipes
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenDustGeneration.java
Labels: bug fix

#3132 Neutronium/black hole bugfix
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTENeutroniumCompressor.java
Labels: bug fix

#3133 Don't add DT catalyst recipes to singleblock
  src/main/java/gregtech/loaders/postload/recipes/MixerRecipes.java
Labels: bug fix

#3064 Beamline Fixes and Balancing
  src/main/java/gtnhlanth/common/beamline/MTEBeamlinePipe.java
  src/main/java/gtnhlanth/common/hatch/MTEHatchOutputBeamline.java
  src/main/java/gtnhlanth/common/tileentity/MTELINAC.java
  src/main/java/gtnhlanth/common/tileentity/MTESourceChamber.java
  src/main/java/gtnhlanth/common/tileentity/MTESynchrotron.java
  src/main/java/gtnhlanth/common/tileentity/MTETargetChamber.java
Labels: Affects Balance, bug fix

#3130 Multiblock solidifer Fixes, and Cleanup
  src/main/java/gregtech/api/enums/GTValues.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: bug fix

#3135 Removes voltage and amperage information in NEI for Research Station
  src/main/java/tectech/recipe/ResearchStationFrontend.java
Labels: enhancement

#3075 Large Large & Larger Turbine Rework
  src/main/java/goodgenerator/blocks/tileEntity/MTEExtremeHeatExchanger.java
  src/main/java/goodgenerator/blocks/tileEntity/MTESupercriticalFluidTurbine.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeTurbineBase.java
  src/main/java/goodgenerator/loader/RecipeLoader2.java
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/api/items/MetaGeneratedTool.java
  src/main/java/gregtech/api/util/GTLanguageManager.java
  src/main/java/gregtech/api/util/TurbineStatCalculator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbineGas.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbineGasAdvanced.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbineHPSteam.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbinePlasma.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbineSteam.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargeTurbineGas.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargeTurbineSCSteam.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargeTurbineSHSteam.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargeTurbineSteam.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbinePlasma.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechLargeTurbinesAndHeatExchanger.java
Labels: enhancement, Affects Balance

#3136 Gorge stuttering fix
  src/main/java/tectech/thing/block/RenderForgeOfGods.java
  src/main/java/tectech/thing/block/TileEntityForgeOfGods.java
Labels: bug fix

#3134 Buffs to creon and superdense plate processing
  src/main/java/gregtech/loaders/oreprocessing/ProcessingPlate.java
  src/main/java/gregtech/loaders/postload/recipes/VacuumFreezerRecipes.java
Labels: Affects Balance

#3108 Rebalance Steam multi
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMixer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
Labels: enhancement, Affects Balance

#3140 Removed implicit forestry dep
  dependencies.gradle
  src/main/java/gregtech/loaders/postload/recipes/FluidExtractorRecipes.java
  src/main/java/gtPlusPlus/core/item/chemistry/AgriculturalChem.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTETreeFarm.java
Labels: refactor

#3141 fix no method found exception when forestry is missing
  src/main/java/gtPlusPlus/core/item/chemistry/AgriculturalChem.java
Labels: bug fix

#3137 Prevent supertank use as a cell when stackSize > 1
  src/main/java/gregtech/common/blocks/ItemMachines.java
Labels: bug fix

#3104 Changes implosion & bio vat recipe generation
  src/main/java/bartworks/common/loaders/BioRecipeLoader.java
  src/main/java/bartworks/common/loaders/StaticRecipeChangeLoaders.java
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingDust.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingGem.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingPlate.java
Labels: refactor, bug fix

#3106 Prevent overflow during power consumption calculation
  src/main/java/gregtech/api/metatileentity/implementations/MTEExtendedPowerMultiBlockBase.java
Labels: bug fix

#3061 Add higher tiered fluid regulators
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/common/covers/CoverFluidRegulator.java
  src/main/java/gregtech/common/items/IDMetaItem01.java
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/49.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/50.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/51.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/52.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/52.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/53.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/53.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/54.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/54.png.mcmeta
Labels: enhancement

#3076 Change sleep potion buff code
  src/main/java/gregtech/mixin/Mixin.java
  src/main/java/gregtech/mixin/interfaces/IBlockStemAccesor.java
  src/main/java/gregtech/mixin/interfaces/PotionExt.java
  src/main/java/gtPlusPlus/core/common/CommonProxy.java
  src/main/java/gtPlusPlus/core/handler/events/PlayerSleepEventHandler.java
  src/main/java/gtPlusPlus/core/potion/GtPotionEffect.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/eigbuckets/EIGStemBucket.java
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/BlockStemMixin.java
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/PotionMixin.java
Labels: refactor, bug fix

#3115 Fix copying multiblock configuration and support Crafting Input Proxy
  src/main/java/gregtech/api/util/GTUtil.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputSlave.java
Labels: enhancement, bug fix

#3145 add missing ismodloaded checks for combs
  src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
Labels: bug fix

#3144 Merge displayed output stacks
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: enhancement

#3146 remove gtpp comb recipes
  src/main/java/gtPlusPlus/xmod/forestry/ForestryHandler.java
  src/main/java/gtPlusPlus/xmod/forestry/bees/recipe/FRGregTechRecipes.java
Labels: enhancement, refactor, bug fix

#3149 Add small clarification to T8 water tooltip
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBaryonicPerfection.java
Labels: enhancement

#3148 Lathe and Autoclave Updates
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiAutoclave.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiLathe.java
Labels: enhancement, bug fix

#3150 A few bugfixes and changes for black hole
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
Labels: bug fix

#3151 Fluid Solidifier Fix
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: bug fix

#3143 Steam Machine Fixes & Improvements
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachineSteel.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/MTESteamMultiBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMixer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWaterPump.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechSteamMultis.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement, bug fix

#3155 Fix UXV 4MA Laser Target Hatch having two result as a research station input
  src/main/java/tectech/loader/recipe/ResearchStationAssemblyLine.java
Labels: bug fix

#3156 Kill bartworks fluid canner registry
  src/main/java/bartworks/system/material/gtenhancement/GTMetaItemEnhancer.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/CellLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/MoltenCellLoader.java
Labels: bug fix

#3154 Recipe conflict squashing
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
Labels: bug fix

#3158 Require screwdriver to adjust laser hatches
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchDynamoTunnel.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchEnergyTunnel.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement

#3147 Various turbine fixes
  src/main/java/goodgenerator/blocks/tileEntity/MTESupercriticalFluidTurbine.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeTurbineBase.java
  src/main/java/goodgenerator/loader/Loaders.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbinePlasma.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbinePlasma.java
Labels: enhancement, bug fix

#3142 Change UIV motor to use molten PHK rather than Superdense
  src/main/java/goodgenerator/loader/ComponentAssemblyLineRecipeLoader.java
Labels: Affects Balance

#3159 Finally Fixing Frames (maybe)
  dependencies.gradle
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/common/blocks/BlockFrameBox.java
Labels: bug fix

#3160 Fix final frame box issues
  dependencies.gradle
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/common/blocks/BlockFrameBox.java
Labels: bug fix

#3164 fix random pack breakage of the day no1
  src/main/java/gregtech/loaders/postload/recipes/MixerRecipes.java
Labels: bug fix

#3138 Add flag to add attaching NBT crafting recipe
  src/main/java/gregtech/api/util/GTModHandler.java
  src/main/java/gregtech/api/util/GTShapelessRecipe.java
Labels: new feature

#3117 Add Antimatter Power Generation
  src/main/java/goodgenerator/blocks/regularBlock/AntimatterRenderBlock.java
  src/main/java/goodgenerator/blocks/structures/AntimatterStructures.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterOutputHatch.java
  src/main/java/goodgenerator/blocks/tileEntity/render/TileAntimatter.java
  src/main/java/goodgenerator/client/ClientProxy.java
  src/main/java/goodgenerator/client/render/AntimatterRenderer.java
  src/main/java/goodgenerator/common/CommonProxy.java
  src/main/java/goodgenerator/loader/IDs_GoodGenerator.java
  src/main/java/goodgenerator/loader/Loaders.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/api/enums/MaterialsUEVplus.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
  src/main/resources/assets/goodgenerator/lang/en_US.lang
  src/main/resources/assets/goodgenerator/models/Antimatter.obj
  src/main/resources/assets/goodgenerator/models/SmoothSphere.obj
  src/main/resources/assets/goodgenerator/shaders/antimatter.frag.glsl
  src/main/resources/assets/goodgenerator/shaders/antimatter.vert.glsl
  src/main/resources/assets/goodgenerator/shaders/protomatter.frag.glsl
  src/main/resources/assets/goodgenerator/shaders/protomatter.vert.glsl
  src/main/resources/assets/goodgenerator/textures/blocks/antimatterAnnihilationMatrix.png
  src/main/resources/assets/goodgenerator/textures/blocks/antimatterContainmentCasing.png
  src/main/resources/assets/goodgenerator/textures/blocks/gravityStabilizationCasing.png
  src/main/resources/assets/goodgenerator/textures/blocks/magneticFluxCasing.png
  src/main/resources/assets/goodgenerator/textures/blocks/protomatterActivationCoil.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.antimatter.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.antimatter.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.protomatter.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.protomatter.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_ANTIMATTER.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_ANTIMATTER_GLOW.png
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: Affects Balance, new feature

#3113 Fix output bus rightclick behavior
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchOutputBus.java
Labels: bug fix

#3166 prioritize gt ores for unification
  src/main/java/gregtech/common/blocks/BlockOresAbstract.java
Labels: enhancement, bug fix

#3105 2.7 Stargate
  src/main/java/goodgenerator/loader/ComponentAssemblyLineMiscRecipes.java
  src/main/java/gregtech/api/enums/MaterialsUEVplus.java
  src/main/java/gregtech/api/enums/OrePrefixes.java
  src/main/java/gregtech/api/recipe/maps/TranscendentPlasmaMixerFrontend.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTETranscendentPlasmaMixer.java
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
  src/main/java/gregtech/loaders/postload/chains/NaniteChain.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/CompressorRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/MixerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/TranscendentPlasmaMixerRecipes.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
  src/main/java/tectech/loader/recipe/Assembler.java
  src/main/java/tectech/loader/recipe/Godforge.java
  src/main/java/tectech/loader/recipe/ResearchStationAssemblyLine.java
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.fluid.sgcrystalslurry.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.fluid.sgcrystalslurry.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.infinityplasma.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.infinityplasma.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/magmatter/nanites.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/magmatter/nanites.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/magmatter/nanites_OVERLAY.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/sgcrystalfluid/cell.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/sgcrystalfluid/cell.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/sgcrystalfluid/cell_OVERLAY.png
Labels: Affects Balance

#3167 Update Antimatter textures
  src/main/resources/assets/goodgenerator/textures/blocks/antimatterAnnihilationMatrix.png
  src/main/resources/assets/goodgenerator/textures/blocks/antimatterContainmentCasing.png
  src/main/resources/assets/goodgenerator/textures/blocks/gravityStabilizationCasing.png
  src/main/resources/assets/goodgenerator/textures/blocks/protomatterActivationCoil.png
Labels: enhancement

#3168 Add antimatter casings and controllers to ItemLists
  src/main/java/goodgenerator/util/ItemRefer.java
Labels: chore

#3152 Merge config categories
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEFluid.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/recipe/RecipeCategories.java
  src/main/java/gregtech/api/recipe/RecipeCategory.java
  src/main/java/gregtech/api/recipe/RecipeCategoryHolder.java
  src/main/java/gregtech/api/recipe/RecipeCategorySetting.java
  src/main/java/gregtech/api/util/GTClientPreference.java
  src/main/java/gregtech/client/GTGUIClientConfig.java
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/GTWorldgenerator.java
  src/main/java/gregtech/common/config/Client.java
  src/main/java/gregtech/common/config/Gregtech.java
  src/main/java/gregtech/common/config/MachineStats.java
  src/main/java/gregtech/common/config/OPStuff.java
  src/main/java/gregtech/common/config/Other.java
  src/main/java/gregtech/common/config/Worldgen.java
  src/main/java/gregtech/common/config/client/ConfigColorModulation.java
  src/main/java/gregtech/common/config/client/ConfigInterface.java
  src/main/java/gregtech/common/config/client/ConfigPreference.java
  src/main/java/gregtech/common/config/client/ConfigRender.java
  src/main/java/gregtech/common/config/client/ConfigWaila.java
  src/main/java/gregtech/common/config/gregtech/ConfigDebug.java
  src/main/java/gregtech/common/config/gregtech/ConfigFeatures.java
  src/main/java/gregtech/common/config/gregtech/ConfigGeneral.java
  src/main/java/gregtech/common/config/gregtech/ConfigHarvestLevel.java
  src/main/java/gregtech/common/config/gregtech/ConfigMachines.java
  src/main/java/gregtech/common/config/gregtech/ConfigOreDropBehavior.java
  src/main/java/gregtech/common/config/gregtech/ConfigPollution.java
  src/main/java/gregtech/common/config/machinestats/ConfigBronzeSolarBoiler.java
  src/main/java/gregtech/common/config/machinestats/ConfigMachines.java
  src/main/java/gregtech/common/config/machinestats/ConfigMassFabricator.java
  src/main/java/gregtech/common/config/machinestats/ConfigMicrowaveEnergyTransmitter.java
  src/main/java/gregtech/common/config/machinestats/ConfigSteelSolarBoiler.java
  src/main/java/gregtech/common/config/machinestats/ConfigTeleporter.java
  src/main/java/gregtech/common/config/worldgen/ConfigEndAsteroids.java
  src/main/java/gregtech/common/config/worldgen/ConfigGeneral.java
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColor.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColorInfinite.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoilerSolar.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoilerSolarSteel.java
  src/main/java/gregtech/common/tileentities/generators/MTEMagicalEnergyAbsorber.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEMassfabricator.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEMicrowaveEnergyTransmitter.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTETeleporter.java
  src/main/java/gregtech/loaders/preload/GTPreLoad.java
  src/main/java/gregtech/nei/GTNEIDefaultHandler.java
  src/main/java/gtPlusPlus/api/recipe/GTPPRecipeCategories.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEMassFabricator.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenBlastSmelter.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenBlastSmelterGTNH.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement, refactor

#3171 Blackhole fixes
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
Labels: bug fix

#3172 Fix crash when opening cover immediately after attaching to pipe
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
Labels: bug fix

#3173 Fix Large HP Turbine reverting to tight mode when scanned
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbineHPSteam.java
Labels: bug fix

#3175 Beamline Fixes Cont.
  src/main/java/gtnhlanth/common/item/MaskList.java
  src/main/java/gtnhlanth/loader/RecipeLoader.java
Labels: bug fix

#3176 More antimatter fixes
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
Labels: enhancement, bug fix

#3174 Rewrite Helioflux Module, add NEI support
  src/main/java/bartworks/MainMod.java
  src/main/java/tectech/loader/recipe/Godforge.java
  src/main/java/tectech/recipe/TecTechRecipeMaps.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge_modules/MTEMoltenModule.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement

#3180 remove reflection from kudatech and access public field directly
  dependencies.gradle
  src/main/java/kubatech/api/helpers/ReflectionHelper.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeEntityCrusher.java
Labels: enhancement

#3181 Antimatter Finishing touches
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
  src/main/java/goodgenerator/blocks/tileEntity/render/TileAntimatter.java
  src/main/java/goodgenerator/client/render/AntimatterRenderer.java
  src/main/resources/assets/goodgenerator/models/Antimatter.obj
  src/main/resources/assets/goodgenerator/models/GlowRing.obj
  src/main/resources/assets/goodgenerator/shaders/antimatter.vert.glsl
  src/main/resources/assets/goodgenerator/shaders/glow.frag.glsl
  src/main/resources/assets/goodgenerator/shaders/glow.vert.glsl
Labels: enhancement

#3040 Fix of Overflow Valve & New features
  src/main/java/gregtech/api/util/GTLanguageManager.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflow.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/items/MetaGeneratedGregtechItems.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: bug fix, new feature

#3178 Fix turbines with less than 100% efficiency not working
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
Labels: bug fix

#3179 Add lore and discovered by for machinist
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#3183 The black hole fixes never end
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/java/gregtech/common/tileentities/render/TileEntityBlackhole.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: bug fix

#3184 Gorge render mem leak - hopeful fix
  src/main/resources/assets/tectech/shaders/star.frag.glsl
Labels: bug fix

#3165 Optimize GTUtility.getTier call
  src/main/java/gregtech/api/util/GTUtility.java
  src/test/java/gregtech/api/util/GTUtilityTest.java
Labels: refactor

#3185 Reduce (useless) memory allocation for detrav fluid scanner
  src/main/java/detrav/DetravLoaderAfterGTPreload.java
  src/main/java/detrav/DetravScannerMod.java
  src/main/java/detrav/net/ProspectingPacket.java
  src/main/java/detrav/utils/FluidColors.java
  src/main/java/gregtech/api/enums/Dimensions.java
  src/main/java/gregtech/api/enums/UndergroundFluidNames.java
Labels: enhancement

#3188 Fix antimatter math to use floats instead of integer division
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
Labels: bug fix

#3182 Recipe conflicts gt++
  src/main/java/gtPlusPlus/core/item/chemistry/AgriculturalChem.java
  src/main/java/gtPlusPlus/plugin/agrichem/BioRecipes.java
Labels: bug fix

#3189 Fix of [Nightly] Steam Tier Furnace has an incorrect tooltip type
  src/main/java/gregtech/api/recipe/RecipeMaps.java
Labels: bug fix

#3169 Port BW config to GTNHLib
  src/main/java/bartworks/API/APIConfigValues.java
  src/main/java/bartworks/MainMod.java
  src/main/java/bartworks/client/gui/BWGuiFactory.java
  src/main/java/bartworks/client/gui/ConfigGUI.java
  src/main/java/bartworks/common/commands/ChangeConfig.java
  src/main/java/bartworks/common/configs/ConfigHandler.java
  src/main/java/bartworks/common/configs/Configuration.java
  src/main/java/bartworks/common/configs/LanderType.java
  src/main/java/bartworks/common/loaders/ItemRegistry.java
  src/main/java/bartworks/common/loaders/RegisterServerCommands.java
  src/main/java/bartworks/common/loaders/recipes/CraftingRecipes.java
  src/main/java/bartworks/common/net/ServerJoinedPacket.java
  src/main/java/bartworks/common/tileentities/classic/TileEntityHeatedWaterPump.java
  src/main/java/bartworks/common/tileentities/multis/MTEBioVat.java
  src/main/java/bartworks/common/tileentities/multis/MTEDeepEarthHeatingPump.java
  src/main/java/bartworks/common/tileentities/multis/MTEElectricImplosionCompressor.java
  src/main/java/bartworks/common/tileentities/multis/MTELESU.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaBlastFurnace.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaChemicalReactor.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaDistillTower.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaOilCracker.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaVacuumFreezer.java
  src/main/java/bartworks/system/material/CircuitGeneration/CircuitImprintLoader.java
  src/main/java/bartworks/system/material/WerkstoffLoader.java
  src/main/java/bartworks/system/material/processingLoaders/DownTierLoader.java
  src/main/java/bartworks/system/oregen/BWWorldGenRoss128b.java
  src/main/java/bartworks/system/oregen/BWWorldGenRoss128ba.java
  src/main/java/bartworks/system/worldgen/BWWorldGenUtil.java
  src/main/java/bartworks/system/worldgen/MapGenRuins.java
  src/main/java/bartworks/util/BWUtil.java
  src/main/java/bwcrossmod/galacticgreg/VoidMinerUtility.java
  src/main/java/bwcrossmod/galacticraft/GalacticraftProxy.java
  src/main/java/bwcrossmod/galacticraft/PlanetsHelperClass.java
  src/main/java/bwcrossmod/galacticraft/planets/ross128b/ChunkProviderRoss128b.java
  src/main/java/bwcrossmod/galacticraft/solarsystems/Ross128SolarSystem.java
  src/main/java/bwcrossmod/thaumcraft/util/ThaumcraftHandler.java
  src/main/java/gregtech/asm/GTCorePlugin.java
  src/main/java/gregtech/mixin/Mixin.java
  src/main/resources/assets/bartworks/lang/en_US.lang
Labels: refactor, bug fix

#3191 More collisions
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/BlockLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/CraftingMaterialLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/DustLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/GemLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/MetalLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/MoltenCellLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/MultipleMetalLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/SimpleMetalLoader.java
  src/main/java/goodgenerator/items/GGMaterial.java
  src/main/java/goodgenerator/util/MaterialFix.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingCrop.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingDust.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingPlate.java
Labels: bug fix

#3192 Remove railcraft oredicts
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
Labels: bug fix

#3195 Don't allow PA or LPF to do HIP/Black hole compression recipes
  src/main/java/gregtech/common/tileentities/machines/multi/MTEProcessingArray.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialMultiMachine.java
Labels: bug fix

#3196 Allow recycling recipes for semi-fluid singleblock gens
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
Labels: enhancement

#3190 Fix QC Computation Bug
  src/main/java/tectech/thing/metaTileEntity/multi/MTEQuantumComputer.java
Labels: bug fix

#3080 Godforge finale
  src/main/java/bartworks/MainMod.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/gregtech/loaders/postload/recipes/BlastFurnaceRecipes.java
  src/main/java/tectech/loader/TecTechConfig.java
  src/main/java/tectech/loader/recipe/BaseRecipeLoader.java
  src/main/java/tectech/loader/recipe/Godforge.java
  src/main/java/tectech/recipe/GodforgePlasmaFrontend.java
  src/main/java/tectech/recipe/TecTechRecipeMaps.java
  src/main/java/tectech/thing/block/RenderForgeOfGods.java
  src/main/java/tectech/thing/block/TileEntityForgeOfGods.java
  src/main/java/tectech/thing/gui/TecTechUITextures.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEForgeOfGods.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge_modules/MTEBaseModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge_modules/MTEExoticModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge_modules/MTEMoltenModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge_modules/MTEPlasmaModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge_modules/MTESmeltingModule.java
  src/main/java/tectech/util/FaceCulledRenderBlocks.java
  src/main/java/tectech/util/FaceVisibility.java
  src/main/java/tectech/util/GodforgeMath.java
  src/main/java/tectech/util/StructureVBO.java
  src/main/java/tectech/util/TextureUpdateRequester.java
  src/main/resources/assets/tectech/lang/en_US.lang
  src/main/resources/assets/tectech/shaders/fadebypass.frag.glsl
  src/main/resources/assets/tectech/shaders/fadebypass.vert.glsl
  src/main/resources/assets/tectech/shaders/gorgeBeam.frag.glsl
  src/main/resources/assets/tectech/shaders/gorgeBeam.vert.glsl
  src/main/resources/assets/tectech/shaders/star.frag.glsl
  src/main/resources/assets/tectech/shaders/star.vert.glsl
  src/main/resources/assets/tectech/textures/gui/background/rainbow_glow.png
  src/main/resources/assets/tectech/textures/gui/button/purple.png
  src/main/resources/assets/tectech/textures/gui/button/purple_pressed.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/heart.png
  src/main/resources/assets/tectech/textures/gui/picture/connector.png
  src/main/resources/assets/tectech/textures/gui/picture/connector_blue.png
  src/main/resources/assets/tectech/textures/gui/picture/connector_blue_opaque.png
  src/main/resources/assets/tectech/textures/gui/picture/connector_empty.png
  src/main/resources/assets/tectech/textures/gui/picture/connector_green.png
  src/main/resources/assets/tectech/textures/gui/picture/connector_green_opaque.png
  src/main/resources/assets/tectech/textures/gui/picture/connector_orange.png
  src/main/resources/assets/tectech/textures/gui/picture/connector_orange_opaque.png
  src/main/resources/assets/tectech/textures/gui/picture/connector_purple.png
  src/main/resources/assets/tectech/textures/gui/picture/connector_purple_opaque.png
  src/main/resources/assets/tectech/textures/gui/picture/connector_red.png
  src/main/resources/assets/tectech/textures/gui/picture/connector_red_opaque.png
  src/main/resources/assets/tectech/textures/gui/picture/connector_switch.png
  src/main/resources/assets/tectech/textures/gui/picture/thanks.png
Labels: Affects Balance, new feature

#3197 Small optimizations & MultiBlockBase cleanup
  src/main/java/bartworks/common/tileentities/multis/MTECircuitAssemblyLine.java
  src/main/java/bartworks/common/tileentities/multis/MTEHighTempGasCooledReactor.java
  src/main/java/bartworks/common/tileentities/multis/MTEThoriumHighTempReactor.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaBlastFurnace.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaOilCracker.java
  src/main/java/bartworks/common/tileentities/multis/mega/MegaMultiBlockBase.java
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/goodgenerator/blocks/tileEntity/MTECoolantTower.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEPreciseAssembler.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeFusionComputer.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeTurbineBase.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEExtendedPowerMultiBlockBase.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/util/ExoticEnergyInputHelper.java
  src/main/java/gregtech/api/util/GTUtil.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/ValidMTEList.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAssemblyLine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDieselEngine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDrillerBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEElectricBlastFurnace.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEExtremeDieselEngine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEFusionComputer.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiFurnace.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEOilCracker.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPCBFactory.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPlasmaForge.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEProcessingArray.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GTPPMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/MTESteamMultiBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialMultiMachine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialVacuumFreezer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIsaMill.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvEBF.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEElementalDuplicator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTELargeRocketEngine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTETreeFarm.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/MTEChemicalPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/mega/MTEMegaAlloyBlastSmelter.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/storage/GregtechMetaTileEntity_PowerSubStationController.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeIndustrialGreenhouse.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEQuantumComputer.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEResearchStation.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTETeslaTower.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
Labels: refactor

#3198 Revert one part of bartworks collision removal
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/SimpleMetalLoader.java
Labels: bug fix

#3200 Fix for render rotations on antimatter forge (again) and HILE
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
  src/main/java/goodgenerator/blocks/tileEntity/render/TileAntimatter.java
  src/main/java/gregtech/common/tileentities/render/TileEntityLaser.java
Labels: bug fix

#3206 Fix air intake and reservoir hatch tooltips
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchFluidGenerator.java
Labels: bug fix

#3205 fix the check preventing the keyboard transformer from transforming lwjgl3's Keyboard
  src/main/java/gregtech/asm/GTCorePlugin.java
Labels: bug fix

#3202 Allow unsafe oredicts to be shown in nei
  src/main/java/gregtech/api/util/GTOreDictUnificator.java
Labels: bug fix

#3209 Fixes cables/pipes not being able to attach to each other
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
Labels: bug fix

#3210 Clarify Antimatter Forge tooltip
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
Labels: enhancement

#3212 fix ioob errors
  src/main/java/gtPlusPlus/core/util/minecraft/ItemUtils.java
Labels: bug fix

#3214 Fix GT++ index out of bounds
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderAlgaeFarm.java
Labels: bug fix

#3215 Remove waila black hole info
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
Labels: enhancement

#3216 Fix steam min casings
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMixer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWaterPump.java
Labels: bug fix

#3217 Fix stocking bus on black hole
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
Labels: bug fix

#3220 fix coal multiplier in code
  src/main/java/gregtech/api/enums/Materials.java
Labels: bug fix

#3221 Fix froth vacuum furnace recipes
  src/main/java/gtPlusPlus/core/item/chemistry/MilledOreProcessing.java
Labels: bug fix

#3186 Fix of new Overflow Valve
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/enums/GregtechItemList.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/items/MetaGeneratedGregtechItems.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/items/MetaGeneratedItemIDs.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: bug fix

#3223 Fix pcb factory nei preview
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPCBFactory.java
Labels: bug fix

#3228 Remove unused class
  src/main/java/gtPlusPlus/core/util/data/AES.java
Labels: refactor

#3226 Infinite Spraycan Additions
  src/main/java/gregtech/api/enums/Dyes.java
  src/main/java/gregtech/api/enums/SoundResource.java
  src/main/java/gregtech/api/interfaces/IItemBehaviour.java
  src/main/java/gregtech/api/items/GTGenericItem.java
  src/main/java/gregtech/api/items/MetaBaseItem.java
  src/main/java/gregtech/api/items/MetaGeneratedItem.java
  src/main/java/gregtech/api/net/GTPacketInfiniteSpraycan.java
  src/main/java/gregtech/api/util/ColoredBlockContainer.java
  src/main/java/gregtech/client/GTMouseEventHandler.java
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gregtech/common/blocks/BlockMachines.java
  src/main/java/gregtech/common/gui/modularui/uifactory/SelectItemUIFactory.java
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColor.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColorInfinite.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColorRemover.java
  src/main/java/gregtech/common/render/items/DataStickRenderer.java
  src/main/java/gregtech/common/render/items/InfiniteSprayCanRenderer.java
  src/main/java/gregtech/common/render/items/MetaGeneratedItemRenderer.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/sounds.json
  src/main/resources/assets/gregtech/sounds/spraycan_lock.ogg
  src/main/resources/assets/gregtech/sounds/spraycan_shake.ogg
  src/main/resources/assets/gregtech/sounds/spraycan_unlock.ogg
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/468/1.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/468/2.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/468/3.png
Labels: enhancement, new feature

#3229 remove empty config
  src/main/java/detrav/DetravScannerMod.java
Labels: refactor
