Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2024-10, with the labels that each got.

#3303 Fix uv plasma gen assembler recipe
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
Labels: bug fix

#3306 Revert zirconium removal
  src/main/java/gtnhlanth/common/register/WerkstoffMaterialPool.java
Labels: bug fix

#3310 Fix wireless EU voiding in multiplayer for non-network owners
  src/main/java/gregtech/common/misc/WirelessNetworkManager.java
Labels: bug fix

#3309 Revert solar reflector and reinforced steam turbine recipe
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
Labels: bug fix

#3315 Remove unnecessary NBT compression from pipe packet
  src/main/java/tectech/mechanics/pipe/PipeActivityMessage.java
Labels: refactor

#3314 Fix T3 waterline being lossy and reduces juice aluminium output due the aluminium hydroxide stoik changes
  src/main/java/gregtech/loaders/postload/chains/BauxiteRefineChain.java
  src/main/java/gregtech/loaders/postload/chains/PurifiedWaterRecipes.java
Labels: bug fix

#3316 Fix energy cost
  src/main/java/gregtech/api/metatileentity/implementations/MTEExtendedPowerMultiBlockBase.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: bug fix

#3313 Fix multi fluid solidifier auto build
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: bug fix

#3317 Refactor tesla tower spark packet
  src/main/java/tectech/mechanics/spark/RendererMessage.java
  src/main/java/tectech/mechanics/spark/ThaumSpark.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTETeslaTower.java
  src/main/java/tectech/thing/metaTileEntity/single/MTETeslaCoil.java
Labels: refactor

#3318 Some bio lab recipes should be real
  src/main/java/bartworks/system/material/processingLoaders/AdditionalRecipes.java
Labels: bug fix

#3319 Revert material hashing
  src/main/java/gregtech/api/enums/OrePrefixes.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingBlock.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingDust.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingGem.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingOre.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingOreSmelting.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingPlate.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingStick.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingTransforming.java
Labels: bug fix

#3259 Fixed Laser & Data pipe every 32 tick connection update
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeData.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeEnergy.java
Labels: enhancement

#3321 Fix issues with catalyst damage + empty catalyst output
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/MTEChemicalPlant.java
Labels: bug fix

#3322 Fix flocculation plant deforming when it has a cover emitting a strong redstone signal
  src/main/java/gregtech/api/util/GTStructureUtility.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitFlocculation.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialWashPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEIndustrialFishingPond.java
Labels: bug fix

#3320 Six Phased Copper Animation Fix
  src/main/java/gregtech/common/render/items/GlitchEffectRenderer.java
Labels: bug fix

#3213 Godforge encore
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
  src/main/java/tectech/loader/recipe/BaseRecipeLoader.java
  src/main/java/tectech/loader/recipe/Godforge.java
  src/main/java/tectech/thing/block/RenderForgeOfGods.java
  src/main/java/tectech/thing/block/TileEntityForgeOfGods.java
  src/main/java/tectech/thing/gui/TecTechUITextures.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEForgeOfGods.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge_modules/MTEBaseModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge_modules/MTEExoticModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge_modules/MTEMoltenModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge_modules/MTESmeltingModule.java
  src/main/java/tectech/util/GodforgeMath.java
  src/main/java/tectech/util/TTUtility.java
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.plasma.infinity.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.plasma.infinity.png.mcmeta
  src/main/resources/assets/tectech/lang/en_US.lang
  src/main/resources/assets/tectech/textures/gui/background/red_glow.png
  src/main/resources/assets/tectech/textures/gui/button/celestial.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/rainbow_spiral.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/rainbow_spiral_off.png
  src/main/resources/assets/tectech/textures/gui/picture/overlay_red.png
  src/main/resources/assets/tectech/textures/gui/picture/rainbow_square.png
Labels: bug fix, new feature

#3325 Fix luag macerating
  src/main/java/gregtech/loaders/postload/recipes/Pulverizer.java
Labels: bug fix

#3324 Remove collisions
  src/main/java/bartworks/common/loaders/RadioHatchMaterialLoader.java
  src/main/java/bartworks/system/material/gtenhancement/PlatinumSludgeOverHaul.java
  src/main/java/goodgenerator/util/CrackRecipeAdder.java
  src/main/java/goodgenerator/util/MaterialFix.java
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingBlock.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingCrushedOre.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingDirty.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingGem.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingLog.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingOre.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingShaping.java
  src/main/java/gregtech/loaders/postload/recipes/BreweryRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/ChemicalRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/CompressorRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/DistilleryRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/FermenterRecipes.java
  src/main/java/gtPlusPlus/core/item/chemistry/CoalTar.java
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
  src/main/java/gtPlusPlus/xmod/bop/blocks/base/LogBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenBlastSmelter.java
  src/main/java/gtnhlanth/loader/RecipeLoader.java
Labels: bug fix

#3326 Fix annealed copper loss
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
Labels: bug fix

#3327 Fix molecular transformer recipes
  src/main/java/gtPlusPlus/xmod/gregtech/HandlerGT.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderMolecularTransformer.java
Labels: bug fix

#3328 Reword waila to say currently instead of probably
  src/main/java/goodgenerator/blocks/tileEntity/MTEMultiNqGenerator.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEUniversalChemicalFuelEngine.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement

#3329 Fix data stick render not working when holding shift
  src/main/java/gregtech/common/render/items/MetaGeneratedItemRenderer.java
Labels: bug fix

#3331 Change Antimatter Forge cycle time from 100 ticks to 20 ticks
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
Labels: bug fix

#3335 Restore hafnium recipe
  src/main/java/gtnhlanth/loader/RecipeLoader.java
Labels: bug fix

#3337 Fix the cursed chembath again
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialWashPlant.java
Labels: bug fix

#3342 16x cutting factory frame texture that resembles the old one
  src/main/resources/assets/miscutils/textures/blocks/metro/TEXTURE_TECH_A.png
  src/main/resources/assets/miscutils/textures/blocks/metro/TEXTURE_TECH_B.png
Labels: enhancement

#3344 Remove unneeded recipe constant, fix sb compressor
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingPlate.java
Labels: bug fix

#3347 fix incorrect fluid shaper tooltip
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: bug fix

#3338 Remove tremendous and useless RAM allocation from GT++ algae pond recipes
  src/main/java/gtPlusPlus/api/objects/data/WeightedCollection.java
  src/main/java/gtPlusPlus/xmod/gregtech/HandlerGT.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/algae/MTEAlgaePondBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderAlgaeFarm.java
Labels: enhancement, refactor

#3330 Allow chemical bath to count flowing water as a valid fluid block
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialWashPlant.java
Labels: bug fix

#3348 Add Infinity+ coil recycling
  src/main/java/gregtech/loaders/postload/recipes/ArcFurnaceRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/Pulverizer.java
Labels: enhancement

#3346 Allow more hatches on mega oil cracker
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaOilCracker.java
Labels: enhancement

#3341 Add Runite Ore to Deep Dark
  src/main/java/gtPlusPlus/everglades/gen/gt/WorldGen_Ores.java
Labels: enhancement

#3353 fix adv assline not respecting gt_no_hatch for energy hatches
  src/main/java/ggfab/mte/MTEAdvAssLine.java
Labels: bug fix

#3351 UHV transmission couldn't be craftable because of for loop lenght
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
Labels: bug fix

#3349 Make frostproof casing use circuit 1 and add sturdy casing to circuit 2
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
Labels: bug fix

#3359 gt++ lang fixes
  src/main/resources/assets/miscutils/lang/en_US.lang
Labels: bug fix

#3362 Change small/tiny ash to chanced output full dust in EBF
  src/main/java/gregtech/loaders/oreprocessing/ProcessingOre.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingRawOre.java
  src/main/java/gregtech/loaders/postload/recipes/BlastFurnaceRecipes.java
Labels: enhancement

#3361 Enable solidifier generation for some goodgen materials
  src/main/java/goodgenerator/items/GGMaterial.java
Labels: bug fix

#3360 fix missing space in coolant cell item names
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
Labels: bug fix

#3356 Add an incoloy-903 recipe to ABS
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
Labels: Affects Balance

#3364 Remove high tier single block pumps
  src/main/java/bartworks/common/loaders/recipes/AssemblyLine.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/loaders/load/MTERecipeLoader.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
Labels: bug fix

#3363 Blackhole fixes
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
Labels: bug fix

#3365 Fix UMV/UXV 4mA+ laser recipes
  src/main/java/tectech/loader/recipe/ResearchStationAssemblyLine.java
Labels: bug fix

#3367 Restore yeeted constructors on sickblaze
  src/main/java/gtPlusPlus/core/entity/projectile/EntityToxinballSmall.java
Labels: bug fix

#3350 Fixed dust output of Ore Drilling Plant
  src/main/java/gregtech/common/blocks/TileEntityOres.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEOreDrillingPlantBase.java
Labels: bug fix

#3354 Small texture change by Krezhvick, fix gtpp having sticks with wrong pixels
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_AUTOCLAVE.png
  src/main/resources/assets/gregtech/textures/items/materialicons/ENRICHED/stick_OVERLAY.png
  src/main/resources/assets/gregtech/textures/items/materialicons/GEM_A/stick_OVERLAY.png
  src/main/resources/assets/gregtech/textures/items/materialicons/NUCLEAR/stick_OVERLAY.png
  src/main/resources/assets/gregtech/textures/items/materialicons/REFINED/stick_OVERLAY.png
  src/main/resources/assets/gregtech/textures/items/materialicons/SHARDS/stick_OVERLAY.png
  src/main/resources/assets/gregtech/textures/items/materialicons/SHINY/stick_OVERLAY.png
  src/main/resources/assets/miscutils/textures/blocks/TileEntities/sterileCasing.png
Labels: enhancement, bug fix

#3352 Pyrolyse oven controller having transparent texture in dev fix
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPyrolyseOven.java
Labels: bug fix

#3340 Fix T8/T9 FluidCore research time
  src/main/java/goodgenerator/loader/RecipeLoader2.java
Labels: enhancement

#3255 Crop Name localization
  src/main/java/gregtech/api/util/GTBaseCrop.java
Labels: enhancement

#3339 Fix SLAM (Antimatter Generator) produce 0 in wireless mode. Add avg efficiency of 10 last cycles.
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
Labels: bug fix

#3368 Allow input hatch on multiblock compressors
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEHIPCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEIndustrialCompressor.java
Labels: enhancement

#3369 Fix waterline multiblocks not resuming their first recipe on server start
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
Labels: bug fix

#3366 Amazon warehouse downtiering
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
Labels: Affects Balance

#3371 Moved Superdense Transcendental Metal Plate to Black Hole only
  src/main/java/gregtech/api/enums/Materials.java
Labels: Affects Balance

#3372 Small rework to black hole instability
  src/main/java/gregtech/api/recipe/check/CheckRecipeResultRegistry.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#3334 Improved & cleaned up wormhole generator
  src/main/java/gregtech/api/enums/GTValues.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEWormholeGenerator.java
Labels: enhancement, bug fix

#3375 Antimatter Amd fix
  src/main/java/goodgenerator/client/render/AntimatterRenderer.java
  src/main/resources/assets/goodgenerator/shaders/antimatter.vert.glsl
Labels: bug fix

#3333 Refactors shift tooltips on MetaBaseItem a bit
  src/main/java/gregtech/api/interfaces/IItemBehaviour.java
  src/main/java/gregtech/api/items/MetaBaseItem.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColorInfinite.java
Labels: refactor, bug fix

#3377 Fix several issues with ender tank covers
  src/main/java/tectech/mechanics/enderStorage/EnderFluidContainer.java
  src/main/java/tectech/mechanics/enderStorage/EnderLinkTag.java
  src/main/java/tectech/mechanics/enderStorage/EnderLinkTank.java
  src/main/java/tectech/mechanics/enderStorage/EnderWorldSavedData.java
  src/main/java/tectech/thing/cover/CoverEnderFluidLink.java
Labels: bug fix

#3332 Fix a rare overflow case when a fuel is so large that it breaks the super efficiency check.
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeBoiler.java
Labels: bug fix

#3312 Reworked cleanroom structure check.
  src/main/java/gregtech/api/util/MultiblockTooltipBuilder.java
  src/main/java/gregtech/common/config/MachineStats.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTECleanroom.java
  src/main/java/gregtech/loaders/preload/GTPreLoad.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement, refactor, bug fix

#3380 Fix AAL
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/gregtech/api/util/OverclockCalculator.java
Labels: bug fix

#3379 Deep earth heating pump Slight Rework and Balance Attempt
  src/main/java/bartworks/common/configs/Configuration.java
  src/main/java/bartworks/common/loaders/recipes/Assembler.java
  src/main/java/bartworks/common/loaders/recipes/AssemblyLine.java
  src/main/java/bartworks/common/tileentities/multis/MTEDeepEarthHeatingPump.java
Labels: Affects Balance

#3385 One last ra2 fix
  src/main/java/gtnhlanth/loader/RecipeLoader.java
Labels: bug fix

#3384 Fix bacterial vat fluid render
  src/main/java/bartworks/client/renderer/RendererGlassBlock.java
  src/main/java/bartworks/client/renderer/RendererSwitchingColorFluid.java
Labels: bug fix

#3386 remove Tessellator field from RenderQuantumStuff
  src/main/java/tectech/thing/block/RenderQuantumStuff.java
Labels: bug fix

#3383 Fix and Buff Solidifier Min Casing Check and Improve Tooltip
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: enhancement, bug fix

#3387 fix Isophthalate typo
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
Labels: bug fix

#3388 Fix DOB comb
  src/main/java/gregtech/api/util/GTForestryCompat.java
Labels: bug fix

#3391 Fix mega oil cracker hatch adder
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaOilCracker.java
Labels: bug fix

#3390 Blackhole render enhancement
  src/main/java/gregtech/common/render/BlackholeRenderer.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/java/gregtech/common/tileentities/render/TileEntityBlackhole.java
Labels: enhancement

#3394 Fix Production of SC Steam on the EHE
  src/main/java/goodgenerator/blocks/tileEntity/MTEExtremeHeatExchanger.java
  src/main/java/goodgenerator/loader/RecipeLoader2.java
Labels: bug fix

#3393 Change extractor structure
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialExtractor.java
Labels: enhancement

#3382 Buff TGS sapling production
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTETreeFarm.java
Labels: Affects Balance

#3345 Godforge afterparty
  src/main/java/tectech/loader/recipe/Godforge.java
  src/main/java/tectech/loader/thing/MachineLoader.java
  src/main/java/tectech/loader/thing/ThingsLoader.java
  src/main/java/tectech/thing/CustomItemList.java
  src/main/java/tectech/thing/block/RenderForgeOfGods.java
  src/main/java/tectech/thing/block/TileEntityForgeOfGods.java
  src/main/java/tectech/thing/gui/TecTechUITextures.java
  src/main/java/tectech/thing/item/FakeItemQGP.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/ForgeOfGodsRingsStructureString.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/ForgeOfGodsStructureString.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/ForgeOfGodsUI.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEBaseModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEExoticModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEMoltenModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEPlasmaModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTESmeltingModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/color/ForgeOfGodsStarColor.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/color/StarColorSetting.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/color/StarColorStorage.java
  src/main/java/tectech/util/GodforgeMath.java
  src/main/resources/assets/tectech/lang/en_US.lang
  src/main/resources/assets/tectech/textures/gui/background/white_glow_half.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/batch_mode_off.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/batch_mode_on.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/furnace_mode_off.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/furnace_mode_on.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/input_separation_off.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/input_separation_on.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/loaf_mode_off.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/loaf_mode_on.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/recipe_locked.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/recipe_unlocked.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/structure_check_off.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/structure_check_on.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/voiding_both.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/voiding_disabled.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/voiding_fluids.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/voiding_items.png
  src/main/resources/assets/tectech/textures/gui/picture/heat_sink_16x8.png
  src/main/resources/assets/tectech/textures/gui/picture/unselected_option.png
  src/main/resources/assets/tectech/textures/items/fakeItemQGP.png
  src/main/resources/assets/tectech/textures/items/fakeItemQGP.png.mcmeta
  src/test/java/tectech/thing/metaTileEntity/multi/godforge/color/ForgeOfGodsStarColorTest.java
Labels: bug fix

#3400 Superdense plate integration
  src/main/java/bwcrossmod/tectech/TecTechResearchLoader.java
  src/main/java/goodgenerator/loader/ComponentAssemblyLineMiscRecipes.java
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/loaders/postload/chains/NaniteChain.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblyLineRecipes.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderChemicalSkips.java
  src/main/java/tectech/loader/recipe/AssemblyLine.java
  src/main/java/tectech/loader/recipe/ResearchStationAssemblyLine.java
Labels: Affects Balance

#3398 Allow use high tier fluid regulators as cover.
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
Labels: new feature

#3397 Fix missing circuit replacements in AL recipies
  src/main/java/goodgenerator/loader/RecipeLoader.java
  src/main/java/gregtech/loaders/postload/chains/PurifiedWaterRecipes.java
  src/main/java/tectech/loader/recipe/ResearchStationAssemblyLine.java
Labels: bug fix

#3403 Fix NPE on IC2 recycler blacklist
  src/main/java/gregtech/api/util/GTModHandler.java
  src/main/java/gregtech/common/GTProxy.java
Labels: bug fix

#3404 Use explicit internal name for Diphenylisophthalate
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
Labels: bug fix

#3406 Fix log 1:6 in cutting machine
  src/main/java/gregtech/loaders/oreprocessing/ProcessingLog.java
Labels: bug fix

#3405 Right clicking water purification units places blocks
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBase.java
Labels: bug fix

#3410 Remove method in multiblock tooltip
  src/main/java/gregtech/api/util/MultiblockTooltipBuilder.java
Labels: refactor

#3419 save debug mode to NBT to prevent it turning it off on game reload
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
Labels: bug fix

#3414 fix world leak caused by BlockPos class from GT++
  src/main/java/gtPlusPlus/api/objects/minecraft/BlockPos.java
  src/main/java/gtPlusPlus/core/tileentities/machines/TileEntityBaseFluidCollector.java
  src/main/java/gtPlusPlus/everglades/block/BlockEvergladesPortal.java
Labels: refactor, bug fix

#3409 Render fixes
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/java/gregtech/common/tileentities/render/TileEntityLaser.java
Labels: bug fix

#3402 Change sterile casing texture
  src/main/resources/assets/miscutils/textures/blocks/TileEntities/sterileCasing.png
  src/main/resources/assets/miscutils/textures/blocks/iconsets/controllerFaces/treeFarm.png
  src/main/resources/assets/miscutils/textures/blocks/iconsets/controllerFaces/treeFarm.png.mcmeta
  src/main/resources/assets/miscutils/textures/blocks/iconsets/controllerFaces/treeFarmActive.png
  src/main/resources/assets/miscutils/textures/blocks/iconsets/controllerFaces/treeFarmActive.png.mcmeta
Labels: enhancement

#3420 fix waterline cycle breaking on reload
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaDistillTower.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDistillationTower.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTESpargeTower.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvDistillationTower.java
Labels: bug fix

#3413 convert the debug button to a LockedWhileActiveButton
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
Labels: bug fix

#3421 Replace Bee description containing Diddy with his new socials for obvious reasons
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: chore

#3422 add cycle idle status for waterline units
  src/main/java/gregtech/api/recipe/check/CheckRecipeResultRegistry.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBase.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement, bug fix

#3430 fix plasma arc furnace recipe
  src/main/java/gregtech/loaders/load/MTERecipeLoader.java
Labels: bug fix

#3433 Various waterline bugfixes
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/common/items/MetaGeneratedItem03.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiLathe.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBaryonicPerfection.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitClarifier.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitDegasser.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitFlocculation.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitOzonation.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitPhAdjustment.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitPlasmaHeater.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitUVTreatment.java
  src/main/resources/assets/gregtech/sounds/PurificationPlantLoop.ogg
Labels: bug fix

#3426 Delete 4 unused GT++ classes
  src/main/java/gtPlusPlus/api/objects/minecraft/AABB.java
  src/main/java/gtPlusPlus/core/handler/events/CustomMovementHandler.java
  src/main/java/gtPlusPlus/core/handler/events/SneakManager.java
  src/main/java/gtPlusPlus/core/inventories/InventoryEggBox.java
Labels: refactor

#3425 Fix mabs crash when breaking energy hatches
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/mega/MTEMegaAlloyBlastSmelter.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
Labels: bug fix

#3436 Hide WAILA and remove collision of render blocks
  src/main/java/goodgenerator/blocks/regularBlock/AntimatterRenderBlock.java
  src/main/java/gregtech/common/blocks/BlockBlackholeRenderer.java
  src/main/java/gregtech/common/blocks/BlockWormholeRender.java
  src/main/java/tectech/thing/block/BlockEOHRender.java
  src/main/java/tectech/thing/block/BlockForgeOfGods.java
Labels: bug fix
