Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2024-12, with the labels that each got.

#3582 Waterline + Gorge tooltip formatting changes
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBaryonicPerfection.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitDegasser.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitOzonation.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitPlasmaHeater.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitUVTreatment.java
  src/main/java/gregtech/loaders/postload/chains/PurifiedWaterRecipes.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
Labels: enhancement

#3583 Minor Godforge fixes
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/util/ForgeOfGodsUI.java
Labels: bug fix

#3584 remove tooltip wrong information from HILE
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
Labels: bug fix

#3585 Fix ME Output Hatch void protection checks
  src/functionalTest/java/gregtech/test/mock/MockIVoidableMachine.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaDistillTower.java
  src/main/java/gregtech/api/interfaces/fluid/IFluidStore.java
  src/main/java/gregtech/api/interfaces/tileentity/IVoidable.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/Controller.java
  src/main/java/gregtech/api/util/OutputHatchWrapper.java
  src/main/java/gregtech/api/util/VoidProtectionHelper.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDistillationTower.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvDistillationTower.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTENuclearReactor.java
Labels: bug fix

#3574 Fix scanning calculations/optimal flow metrics of turbines
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargeTurbineGas.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargeTurbineSCSteam.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargeTurbineSHSteam.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargeTurbineSteam.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbinePlasma.java
Labels: bug fix

#3587 Fix Iron III Chloride chemical formula tooltip
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
Labels: enhancement

#3588 Fix crystal seeds recipes
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
Labels: bug fix

#3589 Fixed infinite oil rig getting stuck
  src/main/java/gregtech/common/tileentities/machines/multi/MTEOilDrillBase.java
Labels: bug fix

#3591 Extend render range
  src/main/java/tectech/thing/block/TileEntityEyeOfHarmony.java
  src/main/java/tectech/thing/block/TileEntityForgeOfGods.java
Labels: enhancement

#3593 Add proper render bounding box for Godforge
  src/main/java/tectech/thing/block/TileEntityForgeOfGods.java
Labels: enhancement

#3594 Fix ME output hatch void protection again
  src/functionalTest/java/gregtech/test/mock/MockIVoidableMachine.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaDistillTower.java
  src/main/java/gregtech/api/interfaces/fluid/IFluidStore.java
  src/main/java/gregtech/api/interfaces/tileentity/IVoidable.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/multitileentity/multiblock/base/Controller.java
  src/main/java/gregtech/api/util/OutputHatchWrapper.java
  src/main/java/gregtech/api/util/VoidProtectionHelper.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDistillationTower.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvDistillationTower.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTENuclearReactor.java
Labels: bug fix

#3596 Fix missing null check in output fluids UI info
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: bug fix

#3597 Fix ME output hatch partial voiding multi fluid output
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
Labels: bug fix

#3598 Add an animated texture to brewery multi
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_MULTI_BREWERY.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_MULTI_BREWERY_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_MULTI_BREWERY_ACTIVE.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_MULTI_BREWERY_ACTIVE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_MULTI_BREWERY_ACTIVE_GLOW.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_MULTI_BREWERY_GLOW.png
Labels: enhancement

#3599 Fix uxv wrap recipe
  src/main/java/goodgenerator/loader/ComponentAssemblyLineMiscRecipes.java
Labels: bug fix

#3600 try fix NPE in yotta tank
  src/main/java/goodgenerator/blocks/tileEntity/MTEYottaFluidTank.java
Labels: bug fix

#3602 Fix dense vs regular SC Steam difference
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargeTurbineSCSteam.java
Labels: bug fix

#3603 Fix nether quartz block conflict
  src/main/java/gregtech/api/util/GTRecipeRegistrator.java
  src/main/java/gregtech/loaders/postload/recipes/Pulverizer.java
Labels: bug fix

#3604 LaB6 Recycling Recipes
  src/main/java/bartworks/common/loaders/ElectricImplosionCompressorRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/ImplosionCompressorRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/LatheRecipes.java
Labels: bug fix

#3605 Remove beamline debug recipes
  src/main/java/gtnhlanth/common/tileentity/recipe/beamline/BeamlineRecipeLoader.java
Labels: chore

#3606 fix SC Turbine giving Steam instead of SH Steam
  src/main/java/goodgenerator/blocks/tileEntity/MTESupercriticalFluidTurbine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargeTurbineSCSteam.java
Labels: bug fix

#3607 fix UCFE Scanner output
  src/main/java/goodgenerator/blocks/tileEntity/MTEUniversalChemicalFuelEngine.java
Labels: bug fix

#3609 Fix Incorrect bee allele definitions and elevate invalid definition logs to warnings.
  src/main/java/gregtech/common/bees/GTAlleleHelper.java
  src/main/java/gregtech/loaders/misc/GTBeeDefinition.java
  src/main/java/gregtech/loaders/misc/GTBranchDefinition.java
Labels: bug fix

#3592 Tweaking EEC EU comsumption
  src/main/java/kubatech/loaders/MobHandlerLoader.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeEntityCrusher.java
Labels: enhancement, Affects Balance

#3610 restore missing auto-workbench button textures
  src/main/resources/assets/miscutils/textures/gui/overlay_button/mode_0.png
  src/main/resources/assets/miscutils/textures/gui/overlay_button/mode_1.png
  src/main/resources/assets/miscutils/textures/gui/overlay_button/mode_2.png
  src/main/resources/assets/miscutils/textures/gui/overlay_button/mode_3.png
  src/main/resources/assets/miscutils/textures/gui/overlay_button/mode_4.png
  src/main/resources/assets/miscutils/textures/gui/overlay_button/mode_5.png
  src/main/resources/assets/miscutils/textures/gui/overlay_button/mode_6.png
  src/main/resources/assets/miscutils/textures/gui/overlay_button/mode_7.png
  src/main/resources/assets/miscutils/textures/gui/overlay_button/mode_8.png
  src/main/resources/assets/miscutils/textures/gui/overlay_button/mode_9.png
  src/main/resources/assets/miscutils/textures/gui/overlay_button/throughput_0.png
  src/main/resources/assets/miscutils/textures/gui/overlay_button/throughput_1.png
  src/main/resources/assets/miscutils/textures/gui/overlay_button/throughput_2.png
  src/main/resources/assets/miscutils/textures/gui/overlay_button/throughput_3.png
Labels: bug fix

#3611 Revert the ignoble computer cube texture to its former glory
  src/main/resources/assets/miscutils/textures/items/MU-metaitem.01/55.png
Labels: enhancement

#3612 Resolved Recipe Conflict with pipe casing
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
Labels: bug fix

#3613 fix a few recipe conflicts II
  src/main/java/gtnhlanth/loader/RecipeLoader.java
Labels: bug fix

#3614 Fixing AE2 Crystal Seeds Pt. 2
  src/main/java/gregtech/loaders/postload/recipes/AutoclaveRecipes.java
Labels: bug fix

#3615 Remove second Description Line of Network Switch
  src/main/java/tectech/thing/metaTileEntity/multi/MTENetworkSwitch.java
  src/main/resources/assets/tectech/lang/zh_CN.lang
Labels: bug fix

#3616 Add efficiency to cleanroom gui
  src/main/java/gregtech/common/tileentities/machines/multi/MTECleanroom.java
Labels: enhancement

#3590 Decrease TF-specific vein max height spawn
  src/main/java/gregtech/api/enums/OreMixes.java
Labels: enhancement

#3527 Downtier Transformation Module
  src/main/java/bartworks/common/loaders/recipes/CraftingRecipes.java
  src/main/java/bartworks/system/material/processingLoaders/AdditionalRecipes.java
Labels: Affects Balance

#3555 Consistent recipe check order for ME crafting buses.
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: bug fix

#3586 Add WAILA info displaying recipe outputs to multiblocks
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#3565 Fix NEI fuel recipes for large boilers
  src/main/java/gregtech/api/recipe/maps/LargeBoilerFuelBackend.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeBoilerBronze.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeBoilerSteel.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeBoilerTitanium.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeBoilerTungstenSteel.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialForgeHammer.java
Labels: bug fix

#3485 Add an upgradable hand pump
  src/main/java/gtPlusPlus/core/item/ModItems.java
  src/main/java/gtPlusPlus/core/item/tool/misc/ItemGregtechPump.java
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
  src/main/resources/assets/miscutils/textures/items/MU-metatool.01/4.png
Labels: new feature

#3618 Remove Compact Fusion force chunk loading
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer1.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer2.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer3.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer4.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer5.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeFusionComputer.java
Labels: refactor

#3619 Remove DTPF force chunk loading
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPlasmaForge.java
Labels: refactor

#3515 Refactored BioLab and Radio Hatch Recipes
  src/main/java/bartworks/common/loaders/recipes/CraftingRecipes.java
  src/main/java/gregtech/api/enums/ItemList.java
Labels: refactor

#3622 bandaid fix for rotated turbine overlay
  src/main/java/gregtech/api/util/GTUtilityClient.java
Labels: bug fix

#3623 localize research station mode for waila
  src/main/java/tectech/thing/metaTileEntity/multi/MTEResearchStation.java
Labels: bug fix

#3628 Fix modded music disk playback in the electric jukebox using the new GTNHLib api
  dependencies.gradle
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/util/GTMusicSystem.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEBetterJukebox.java
Labels: bug fix

#3629 Fix DTPF convergence item consumption
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPlasmaForge.java
Labels: bug fix

#3632 Fix fusion hatch textures
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
Labels: bug fix

#3631 Delete the RunGC command
  src/main/java/bartworks/common/commands/RunGC.java
  src/main/java/bartworks/common/loaders/RegisterServerCommands.java
Labels: enhancement

#3636 Fix Wrong Nether/Fluix Quartz Seed Amount in Autoclave
  src/main/java/gregtech/loaders/postload/recipes/AutoclaveRecipes.java
Labels: bug fix

#3638 Fix LSC wireless rebalance push wrong info.
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
Labels: bug fix

#3635 Fix Rocket engine pollution
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/generators/MTERocketFuelGeneratorBase.java
Labels: bug fix

#3634 Remove a few more commands the shouldn't be in use.
  src/main/java/bartworks/common/commands/ClearCraftingCache.java
  src/main/java/bartworks/common/commands/GetWorkingDirectory.java
  src/main/java/bartworks/common/loaders/RegisterServerCommands.java
Labels: enhancement

#3637 Allow I/O Hatches to be placed on all Steel Casings in the Industrial Lathe
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiLathe.java
Labels: enhancement

#3641 Fix UUA time multiplier
  src/main/java/gregtech/common/config/MachineStats.java
Labels: bug fix

#3307 remove outdated compat code
  src/main/java/gregtech/api/recipe/RecipeMaps.java
Labels: refactor

#3639 Separate tool crafting sound from getContainerItem
  src/main/java/gregtech/api/items/MetaGeneratedTool.java
  src/main/java/gregtech/common/GTProxy.java
Labels: bug fix

#3203 Remove some GT tools
  src/main/java/detrav/items/processing/ProcessingDetravToolProspector.java
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/enums/OrePrefixes.java
  src/main/java/gregtech/api/enums/TextureSet.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/items/IDMetaTool01.java
  src/main/java/gregtech/common/items/MetaGeneratedItem02.java
  src/main/java/gregtech/common/items/MetaGeneratedTool01.java
  src/main/java/gregtech/common/items/flinttools/FlintAxe.java
  src/main/java/gregtech/common/items/flinttools/FlintHoe.java
  src/main/java/gregtech/common/items/flinttools/FlintPickaxe.java
  src/main/java/gregtech/common/items/flinttools/FlintShovel.java
  src/main/java/gregtech/common/items/flinttools/FlintSword.java
  src/main/java/gregtech/common/items/flinttools/FlintTools.java
  src/main/java/gregtech/common/tools/ToolAxe.java
  src/main/java/gregtech/common/tools/ToolHoe.java
  src/main/java/gregtech/common/tools/ToolKnife.java
  src/main/java/gregtech/common/tools/ToolPickaxe.java
  src/main/java/gregtech/common/tools/ToolPlow.java
  src/main/java/gregtech/common/tools/ToolSense.java
  src/main/java/gregtech/common/tools/ToolShovel.java
  src/main/java/gregtech/common/tools/ToolSword.java
  src/main/java/gregtech/common/tools/ToolUniversalSpade.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingShaping.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingToolHead.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingToolOther.java
  src/main/java/gregtech/loaders/postload/BookAndLootLoader.java
  src/main/java/gregtech/loaders/postload/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/postload/GTPostLoad.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
  src/main/java/gtneioreplugin/GTNEIOrePlugin.java
  src/main/java/gtneioreplugin/plugin/item/ItemDimensionDisplay.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/items/tools/flintAxe.png
  src/main/resources/assets/gregtech/textures/items/tools/flintHoe.png
  src/main/resources/assets/gregtech/textures/items/tools/flintPickaxe.png
  src/main/resources/assets/gregtech/textures/items/tools/flintShovel.png
  src/main/resources/assets/gregtech/textures/items/tools/flintSword.png
Labels: refactor

#3645 Add missing goodgenerator solidifier recipes
  src/main/java/goodgenerator/items/GGMaterial.java
Labels: Affects Balance, new feature

#3644 Deprecate BW low power lasers
  src/main/java/bartworks/common/loaders/ItemRegistry.java
  src/main/java/bartworks/common/loaders/recipes/Assembler.java
  src/main/java/bwcrossmod/tectech/tileentites/tiered/LowPowerLaser.java
  src/main/java/bwcrossmod/tectech/tileentites/tiered/LowPowerLaserBase.java
  src/main/java/bwcrossmod/tectech/tileentites/tiered/MTELowPowerLaserBox.java
  src/main/java/bwcrossmod/tectech/tileentites/tiered/MTELowPowerLaserDynamo.java
  src/main/java/bwcrossmod/tectech/tileentites/tiered/MTELowPowerLaserHatch.java
  src/main/java/bwcrossmod/tectech/tileentites/tiered/MTELowPowerLaserPipe.java
Labels: enhancement

#3520 Migrate GalaxySpace materials to GT5u
  src/main/java/bartworks/system/material/WerkstoffLoader.java
Labels: refactor

#3355 Add Signalium, Lumiium and Enderium ABS recipes
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
Labels: Affects Balance

#3646 fix reservoir hatch crash
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
Labels: bug fix

#3647 Add Research Station to NEI Scanner List
  src/main/java/tectech/thing/metaTileEntity/multi/MTEResearchStation.java
Labels: enhancement

#3642 Refactor Steam Input Bus to extend MTEHatchInputBus
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchSteamBusInput.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MteHatchSteamBusInput.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GTPPMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/MTESteamMultiBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechSteamMultis.java
Labels: enhancement, refactor

#3357 Making Plasma Arc Furnace more useful
  src/main/java/gregtech/api/recipe/RecipeCategories.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/gregtech/common/config/Client.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialArcFurnace.java
  src/main/resources/assets/gregtech/textures/gui/picture/plasma_arc_furnace_recycling.png
Labels: Affects Balance

#3542 Adds Tin Alloy mixer recipe
  src/main/java/gregtech/loaders/postload/recipes/MixerRecipes.java
Labels: Affects Balance

#3648 Fix a few Glass Tooltips
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialElectromagneticSeparator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialExtractor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiLathe.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEHIPCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEIndustrialCompressor.java
Labels: bug fix

#3649 Add some more missing solidifier recipes
  src/main/java/bartworks/system/material/WerkstoffLoader.java
  src/main/java/gtnhlanth/common/register/WerkstoffMaterialPool.java
  src/main/java/gtnhlanth/loader/RecipeLoader.java
Labels: enhancement

#3510 PArt 1 of Wire/cable rebalance, take 2
  src/main/java/goodgenerator/loader/Loaders.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
Labels: Affects Balance

#3408 Make Uncertain Resolver X the default version
  src/main/java/tectech/loader/recipe/Assembler.java
  src/main/java/tectech/loader/thing/MachineLoader.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchUncertainty.java
  src/main/resources/assets/tectech/lang/en_US.lang
  src/main/resources/assets/tectech/lang/zh_CN.lang
Labels: enhancement, Affects Balance

#3538 Revisiting Neutron Accelerators
  src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/MTENeutronAccelerator.java
  src/main/java/goodgenerator/loader/Loaders.java
  src/main/java/goodgenerator/loader/RecipeLoader.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
Labels: enhancement

#3652 fix bug in werkstoff recipe autogen
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/MoltenCellLoader.java
Labels: bug fix

#3653 Reallow dynamo hatches on Data Bank for power pass
  src/main/java/tectech/thing/metaTileEntity/multi/MTEDataBank.java
Labels: bug fix

#3620 Migrate Research Completer to GT5u
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/net/GTPacketNodeInfo.java
  src/main/java/gregtech/api/net/GTPacketTypes.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEResearchCompleter.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
Labels: refactor

#3418 Add a small bonus applied to fuels with large burntime to GT large boilers.
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeBoiler.java
Labels: Affects Balance

#3553 Align multiblock text to left
  src/main/java/bartworks/common/tileentities/multis/MTELESU.java
  src/main/java/bartworks/common/tileentities/multis/MTEWindmill.java
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
  src/main/java/goodgenerator/blocks/tileEntity/MTENeutronActivator.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEYottaFluidTank.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeFusionComputer.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEFusionComputer.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTENanoForge.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEWormholeGenerator.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GTPPMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/storage/GregtechMetaTileEntity_PowerSubStationController.java
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
  src/main/java/kubatech/api/implementations/KubaTechGTMultiBlockBase.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeIndustrialGreenhouse.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEMegaIndustrialApiary.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEBaseModule.java
Labels: bug fix

#3569 Refactoring LES code for better readability
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeEssentiaSmeltery.java
Labels: refactor

#3655 Fix lag probably caused by crib
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
Labels: bug fix

#3656 LES Tricorder Parallel count info
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeEssentiaSmeltery.java
Labels: enhancement

#3657 Change scanner to respect fake recipe item count
  src/main/java/gregtech/common/tileentities/machines/basic/MTEScanner.java
Labels: enhancement, bug fix

#3658 HIP Unit mini rework
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/common/blocks/BlockCasings10.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEHIPCompressor.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/COOLANT_DUCT_CASING.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/HEATING_DUCT_CASING.png
Labels: enhancement

#3659 Reduce Naquadria plasma amount in stellar catalyst
  src/main/java/gregtech/loaders/postload/recipes/MixerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/TranscendentPlasmaMixerRecipes.java
Labels: Affects Balance

#3660 Remove priest tier skip
  src/main/java/gregtech/mixin/Mixin.java
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/VanillaTradingMixin.java
Labels: enhancement, Affects Balance, bug fix

#3661 change: fix symmetry of decontaminant degasser
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitDegasser.java
Labels: bug fix

#3663 Add Oredict Tag to Beamline Masks
  src/main/java/gregtech/api/enums/OrePrefixes.java
  src/main/java/gtnhlanth/common/register/LanthItemList.java
Labels: enhancement

#3664 Move ingot macerating and ingot/dust fluid extracting out of recycling
  src/main/java/gregtech/api/util/GTRecipeRegistrator.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingDust.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingIngot.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingNugget.java
Labels: enhancement

#3666 Set an owner in force load chunk NBT for opis
  src/main/java/gregtech/api/objects/GTChunkManager.java
Labels: chore

#3665 Fix multi ui text position
  src/main/java/bartworks/common/tileentities/multis/MTELESU.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
Labels: bug fix

#3669 Alternate lsc info fix
  src/main/java/gregtech/api/metatileentity/implementations/MTEEnhancedMultiBlockBase.java
  src/main/java/gregtech/api/util/LongData.java
  src/main/java/gregtech/api/util/LongRunningAverage.java
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
  src/test/java/gregtech/api/util/LongRunningAverageTest.java
Labels: bug fix

#3671 Fix Bio Lab recipe voltages that uses transform module
  src/main/java/bartworks/common/tileentities/tiered/MTEBioLab.java
  src/main/java/bartworks/system/material/processingLoaders/AdditionalRecipes.java
Labels: bug fix

#3670 Fix structure of mapiary
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEMegaIndustrialApiary.java
Labels: bug fix

#3672 Fix SLAM structure and Antimatter Multi Tooltips
  src/main/java/goodgenerator/blocks/structures/AntimatterStructures.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
Labels: bug fix

#3675 Fix autobuild of first godforge ring
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
Labels: bug fix

#3673 Prevent fill by hand reservoir/air intake hatch with incorrect fluid
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/METHatchAirIntake.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchReservoir.java
Labels: bug fix

#3680 Fix circuit 9 Heavy Oil
  src/main/java/gregtech/loaders/postload/recipes/DistilleryRecipes.java
Labels: bug fix

#3681 Remove duplicate stone dust recipe
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
Labels: bug fix

#3679 Fix lsc crash at full capacity
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
Labels: bug fix

#3683 Fix fluid shaper glass amount range tooltip
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: bug fix

#3684 Swap Draconic and Wyvern DEFC textures
  src/main/resources/assets/kubatech/textures/blocks/casing/defc_2.png
  src/main/resources/assets/kubatech/textures/blocks/casing/defc_3.png
Labels: enhancement

#3685 Fix the Sound of Saplings from GT++
  src/main/java/gtPlusPlus/xmod/bop/blocks/base/SaplingBase.java
Labels: bug fix

#3686 Add onPlayerDestroyItem event when using a tool on a machine
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
Labels: bug fix

#3682 Add extra null checks for waila outputs data
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: bug fix

#3461 double patterns cribs
  src/main/java/gregtech/api/gui/modularui/GTUITextures.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
  src/main/resources/assets/gregtech/textures/gui/overlay_button/x2.png
Labels: new feature

#3687 fix Space Project NEI GUI
  src/main/java/gregtech/api/recipe/maps/SpaceProjectFrontend.java
Labels: bug fix

#3539 Add Chemical Bath + Thermal Centrifuge mode to IOF
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIntegratedOreFactory.java
Labels: enhancement

#3688 Buff godforge conversion milestone scaling
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: Affects Balance

#3490 Introducing the Klein bottle! An "Infinite" "Volumetric" "Flask"
  src/main/java/gregtech/common/render/FlaskRenderer.java
  src/main/java/gtPlusPlus/core/item/ModItems.java
  src/main/java/gtPlusPlus/core/recipe/RecipesGeneral.java
  src/main/java/gtPlusPlus/core/tileentities/general/TileEntityVolumetricFlaskSetter.java
  src/main/java/gtPlusPlus/nei/NEIGTPPConfig.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/enums/GregtechItemList.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/helpers/VolumetricFlaskHelper.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/render/FlaskRenderer.java
  src/main/resources/assets/gregtech/textures/items/gt.Volumetric_Flask_Infinite.png
  src/main/resources/assets/gregtech/textures/items/gt.Volumetric_Flask_Infinite.window.png
Labels: new feature

#3691 Fix fluid extractor and solidifier overdraw
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeFluidExtractor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: bug fix

#3690 Add steam fill bars to steam machines
  src/main/java/gregtech/api/gui/modularui/GTUITextures.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
  src/main/resources/assets/gregtech/textures/gui/progressbar/steam_fill.png
  src/main/resources/assets/gregtech/textures/gui/progressbar/steam_fill_steel.png
Labels: enhancement

#3689 Add tiered solar generators to gt
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/common/tileentities/generators/MTESolarGenerator.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_SOLAR_PANEL.png
Labels: new feature

#3694 LES UI update
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeEssentiaSmeltery.java
Labels: enhancement

#3695 Add some plasma recipes to Mk4 Fusion
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderGTNH.java
Labels: enhancement

#3693 Refactor Sparge Tower
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/gregtech/api/util/GasSpargingRecipe.java
  src/main/java/gregtech/api/util/GasSpargingRecipeMap.java
  src/main/java/gtPlusPlus/api/recipe/GTPPRecipeMaps.java
  src/main/java/gtPlusPlus/api/recipe/SpargeTowerFrontend.java
  src/main/java/gtPlusPlus/nei/LFTRSpargingNEIHandler.java
  src/main/java/gtPlusPlus/nei/NEIGTPPConfig.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTESpargeTower.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderLFTR.java
  src/main/resources/assets/miscutils/lang/en_US.lang
Labels: refactor

#3697 Widen the Voltage enum in ItemComb
  src/main/java/gregtech/common/items/ItemComb.java
Labels: chore

#3692 Buff PCB Parallel
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPCBFactory.java
Labels: Affects Balance

#3699 THTR
  src/main/java/bartworks/common/tileentities/multis/MTEThoriumHighTempReactor.java
Labels: refactor

#3701 Wireless energy covers
  src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/MTENeutronAccelerator.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/common/covers/CoverEnergyWireless.java
  src/main/java/gregtech/common/items/IDMetaItem01.java
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/383.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/384.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/385.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/386.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/387.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/388.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/389.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/390.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/391.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/392.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/393.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/394.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/395.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/396.png
Labels: enhancement

#3700 Fixes for dyson galaxyspace to intergalactic migration
  src/main/java/tectech/loader/recipe/Godforge.java
  src/main/java/tectech/loader/recipe/ResearchStationAssemblyLine.java
Labels: refactor

#3702 Removed usage of deprecated API in LES
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeEssentiaSmeltery.java
Labels: refactor

#3708 Prospector scanner recipe fix
  src/main/java/detrav/enums/IDDetraveMetaGeneratedTool01.java
  src/main/java/detrav/items/DetravMetaGeneratedTool01.java
  src/main/java/detrav/items/processing/ProcessingDetravToolProspector.java
Labels: bug fix

#3711 re enable Multi Tool
  src/main/java/gregtech/loaders/oreprocessing/ProcessingToolOther.java
Labels: bug fix

#3668 Boldarnator (industrial rock breaker) GPL
  src/main/java/gtPlusPlus/api/recipe/GTPPRecipeMaps.java
  src/main/java/gtPlusPlus/core/handler/CompatHandler.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEIndustrialRockBreaker.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderIndustrialRockBreaker.java
Labels: refactor, bug fix

#3720 Change Strontium Processing Recipe
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
Labels: enhancement

#3714 Restore gem implosion
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/GemLoader.java
  src/main/java/gregtech/loaders/postload/recipes/ImplosionCompressorRecipes.java
Labels: bug fix

#3705 Clean up no longer needed galaxyspace isModLoaded check
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
Labels: refactor

#3719 Change Semifluid generator EBF gating
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
Labels: Affects Balance

#3721 Selenium processing tweak
  src/main/java/gtPlusPlus/api/recipe/GTPPRecipeMaps.java
  src/main/java/gtPlusPlus/core/recipe/RecipesSeleniumProcessing.java
Labels: enhancement

#3717 Gt tools removal
  src/functionalTest/java/kubatech/test/kubatechTestMod.java
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/config/Gregtech.java
  src/main/java/gregtech/common/items/flinttools/FlintAxe.java
  src/main/java/gregtech/common/items/flinttools/FlintHoe.java
  src/main/java/gregtech/common/items/flinttools/FlintPickaxe.java
  src/main/java/gregtech/common/items/flinttools/FlintShovel.java
  src/main/java/gregtech/common/items/flinttools/FlintSword.java
  src/main/java/gregtech/common/items/flinttools/FlintTools.java
  src/main/java/gregtech/loaders/postload/GTPostLoad.java
  src/main/java/gregtech/loaders/preload/GTPreLoad.java
  src/main/java/gregtech/mixin/Mixin.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/items/tools/flintAxe.png
  src/main/resources/assets/gregtech/textures/items/tools/flintHoe.png
  src/main/resources/assets/gregtech/textures/items/tools/flintPickaxe.png
  src/main/resources/assets/gregtech/textures/items/tools/flintShovel.png
  src/main/resources/assets/gregtech/textures/items/tools/flintSword.png
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/ItemToolMaterialMixin.java
Labels: Affects Balance

#3254 Updates Structure checks to add error hinting
  src/main/java/bartworks/common/tileentities/multis/MTEWindmill.java
  src/main/java/bartworks/common/tileentities/multis/mega/MegaMultiBlockBase.java
  src/main/java/bartworks/util/BWUtil.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEFuelRefineFactory.java
  src/main/java/goodgenerator/util/StructureHelper.java
  src/main/java/gregtech/api/util/GTStructureUtility.java
  src/main/java/gregtech/api/util/HatchElementBuilder.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEConcreteBackfillerBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDrillerBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeChemicalReactor.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GTPPMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/MTEChemicalPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/storage/GregtechMetaTileEntity_PowerSubStationController.java
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
  src/main/java/kekztech/common/tileentities/MTETankTFFT.java
Labels: new feature

#3722 Add separate minimum & default tick rates for covers
  src/main/java/gregtech/api/util/CoverBehaviorBase.java
  src/main/java/gregtech/common/covers/CoverInfo.java
  src/main/java/gregtech/common/covers/CoverItemMeter.java
  src/main/java/gregtech/common/covers/CoverLiquidMeter.java
  src/main/java/gregtech/common/covers/redstone/CoverAdvancedWirelessRedstoneBase.java
  src/main/java/gregtech/common/covers/redstone/CoverWirelessDoesWorkDetector.java
Labels: enhancement

#3710 Disable wirecutter interaction on EOH when it's working
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEyeOfHarmony.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: bug fix

#3222 Matter manipulator compat
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/enums/OrePrefixes.java
  src/main/java/gregtech/api/interfaces/tileentity/ICoverable.java
  src/main/java/gregtech/api/interfaces/tileentity/IRedstoneEmitter.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gtPlusPlus/core/tileentities/base/TileEntityBase.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/Parameters.java
Labels: refactor

#3723 Fix goodgen controller textures missing
  src/main/java/goodgenerator/loader/Loaders.java
  src/main/java/kekztech/common/blocks/BlockTFFTStorageField.java
Labels: bug fix

#3725 Move MTE IDs around
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
Labels: bug fix

#3726 Fix crash on serializing space teams
  src/main/java/gregtech/common/misc/spaceprojects/SpaceProjectWorldSavedData.java
Labels: bug fix

#3727 Symetrize mapiary bottom
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEMegaIndustrialApiary.java
Labels: bug fix

#3729 Add Hafnium Output to QFT
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderChemicalSkips.java
Labels: Affects Balance

#3730 Fix PrAss not working with stocking bus notifications
  src/main/java/goodgenerator/blocks/tileEntity/MTEPreciseAssembler.java
Labels: bug fix

#3731 remove unnecessary recipes
  src/main/java/gregtech/loaders/postload/recipes/ChemicalRecipes.java
Labels: enhancement

#3734 fix hazmat-protection tooltip hard code to help localize
  src/main/java/gregtech/common/GTProxy.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/lang/zh_CN.lang
Labels: enhancement

#3735 Add Localizations
  src/main/resources/assets/bartworks/lang/en_US.lang
  src/main/resources/assets/goodgenerator/lang/en_US.lang
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gtnhlanth/lang/en_US.lang
  src/main/resources/assets/kekztech/lang/en_US.lang
  src/main/resources/assets/kubatech/lang/en_US.lang
  src/main/resources/assets/miscutils/lang/en_US.lang
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: bug fix

#3736 Fix plasma arc recipes
  src/main/java/gregtech/api/util/GTRecipeConstants.java
Labels: bug fix
