Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2024-11, with the labels that each got.

#3440 fix tengam oregen
  src/main/java/gregtech/api/enums/OreMixes.java
Labels: bug fix

#3434 Fixes for Deep Earth Heating Pump
  src/main/java/bartworks/common/loaders/ItemRegistry.java
  src/main/java/bartworks/common/tileentities/multis/MTEDeepEarthHeatingPump.java
  src/main/java/gregtech/api/gui/modularui/GTUITextures.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDrillerBase.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/gui/overlay_button/machine_mode_dehp_steam.png
Labels: enhancement

#3441 Fix EIG Fertilizer Multiplier
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeIndustrialGreenhouse.java
Labels: bug fix

#3444 Give blackhole a bounding box
  src/main/java/gregtech/common/tileentities/render/TileEntityBlackhole.java
Labels: bug fix

#3447 Reduce Bounding Box allocations
  src/main/java/goodgenerator/blocks/tileEntity/render/TileAntimatter.java
  src/main/java/gregtech/common/tileentities/render/TileEntityBlackhole.java
  src/main/java/tectech/thing/block/TileEntityEyeOfHarmony.java
Labels: refactor

#3445 Fix wrap recipes
  src/main/java/goodgenerator/loader/ComponentAssemblyLineMiscRecipes.java
Labels: bug fix

#3449 Change Cooling Tower Structure
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitPlasmaHeater.java
Labels: bug fix

#3448 Add tinted industrial glass to the structure glasses.
  src/main/java/bartworks/common/loaders/RegisterGlassTiers.java
  src/main/java/gregtech/api/multitileentity/multiblock/casing/Glasses.java
Labels: bug fix

#3446 Fix structure checks and tooltip issues
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiAutoclave.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEHIPCompressor.java
Labels: bug fix

#3416 Add an overflow fix that was missing from #3332.
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeBoiler.java
Labels: bug fix

#3399 Fix DTPF convergence catalyst consumption for non-catalyst recipes
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPlasmaForge.java
Labels: bug fix

#3451 fixed crash in kubatech if witchery is not loaded
  src/main/java/kubatech/loaders/DEFCRecipes.java
Labels: bug fix

#3427 LSC information enhancements
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
Labels: new feature

#3424 Fix wrong shutdown duration of tectech multi & cleanup
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeFusionComputer.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEEnhancedMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEFusionComputer.java
  src/main/java/gtnhlanth/common/tileentity/MTEDissolutionTank.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
Labels: bug fix

#3428 adjusted status window widget creation to allow for horizontal scrolling
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
Labels: bug fix

#3455 Fix baryonic perfection voiding one catalyst when recipe fails
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBaryonicPerfection.java
Labels: bug fix

#3456 Change thorium comb to have mv processing
  src/main/java/gregtech/common/items/ItemComb.java
Labels: Affects Balance

#3458 Remove fast mode mention from XL Steam Turbines
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
Labels: bug fix

#3429 Fix shirabon cost in alternative naqfuel mk6 recipe
  src/main/java/goodgenerator/loader/FuelRecipeLoader.java
Labels: bug fix

#3457 Fix EHE NEI special info
  src/main/java/goodgenerator/api/recipe/ExtremeHeatExchangerFrontend.java
Labels: bug fix

#3459 Fix HILE waila info
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
Labels: bug fix

#3454 Add Tool Casting support to the Fluid Shaper multiblock.
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchSolidifier.java
Labels: enhancement

#3439 Another round of later naqfuel buffs
  src/main/java/goodgenerator/blocks/tileEntity/MTEFuelRefineFactory.java
  src/main/java/goodgenerator/loader/FuelRecipeLoader.java
  src/main/java/goodgenerator/loader/NeutronActivatorLoader.java
Labels: Affects Balance

#3443 Fix HILE render turning off while running when pressing power button
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
Labels: bug fix

#3460 Remove waterline QFT skip
  src/main/java/gtPlusPlus/core/item/chemistry/GenericChem.java
  src/main/java/gtPlusPlus/core/util/minecraft/ItemUtils.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderChemicalSkips.java
Labels: enhancement

#3463 Fix gold vein name
  src/main/java/gregtech/api/enums/OreMixes.java
Labels: bug fix

#3464 Delete the "PlayerActivity.log"
  src/main/java/gregtech/api/util/GTLog.java
  src/main/java/gregtech/common/GTPlayerActivityLogger.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/config/Gregtech.java
  src/main/java/gregtech/loaders/preload/GTPreLoad.java
Labels: chore

#3435 Turbine Texture Refactor
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/common/blocks/BlockCasings4.java
  src/main/java/gregtech/common/blocks/BlockCasings8.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbineSteam.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/GregtechMetaSpecialMultiCasings.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargeTurbineSteam.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_TURBINE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_TURBINE_HSSS.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_TURBINE_STEEL.png
Labels: refactor

#3466 Readd missing iodine output to seaweed ash line
  src/main/java/gtnhlanth/loader/RecipeLoader.java
Labels: bug fix

#3462 Fix a few waterline nei previews
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitPlasmaHeater.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitUVTreatment.java
Labels: bug fix

#3431 Add ctrl-middle-click to suppress infinite spray can's left click shake
  src/main/java/gregtech/api/net/GTPacketInfiniteSpraycan.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColorInfinite.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#3470 Blackhole fixes
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
Labels: bug fix

#3472 Add Very Heavy Oil Cell to Materials list
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
Labels: enhancement

#3478 Adjust number formatting in WAILA machine progress line
  src/main/java/gregtech/api/util/GTWaila.java
Labels: enhancement

#3480 Fix Solidifier Autoplace and Add Glass Subchannel
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: enhancement, bug fix

#3479 Small solidifier structure check fix
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: bug fix

#3481 Fix to Vanadium Redox Power Cell Recipe
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
Labels: bug fix

#3476 Delete NBT data about crafting components on MetaTileEntity
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
Labels: refactor

#3473 Save custom name on particular case
  src/main/java/gregtech/common/tileentities/machines/multi/drone/MTEDroneCentre.java
Labels: bug fix

#3483 Improve EoH tier numbering in portable scanner info
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEyeOfHarmony.java
Labels: enhancement, bug fix

#3468 rebalance of plasma chain recipes
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderNuclear.java
Labels: Affects Balance

#3477 Add configurable EOH Energy Display
  src/main/java/tectech/loader/ConfigHandler.java
  src/main/java/tectech/proxy/CommonProxy.java
  src/main/java/tectech/recipe/EyeOfHarmonyFrontend.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement

#3486 Add nbt safeguard for dtpf convergence catalyst type
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPlasmaForge.java
Labels: bug fix

#3488 Fix Volumetric Flasks Render
  src/main/java/gregtech/common/render/FlaskRenderer.java
Labels: bug fix

#3438 Adds a blacklist to prevent certain dims like Twilight Forest from generating overworld ores
  src/main/java/gregtech/api/world/GTWorldgen.java
  src/main/java/gregtech/common/WorldgenGTOreLayer.java
  src/main/java/gregtech/common/WorldgenGTOreSmallPieces.java
Labels: bug fix

#3482 added recipe using rutile, scheelite and ilmenite for qft Tita-Tungsten-Catalyst
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderChemicalSkips.java
Labels: Affects Balance

#3491 Add explicit mention of exotic energy hatches
  src/main/java/bartworks/common/tileentities/multis/MTEElectricImplosionCompressor.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaBlastFurnace.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaChemicalReactor.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaDistillTower.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaOilCracker.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaVacuumFreezer.java
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEComponentAssemblyLine.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEFuelRefineFactory.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeEssentiaSmeltery.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer1.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer2.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer3.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer4.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer5.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEMultiNqGenerator.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEPreciseAssembler.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEUniversalChemicalFuelEngine.java
  src/main/java/gregtech/api/enums/GTValues.java
  src/main/java/gregtech/api/util/MultiblockTooltipBuilder.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTENanoForge.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPCBFactory.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEWormholeGenerator.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTELargeRocketEngine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEQuantumForceTransformer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/mega/MTEMegaAlloyBlastSmelter.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEActiveTransformer.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEDataBank.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEnergyInfuser.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTENetworkSwitch.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEQuantumComputer.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEResearchStation.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTETeslaTower.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#3493 Prevent screwdriver from changing pipe collision boxes
  src/main/java/gregtech/common/GTClient.java
Labels: enhancement

#3492 Add tooltips to fluid/item pipe casings
  src/main/java/gregtech/common/blocks/ItemCasings11.java
  src/main/java/gregtech/common/blocks/ItemCasings2.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#3497 Delete GT++ Super chests
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gtPlusPlus/core/handler/CompatHandler.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/enums/GregtechItemList.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/storage/MTETieredChest.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechSuperChests.java
Labels: refactor

#3498 Simplify GT Assembler recipes for Muffler Upgrades
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
Labels: enhancement

#3500 Fix pitchblende height range
  src/main/java/gregtech/api/enums/OreMixes.java
Labels: bug fix

#3499 Added mode swap button to Utupu Tanuri
  dependencies.gradle
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialDehydrator.java
Labels: new feature

#3501 Added Pipe Casing Recipes to Assembler
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
Labels: enhancement

#3503 Reduce packets sent for shutdown duration UI
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: chore

#3502 Add Ore Berries to Fluid Extraction Recipes
  src/main/java/gregtech/loaders/postload/recipes/FluidExtractorRecipes.java
Labels: enhancement

#3378 Prevent -generation when long overflow for antimatter gen.
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
Labels: bug fix

#3507 Restore hydration cell recipe
  src/main/java/gregtech/loaders/postload/recipes/ExtractorRecipes.java
Labels: bug fix

#3506 Add throughput to Wireless Energy Hatch tooltip
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchWirelessMulti.java
Labels: enhancement

#3494 Improve EHE info and buff lava in EHE
  src/main/java/goodgenerator/api/recipe/ExtremeHeatExchangerFrontend.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEExtremeHeatExchanger.java
  src/main/java/goodgenerator/loader/RecipeLoader2.java
  src/main/resources/assets/goodgenerator/lang/en_US.lang
  src/main/resources/assets/goodgenerator/lang/zh_CN.lang
Labels: Affects Balance, bug fix

#3432 Fix (another) Computation Bug
  src/main/java/tectech/thing/metaTileEntity/multi/MTENetworkSwitch.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEQuantumComputer.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: bug fix

#3495 Remove the GT++ programmed circuit from certain chem plant recipes
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
Labels: enhancement

#3496 Add Raw Ores to Isamill recipes
  src/main/java/gtPlusPlus/core/item/base/ore/BaseItemMilledOre.java
Labels: enhancement

#3487 update the BlockPosHighlighter call to AE2 in MTEDroneCentre
  dependencies.gradle
  src/main/java/gregtech/common/tileentities/machines/multi/drone/MTEDroneCentre.java
Labels: chore

#3511 9x crop leaf extraction
  src/main/java/gregtech/common/items/MetaGeneratedItem02.java
Labels: bug fix

#3512 move away from classicHatches() hatch adder
  src/main/java/tectech/thing/metaTileEntity/multi/MTEDataBank.java
Labels: bug fix

#3516 PA Recipe Removal
  src/main/java/gregtech/common/tileentities/machines/multi/MTEProcessingArray.java
  src/main/java/gregtech/loaders/load/MTERecipeLoader.java
Labels: Affects Balance

#3513 reinit of assline datasticks on id remap
  src/main/java/gregtech/api/util/GTRecipe.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/tectech/recipe/TTRecipeAdder.java
Labels: bug fix

#3467 Added Waila info for ME output hatches/busses
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
  src/main/java/gregtech/crossmod/waila/GregtechWailaDataProvider.java
Labels: enhancement

#3505 Follow up fixes for multiple muffler hatches.
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaBlastFurnace.java
  src/main/java/bartworks/common/tileentities/multis/mega/MegaMultiBlockBase.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeTurbineBase.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEExtendedPowerMultiBlockBase.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchMuffler.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDieselEngine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEElectricBlastFurnace.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEExtremeDieselEngine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiFurnace.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPCBFactory.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchMufflerAdvanced.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GTPPMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
Labels: refactor, bug fix

#3526 Attempt to add bulk recipe w/ alumina for celuag
  src/main/java/gtnhlanth/common/register/WerkstoffMaterialPool.java
  src/main/java/gtnhlanth/loader/RecipeLoader.java
Labels: bug fix

#3517 Fix some incorrect parallel calculation
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAssemblyLine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIntegratedOreFactory.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiFurnace.java
Labels: bug fix

#3534 Fix multiblocks displaying output x 0
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: bug fix

#3528 Black hole fixes/changes
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
Labels: enhancement, bug fix

#3529 Add name of glass tiers to Bacterial Vat NEI page
  src/main/java/bartworks/API/recipe/BacterialVatFrontend.java
  src/main/java/bartworks/common/loaders/BioRecipeLoader.java
  src/main/java/bartworks/system/material/processingLoaders/AdditionalRecipes.java
  src/main/java/gregtech/api/recipe/RecipeMaps.java
Labels: enhancement

#3533 Fix maintenance hatch right-click behavior from the wrong side.
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchMaintenance.java
Labels: bug fix

#3537 Deprecate the Advanced Large Gas turbine
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbineGas.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbineGasAdvanced.java
  src/main/java/gregtech/loaders/load/MTERecipeLoader.java
Labels: Affects Balance

#3522 Fix NEI preview for Implosion Compressor and Density^2
  src/main/java/gregtech/common/tileentities/machines/multi/MTEImplosionCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvImplosionCompressor.java
Labels: bug fix

#3530 fix turbine overlay not being shown in NEI preview
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
Labels: bug fix

#3532 Fix SOFC Mk2 fuel efficiency
  src/main/java/kekztech/common/tileentities/MTESOFuelCellMK2.java
Labels: enhancement, bug fix

#3521 Use ofBlocksTiered for steam water pump structure
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWaterPump.java
Labels: refactor

#3508 Reworked Fluid Shaper Parallels, Tooltip Cleanup, Structure Change
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: Affects Balance

#3545 Prevent LHE from consuming cold coolant
  src/main/java/gregtech/api/registries/LHECoolantRegistry.java
Labels: bug fix

#3543 Fix non-elemental plasma cells
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/api/enums/MaterialsUEVplus.java
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
Labels: bug fix

#3540 Fixed Antimatter Forge Tricoder info
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
Labels: bug fix

#3536 make the cover tooltips respect the advancedItemTooltips setting
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
Labels: bug fix

#3524 Remove empty Auto-generated BW Centrifuge, Electrolyzer, etc. recipes
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/CellLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/DustLoader.java
Labels: bug fix

#3519 Add dyson swarm controller MTE ID
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
Labels: chore

#3544 Add blockrenderer as a runtime dep
  dependencies.gradle
Labels: chore

#3504 Beamline fixes 4
  src/main/java/gtnhlanth/common/beamline/BeamLinePacket.java
  src/main/java/gtnhlanth/common/item/ItemPhotolithographicMask.java
  src/main/java/gtnhlanth/common/item/MaskList.java
  src/main/java/gtnhlanth/common/register/LanthItemList.java
  src/main/java/gtnhlanth/common/register/WerkstoffMaterialPool.java
  src/main/java/gtnhlanth/common/tileentity/MTELINAC.java
  src/main/java/gtnhlanth/common/tileentity/MTESourceChamber.java
  src/main/java/gtnhlanth/common/tileentity/MTESynchrotron.java
  src/main/java/gtnhlanth/common/tileentity/MTETargetChamber.java
  src/main/java/gtnhlanth/common/tileentity/recipe/beamline/BeamlineRecipeLoader.java
  src/main/java/gtnhlanth/loader/RecipeLoader.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_SHIELDED_ACCELERATOR.png
  src/main/resources/assets/gtnhlanth/lang/en_US.lang
  src/main/resources/assets/gtnhlanth/textures/blocks/casing.antenna_t1.png
  src/main/resources/assets/gtnhlanth/textures/blocks/casing.antenna_t2.png
  src/main/resources/assets/gtnhlanth/textures/blocks/casing.coolant_delivery.png
  src/main/resources/assets/gtnhlanth/textures/blocks/casing.electrode.png
  src/main/resources/assets/gtnhlanth/textures/blocks/casing.electrode.png.mcmeta
  src/main/resources/assets/gtnhlanth/textures/blocks/casing.focus_manipulator.png
  src/main/resources/assets/gtnhlanth/textures/blocks/casing.shielded_accelerator.png
  src/main/resources/assets/gtnhlanth/textures/blocks/casing.shielded_accelerator_glass.png
  src/main/resources/assets/gtnhlanth/textures/blocks/casing.target_receptacle.png
  src/main/resources/assets/gtnhlanth/textures/items/etched_mask1.png
  src/main/resources/assets/gtnhlanth/textures/items/iron_quartz_plate.png
  src/main/resources/assets/gtnhlanth/textures/items/mask_substrate.png
  src/main/resources/assets/gtnhlanth/textures/items/masked_mask_substrate.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/acc.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/asoc.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/blank1.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/blank2.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/blank3.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/cblank.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/ccpu.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/ccpu2.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/cpu.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/csoc.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/hpic.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/ilc.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/lcc.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/lpic.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/nand.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/ncpu.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/nor.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/npic.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/pic.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/ppic.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/prcpu.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/prhpic.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/prncpu.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/prnpic.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/prpic.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/qbit.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/qpic.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/ram.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/soc.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/ssoc.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/uhpic.png
  src/main/resources/assets/gtnhlanth/textures/items/photomask/ulpic.png
  src/main/resources/assets/gtnhlanth/textures/items/substrate_precursor.png
Labels: enhancement, Affects Balance, bug fix

#3547 Fix crash in Fishing Port when no recipe is found
  src/main/java/gtPlusPlus/core/util/data/ArrayUtils.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEIndustrialFishingPond.java
Labels: bug fix

#3548 Renaming "Assembling Line" to "Assembly Line"
  src/main/java/bartworks/common/tileentities/multis/MTECircuitAssemblyLine.java
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/gregtech/common/blocks/BlockCasings2.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAssemblyLine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTENanoForge.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement

#3549 fix treetwister effect crash
  src/main/java/gregtech/loaders/misc/bees/GTAlleleEffect.java
Labels: bug fix

#3552 Clarify scanner readout on T7 water multi
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitDegasser.java
Labels: enhancement

#3554 readd missing condition
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
Labels: bug fix

#3556 fix mar-ce recycling and make the logic cleaner
  src/main/java/gtnhlanth/loader/RecipeLoader.java
Labels: bug fix

#3557 Bring Item Holders' descriptions in line with other covers.
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
Labels: enhancement

#3558 Waterline fixes
  src/main/java/gregtech/api/enums/SoundResource.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBase.java
Labels: bug fix

#3562 Fix crash when configuring ender tank covers
  src/main/java/tectech/thing/cover/CoverEnderFluidLink.java
Labels: bug fix

#3564 Fixed Wrong Antimatter Tooltip
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
Labels: bug fix

#3396 Godforge hangover
  src/main/java/gregtech/api/gui/modularui/GTUITextures.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/tectech/loader/recipe/BaseRecipeLoader.java
  src/main/java/tectech/loader/recipe/Godforge.java
  src/main/java/tectech/recipe/GodforgeUpgradeCostFrontend.java
  src/main/java/tectech/recipe/TecTechRecipeMaps.java
  src/main/java/tectech/thing/block/RenderForgeOfGods.java
  src/main/java/tectech/thing/block/TileEntityForgeOfGods.java
  src/main/java/tectech/thing/gui/TecTechUITextures.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEBaseModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEExoticModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEMoltenModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEPlasmaModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTESmeltingModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/color/ForgeOfGodsStarColor.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/structure/ForgeOfGodsRingsStructureString.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/structure/ForgeOfGodsStructureString.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/upgrade/ForgeOfGodsUpgrade.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/upgrade/UpgradeStorage.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/util/ForgeOfGodsUI.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/util/GodforgeMath.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/util/MilestoneFormatter.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/util/MilestoneIcon.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/util/UpgradeColor.java
  src/main/resources/assets/gregtech/textures/gui/picture/arrow_gray.png
  src/main/resources/assets/tectech/lang/en_US.lang
  src/main/resources/assets/tectech/textures/gui/overlay_button/statistics.png
  src/main/resources/assets/tectech/textures/gui/picture/green_checkmark.png
  src/main/resources/assets/tectech/textures/gui/picture/rainbow_square.png
Labels: bug fix

#3559 Add info in the tooltip of the chemplant
  src/main/java/bartworks/common/tileentities/multis/MTEDeepEarthHeatingPump.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/MTEChemicalPlant.java
Labels: enhancement

#3567 Restore missing wire recipes
  src/main/java/goodgenerator/util/CrackRecipeAdder.java
Labels: bug fix

#3561 Fix fluid amount not updated in multiblock ui
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: bug fix

#3570 remove maintenance hatch from TPM NEI preview
  src/main/java/gregtech/common/tileentities/machines/multi/MTETranscendentPlasmaMixer.java
Labels: bug fix

#3573 Fixing laser pipe connection issues when you place a pipe next to another one
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeData.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeEnergy.java
Labels: bug fix

#3575 prevent client side code being called server side
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
Labels: bug fix

#3576 fix many broken and incorrect recycling recipes and fixes several infinite material loops
  src/main/java/bartworks/system/material/WerkstoffLoader.java
Labels: bug fix

#3577 Fix turbines resetting to tight mode after server restart
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbineHPSteam.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbineSteam.java
Labels: bug fix

#3579 Fix water overwriting other fluids in laser engraver
  src/main/java/gregtech/api/util/GTRecipeConstants.java
Labels: bug fix

#3580 Fix Living Crystal Chip progression skip using Beamline
  src/main/java/gtnhlanth/loader/RecipeLoader.java
Labels: Affects Balance

#3568 Fix Godforge NDPE upgrade description
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: bug fix

#3578 Frame fix (NEEDS TESTING)
  src/main/java/gregtech/api/interfaces/ITemporaryTE.java
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEFrame.java
  src/main/java/gregtech/api/net/GTPacketCreateTE.java
  src/main/java/gregtech/api/net/GTPacketTileEntity.java
  src/main/java/gregtech/api/net/GTPacketTypes.java
  src/main/java/gregtech/common/blocks/BlockFrameBox.java
Labels: bug fix
