Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2025-04, with the labels that each got.

#4125 Fix Cleanroom NPE
  src/main/java/gregtech/common/tileentities/machines/multi/MTECleanroom.java
Labels: bug fix

#4127 Fix Synchrotron NPE
  src/main/java/gtnhlanth/common/tileentity/MTESynchrotron.java
Labels: bug fix, :construction: Testing on Zeta

#4130 Fix ActiveGTMachineMutationCondition
  src/main/java/gregtech/loaders/misc/GTBees.java
Labels: bug fix

#4103 Add a config option to invert scrolling direction for Ghost Circuits
  src/main/java/gregtech/api/metatileentity/BaseTileEntity.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/config/Client.java
  src/main/java/gregtech/loaders/preload/GTPreLoad.java
Labels: enhancement

#4096 Better Dynamic Heating Coil Textures
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_AWAKENEDDRACONIUM_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_AWAKENEDDRACONIUM_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_CUPRONICKEL_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_CUPRONICKEL_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_ELECTRUMFLUX_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_ELECTRUMFLUX_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_ETERNAL_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_ETERNAL_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_HSSG_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_HSSG_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_HSSS_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_HSSS_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_HYPOGEN_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_HYPOGEN_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_INFINITY.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_INFINITY_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_INFINITY_BACKGROUND.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_INFINITY_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_INFINITY_FOREGROUND.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_KANTHAL_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_KANTHAL_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_NAQUADAHALLOY_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_NAQUADAHALLOY_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_NAQUADAH_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_NAQUADAH_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_NICHROME_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_NICHROME_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_TRINIUM_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_TRINIUM_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_TUNGSTENSTEEL_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_TUNGSTENSTEEL_FOREGROUND.png
Labels: enhancement

#4098 Comet helium ions
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
Labels: enhancement

#4131 Fix spelling of "Appliances" in GT++
  src/main/resources/assets/miscutils/lang/en_US.lang
Labels: bug fix

#4132 Fix PrAss NPE
  src/main/java/goodgenerator/blocks/tileEntity/MTEPreciseAssembler.java
Labels: bug fix

#4133 Beamline Refactor/Cleanup
  src/main/java/gtnhlanth/common/hatch/MTEHatchBeamlineConnector.java
  src/main/java/gtnhlanth/common/hatch/MTEHatchInputBeamline.java
  src/main/java/gtnhlanth/common/hatch/MTEHatchOutputBeamline.java
  src/main/java/gtnhlanth/common/tileentity/MTELINAC.java
  src/main/java/gtnhlanth/common/tileentity/MTESourceChamber.java
  src/main/java/gtnhlanth/common/tileentity/MTESynchrotron.java
  src/main/java/gtnhlanth/common/tileentity/MTETargetChamber.java
  src/main/java/gtnhlanth/util/DescTextLocalization.java
Labels: enhancement

#4135 Fix t1 water not forming with distilled or cofhcore water
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitClarifier.java
Labels: bug fix

#4138 Mitigate merge conflicts
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gtnhlanth/common/tileentity/MTELINAC.java
  src/main/java/gtnhlanth/common/tileentity/MTESourceChamber.java
  src/main/java/gtnhlanth/common/tileentity/MTESynchrotron.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: chore

#4140 Remove abandoned item Behavior classes
  src/main/java/gregtech/common/items/behaviors/BehaviourHoe.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSense.java
Labels: refactor, :construction: Testing on Zeta

#4068 Structure wrapper system
  src/main/java/gregtech/api/casing/Casings.java
  src/main/java/gregtech/api/casing/ICasing.java
  src/main/java/gregtech/api/casing/ICasingGroup.java
  src/main/java/gregtech/api/enums/GTValues.java
  src/main/java/gregtech/api/enums/HatchElement.java
  src/main/java/gregtech/api/enums/StructureError.java
  src/main/java/gregtech/api/interfaces/IHatchElement.java
  src/main/java/gregtech/api/structure/CasingInfo.java
  src/main/java/gregtech/api/structure/IStructureInstance.java
  src/main/java/gregtech/api/structure/IStructureProvider.java
  src/main/java/gregtech/api/structure/StructureWrapper.java
  src/main/java/gregtech/api/structure/StructureWrapperInstanceInfo.java
  src/main/java/gregtech/api/structure/StructureWrapperTooltipBuilder.java
  src/main/java/gregtech/api/util/GTDataUtils.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/MultiblockTooltipBuilder.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
Labels: refactor, :construction: Testing on Zeta

#4056 Support Custom Glyphs via Private Use Area Unicode + New Element Symbols
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/api/util/CustomGlyphs.java
  src/main/java/gtPlusPlus/core/material/MaterialsAlloy.java
  src/main/resources/assets/minecraft/font/glyph_sizes.bin
  src/main/resources/assets/minecraft/textures/font/unicode_page_e0.png
Labels: new feature, :construction: Testing on Zeta

#4149 Fix NPE in getWailaNBTData
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
Labels: bug fix

#4144 Add methods to register GT++ catalysts and milling balls
  src/main/java/gtPlusPlus/core/util/minecraft/ItemUtils.java
Labels: new feature

#4145 Text de-hardcoding
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchMaintenance.java
  src/main/java/gregtech/api/util/MultiblockTooltipBuilder.java
  src/main/java/gregtech/common/items/ItemIntegratedCircuit.java
  src/main/java/gtPlusPlus/plugin/agrichem/item/algae/ItemAlgaeBase.java
  src/main/java/tectech/thing/casing/ItemCasingsGodforge.java
  src/main/java/tectech/thing/casing/ItemCasingsSpacetime.java
  src/main/java/tectech/thing/casing/ItemCasingsStabilisation.java
  src/main/java/tectech/thing/casing/ItemCasingsTimeAcceleration.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement

#4150 Waila change for multiblock locked recipe
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: bug fix

#4134 Allow DualInputInventory fallback to non-cached processing procedure
  src/main/java/gregtech/api/logic/ProcessingLogic.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/IDualInputHatch.java
  src/main/java/gregtech/common/tileentities/machines/IDualInputInventory.java
Labels: enhancement

#4136 Chanced outputs amount consistency
  src/functionalTest/java/gregtech/test/GTParallelHelperTest.java
  src/main/java/gregtech/api/util/ParallelHelper.java
  src/main/java/gregtech/api/util/VoidProtectionHelper.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEQuantumForceTransformer.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEyeOfHarmony.java
Labels: bug fix

#4142 Move all the Armors' Hazmat features to Interface implementations
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/hazards/HazardProtection.java
  src/main/java/gregtech/api/hazards/HazardProtectionTooltip.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/mixin/Mixin.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/accessors/ItemArmorMixin.java
  src/mixin/java/gregtech/mixin/mixins/late/advanced_solar_panels/MixinAdvancedSolarHelmet.java
  src/mixin/java/gregtech/mixin/mixins/late/ic2/MixinIc2Hazmat.java
  src/mixin/java/gregtech/mixin/mixins/late/ic2/MixinIc2Nano.java
  src/mixin/java/gregtech/mixin/mixins/late/ic2/MixinIc2Quantum.java
Labels: refactor

#4152 Add cell for Raw Radox
  src/main/java/gregtech/common/items/MetaGeneratedItem98.java
Labels: enhancement

#4153 Remove dead file
  src/main/java/gregtech/common/items/ID_MetaItem_03.java
Labels: refactor

#4158 Advanced Assembly Line Improvements
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEFuelRefineFactory.java
  src/main/java/gregtech/api/objects/overclockdescriber/FusionOverclockDescriber.java
  src/main/java/gregtech/api/recipe/check/CheckRecipeResultRegistry.java
  src/main/java/gregtech/api/recipe/check/ResultInsufficientVoltage.java
  src/main/java/gregtech/api/util/MultiblockTooltipBuilder.java
  src/main/java/gregtech/api/util/OverclockCalculator.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEMassfabricator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement, :construction: Testing on Zeta

#4165 Don't initialize covers as null
  src/main/java/gregtech/api/covers/CoverRegistry.java
  src/main/java/gregtech/api/interfaces/tileentity/ICoverable.java
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
Labels: refactor

#4162 buff railcraft bending recipes down to LV/MV
  src/main/java/gregtech/loaders/postload/recipes/BenderRecipes.java
Labels: Affects Balance

#4163 Smoothen overclocks for fractional ticks
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/gregtech/api/util/OverclockCalculator.java
  src/main/java/gregtech/api/util/ParallelHelper.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAssemblyLine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIntegratedOreFactory.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiFurnace.java
  src/test/java/gregtech/overclock/GT_OverclockCalculator_UnitTest.java
Labels: enhancement, Affects Balance, bug fix

#4141 fix and add QoL to infinite tank from gt++
  src/main/java/gtPlusPlus/core/block/general/BlockFluidTankInfinite.java
  src/main/java/gtPlusPlus/core/tileentities/general/TileEntityInfiniteFluid.java
Labels: enhancement, bug fix, :construction: Testing on Zeta

#4169 Change superstable seed texture
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/420.png
Labels: enhancement, :construction: Testing on Zeta

#4168 Fix ME Hatch Output Filtering
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
Labels: bug fix, :construction: Testing on Zeta

#4159 Clean up some TTMultiblockBase fields
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEnergyInfuser.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
Labels: refactor, bug fix, :construction: Testing on Zeta

#4161 Fix Buck Converter UI client desync
  src/main/java/tectech/thing/metaTileEntity/single/MTEBuckConverter.java
Labels: bug fix, :construction: Testing on Zeta

#4182 Add IronTankMinecarts to mod enums
  src/main/java/gregtech/api/enums/Mods.java
Labels: new feature

#4118 fix fusion casing CTM issue when using angelica
  src/main/java/gregtech/api/util/GTRenderingWorld.java
  src/main/java/gregtech/common/covers/CoverFacadeBase.java
Labels: bug fix, :construction: Testing on Zeta

#4187 Add extruder recipe for pasta
  src/main/java/gregtech/loaders/postload/recipes/ExtruderRecipes.java
Labels: enhancement, :construction: Testing on Zeta

#4025 Add the Redstone Sniffer
  src/main/java/bartworks/common/loaders/recipes/CraftingRecipes.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/net/GTPacketTypes.java
  src/main/java/gregtech/api/net/PacketDebugRedstoneCover.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/covers/CoverPosition.java
  src/main/java/gregtech/common/covers/CoverRedstoneTransmitterExternal.java
  src/main/java/gregtech/common/covers/CoverRedstoneTransmitterInternal.java
  src/main/java/gregtech/common/covers/CoverRedstoneWirelessBase.java
  src/main/java/gregtech/common/covers/redstone/CoverAdvancedRedstoneTransmitterBase.java
  src/main/java/gregtech/common/covers/redstone/CoverAdvancedRedstoneTransmitterExternal.java
  src/main/java/gregtech/common/covers/redstone/CoverAdvancedRedstoneTransmitterInternal.java
  src/main/java/gregtech/common/covers/redstone/CoverAdvancedWirelessRedstoneBase.java
  src/main/java/gregtech/common/covers/redstone/CoverWirelessDoesWorkDetector.java
  src/main/java/gregtech/common/covers/redstone/CoverWirelessFluidDetector.java
  src/main/java/gregtech/common/covers/redstone/CoverWirelessItemDetector.java
  src/main/java/gregtech/common/covers/redstone/CoverWirelessMaintenanceDetector.java
  src/main/java/gregtech/common/gui/modularui/uifactory/RedstoneSnifferGuiBuilder.java
  src/main/java/gregtech/common/gui/mui1/cover/AdvancedWirelessRedstoneBaseUIFactory.java
  src/main/java/gregtech/common/items/ItemRedstoneSniffer.java
  src/main/java/gregtech/common/items/MetaGeneratedItem02.java
  src/main/java/gregtech/common/misc/spaceprojects/SpaceProjectManager.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/gui/overlay_button/redstoneSnifferLocate.png
  src/main/resources/assets/gregtech/textures/gui/overlay_button/redstoneSnifferTeleport.png
  src/main/resources/assets/gregtech/textures/items/gt.Item_Redstone_Sniffer.png
Labels: new feature, :construction: Testing on Zeta

#4179 Remove GT plankWood recipes in ore recipe generator
  src/main/java/gregtech/loaders/oreprocessing/ProcessingPlank.java
Labels: bug fix, :construction: Testing on Zeta

#4172 Expose vanilla TE data packet system to MTEs
  src/main/java/gregtech/api/interfaces/metatileentity/IMetaTileEntity.java
  src/main/java/gregtech/api/interfaces/tileentity/IGregTechTileEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CommonBaseMetaTileEntity.java
Labels: refactor, :construction: Testing on Zeta

#4014 We're Going Fishing Son
  src/main/java/gregtech/api/gui/modularui/GTUITextures.java
  src/main/java/gregtech/api/util/FishPondFakeRecipe.java
  src/main/java/gregtech/api/util/FishPondRecipes.java
  src/main/java/gtPlusPlus/GTplusplus.java
  src/main/java/gtPlusPlus/api/recipe/GTPPRecipeMaps.java
  src/main/java/gtPlusPlus/api/recipe/ZhuhaiFrontend.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEIndustrialFishingPond.java
  src/main/resources/assets/gregtech/textures/gui/progressbar/fishing.png
Labels: enhancement, refactor, :construction: Testing on Zeta

#4164 Spirally Infinity Coil Texture
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_INFINITY_BACKGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_INFINITY_BACKGROUND.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_INFINITY_FOREGROUND.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_COIL_INFINITY_FOREGROUND.png.mcmeta
Labels: enhancement, :construction: Testing on Zeta

#4207 Fix kerogen not having LCR recipe, and add cells for fulvic acid and kerogen
  src/main/java/bartworks/common/loaders/FluidLoader.java
  src/main/java/bartworks/common/loaders/recipes/ChemicalReactor.java
  src/main/java/gregtech/common/items/MetaGeneratedItem98.java
Labels: enhancement, bug fix

#4189 fix global_energy_join
  src/main/java/gregtech/common/misc/GTCommand.java
Labels: enhancement, bug fix

#4201 make neutron accelerator hatch not an energy hatch
  src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/MTENeutronAccelerator.java
Labels: enhancement

#4211 Improve Precise Assembler tooltip
  src/main/java/goodgenerator/blocks/tileEntity/MTEPreciseAssembler.java
Labels: enhancement

#4184 Misc decayable gt++ dust QoL improvements
  src/main/java/gtPlusPlus/core/inventories/InventoryDecayablesChest.java
  src/main/java/gtPlusPlus/core/item/materials/DustDecayable.java
Labels: enhancement

#4166 Add text to precise assembler ui displaying the casing voltage limit
  src/main/java/goodgenerator/blocks/tileEntity/MTEPreciseAssembler.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#4190 Remove hard limit on slot 0 for (adv) assline stocking busses
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/gregtech/api/metatileentity/CommonMetaTileEntity.java
  src/main/java/gregtech/api/util/GTRecipe.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputME.java
Labels: enhancement

#4180 Fix distillation tower voiding with multiple output hatches per layer
  src/main/java/gregtech/api/util/OutputHatchWrapper.java
Labels: bug fix

#4128 Adjust infinite spray can keybind controls
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColorInfinite.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#4186 Add MUI2 support for the Radio Hatch
  src/main/java/bartworks/common/tileentities/tiered/MTERadioHatch.java
  src/main/java/gregtech/api/modularui2/GTGuiTextures.java
  src/main/java/gregtech/api/modularui2/GTTextureIds.java
  src/main/resources/assets/gregtech/textures/gui/overlay_button/screwdriver.png
Labels: enhancement

#4154 Add firestone burn effect to GT items
  src/main/java/gregtech/common/blocks/ItemOres.java
  src/main/java/gregtech/common/blocks/ItemStorage.java
  src/main/java/gregtech/common/items/ItemComb.java
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/common/items/MetaGeneratedItem03.java
Labels: enhancement

#4115 Move Large Molecular Assembler to GT5u
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/gui/modularui/GTUITextures.java
  src/main/java/gregtech/api/net/GTPacketLMACraftingFX.java
  src/main/java/gregtech/api/net/GTPacketTypes.java
  src/main/java/gregtech/client/LMACraftingFX.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeMolecularAssembler.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/gui/overlay_button/lma_animation_off.png
  src/main/resources/assets/gregtech/textures/gui/overlay_button/lma_animation_on.png
Labels: refactor, :construction: Testing on Zeta

#4199 Fix industrial apiary upgrades overflow
  src/main/java/gregtech/api/util/GTApiaryUpgrade.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEIndustrialApiary.java
Labels: bug fix

#4210 Remove hasSidedRedstoneOutputBehavior
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBuffer.java
  src/main/java/gtPlusPlus/core/tileentities/base/TileEntityBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTEPollutionDetector.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/redstone/MTERedstoneCircuitBlock.java
  src/main/java/tectech/thing/metaTileEntity/single/MTEOwnerDetector.java
Labels: chore

#4216 Add missing spaces to Drone Center display text in Waila (Attempt 2)
  src/main/java/gregtech/common/tileentities/machines/multi/drone/MTEDroneCentre.java
  src/main/java/gregtech/common/tileentities/machines/multi/drone/MTEHatchDroneDownLink.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: chore

#4198 More Ore Texture Improvements
  src/main/resources/assets/gregtech/textures/blocks/materialicons/CUSTOM/cosmicneutronium/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/DULL/oreSmall.png
Labels: enhancement

#4214 Remove unused biofuel material
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
Labels: refactor

#4218 fix ichorium plasma
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
Labels: bug fix

#4219 Fix Incorrect Colour for Molten and Plasma Ichorium
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.molten.ichorium.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.plasma.ichorium.png
Labels: enhancement

#4221 Add output hatch check to MTEBioVat
  src/main/java/bartworks/common/tileentities/multis/MTEBioVat.java
Labels: bug fix

#4223 Describe UCFE mechanics in the machine tooltip.
  src/main/java/goodgenerator/blocks/tileEntity/MTEUniversalChemicalFuelEngine.java
Labels: chore

#4225 Add mod with "gregtechNH" modid for easier GT6 differentiation
  src/main/java/gregtech/GTNHMod.java
  src/main/resources/mcmod.info
Labels: chore

#4227 Use lowercase modid for gregtech_nh
  src/main/java/gregtech/GTNHMod.java
  src/main/resources/mcmod.info
Labels: chore

#4231 Don't show maintenance readout on unformed multis
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: enhancement

#4226 Widen Modifiers to `protected` in ParallelHelper and OverclockCalculator
  src/main/java/gregtech/api/util/OverclockCalculator.java
  src/main/java/gregtech/api/util/ParallelHelper.java
Labels: chore

#4220 Plasma Texture Improvements
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.plasma.autogenerated.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.plasma.bedrockium.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.plasma.cosmicneutronium.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.plasma.ichorium.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.plasma.infinity.png
  src/main/resources/assets/miscutils/textures/blocks/fluids/fluid.plasma.autogenerated.png
Labels: enhancement, :construction: Testing on Zeta

#4192 Rework Wireless Charger
  src/main/java/gregtech/api/interfaces/tileentity/IWirelessCharger.java
  src/main/java/gregtech/api/util/GTModHandler.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/misc/WirelessChargerManager.java
  src/main/java/gtPlusPlus/core/item/bauble/BatteryPackBaseBauble.java
  src/main/java/gtPlusPlus/core/item/general/ItemHealingDevice.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/textures/TexturesGtBlock.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/helpers/ChargingHelper.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTEWirelessCharger.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechWirelessChargers.java
  src/main/resources/assets/miscutils/lang/en_US.lang
  src/main/resources/assets/miscutils/textures/blocks/TileEntities/adv_machine_screen_inactive.png
Labels: enhancement

#4213 Fix synchronization for wireless computation/data
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchDataConnector.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchWirelessComputationInput.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchWirelessComputationOutput.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchWirelessDataItemsInput.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchWirelessDataItemsOutput.java
Labels: bug fix

#4232 Coal tar recipes for Cactus and sugar charcoal/coke
  src/main/java/gtPlusPlus/core/item/chemistry/RecipeLoaderCoalTar.java
Labels: enhancement, refactor

#4167 Fix laser mirror loop stack overflow & Add debug generator mirror support
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeLaserMirror.java
  src/main/java/tectech/thing/metaTileEntity/single/MTEDebugPowerGenerator.java
Labels: bug fix

#4055 Fusion Recipe Threshold Changes
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer2.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer3.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer4.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer5.java
  src/main/java/goodgenerator/loader/RecipeLoader.java
  src/main/java/goodgenerator/loader/RecipeLoader2.java
  src/main/java/gregtech/loaders/postload/recipes/FusionReactorRecipes.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderChemicalSkips.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderGTNH.java
Labels: Affects Balance

#4235 Fix XLT Muffler Preview & Hologram Dots
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
Labels: bug fix

#4238 Fix intergalactic blocks registration order
  src/main/java/gtnhintergalactic/block/BlockCasingDysonSwarm.java
  src/main/java/gtnhintergalactic/block/BlockCasingGasSiphon.java
  src/main/java/gtnhintergalactic/block/BlockSpaceElevatorCable.java
  src/main/java/gtnhintergalactic/proxy/CommonProxy.java
Labels: bug fix

#4240 Fix Fortune Rich Ores Yielding Less Than Expected
  src/main/java/gregtech/common/blocks/TileEntityOres.java
Labels: bug fix

#4243 Buff HDP
  src/main/java/goodgenerator/loader/FuelRodLoader.java
Labels: Affects Balance

#4191 Port some initial cover UIs to MUI2
  src/main/java/gregtech/api/interfaces/modularui/KeyProvider.java
  src/main/java/gregtech/api/modularui2/CoverGuiData.java
  src/main/java/gregtech/api/modularui2/CoverUIFactory.java
  src/main/java/gregtech/api/modularui2/GTGuis.java
  src/main/java/gregtech/api/util/GTLanguageManager.java
  src/main/java/gregtech/common/covers/Cover.java
  src/main/java/gregtech/common/covers/CoverControlsWork.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverDoesWork.java
  src/main/java/gregtech/common/covers/CoverFacadeBase.java
  src/main/java/gregtech/common/covers/CoverFluidfilter.java
  src/main/java/gregtech/common/covers/CoverIOBase.java
  src/main/java/gregtech/common/covers/CoverItemFilter.java
  src/main/java/gregtech/common/covers/CoverNeedMaintainance.java
  src/main/java/gregtech/common/covers/CoverPlayerDetector.java
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/java/gregtech/common/covers/CoverShutter.java
  src/main/java/gregtech/common/covers/conditions/MaintenanceAlertCondition.java
  src/main/java/gregtech/common/covers/conditions/RedstoneCondition.java
  src/main/java/gregtech/common/covers/gui/CoverControlsWorkGui.java
  src/main/java/gregtech/common/covers/gui/CoverDoesWorkGui.java
  src/main/java/gregtech/common/covers/gui/CoverFacadeBaseGui.java
  src/main/java/gregtech/common/covers/gui/CoverFluidfilterGui.java
  src/main/java/gregtech/common/covers/gui/CoverGui.java
  src/main/java/gregtech/common/covers/gui/CoverIOBaseGui.java
  src/main/java/gregtech/common/covers/gui/CoverItemFilterGui.java
  src/main/java/gregtech/common/covers/gui/CoverNeedMaintenanceGui.java
  src/main/java/gregtech/common/covers/gui/CoverPlayerDetectorGui.java
  src/main/java/gregtech/common/covers/gui/CoverShutterGui.java
  src/main/java/gregtech/common/covers/modes/BlockMode.java
  src/main/java/gregtech/common/covers/modes/DetectionMode.java
  src/main/java/gregtech/common/covers/modes/FilterDirectionMode.java
  src/main/java/gregtech/common/covers/modes/FilterType.java
  src/main/java/gregtech/common/covers/modes/MachineProcessingCondition.java
  src/main/java/gregtech/common/covers/modes/PlayerDetectionMode.java
  src/main/java/gregtech/common/covers/modes/RedstoneMode.java
  src/main/java/gregtech/common/covers/modes/ShutterMode.java
  src/main/java/gregtech/common/covers/modes/TransferMode.java
  src/main/java/gregtech/common/gui/mui1/cover/ItemFilterUIFactory.java
  src/main/java/gregtech/common/modularui2/sync/LinkedBoolValue.java
  src/main/java/gregtech/common/modularui2/util/FlowActions.java
  src/main/java/gregtech/common/modularui2/widget/CoverTickRateButton.java
  src/main/java/gregtech/common/modularui2/widget/SelectButton.java
  src/main/java/gregtech/common/modularui2/widget/builder/EnumRowBuilder.java
Labels: refactor
