Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2025-06, with the labels that each got.

#4391 Add more info to scanner for Tesla Tower
  src/main/java/tectech/thing/metaTileEntity/multi/MTETeslaTower.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement, :construction: Testing on Zeta

#4431 Add missing number formatting to some godforge ui elements
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/util/ForgeOfGodsUI.java
Labels: enhancement

#4432 Fix imprint recipes
  src/main/java/bartworks/MainMod.java
  src/main/java/bartworks/system/material/WerkstoffLoader.java
Labels: bug fix

#4430 Make cribs cache keep order of recipes
  src/main/java/gregtech/api/logic/ProcessingLogic.java
Labels: bug fix

#4196 Protect some calls that lead to loadChunk with blockExists
  src/main/java/gregtech/common/tileentities/machines/basic/MTEIndustrialApiary.java
  src/main/java/gtPlusPlus/core/tileentities/machines/TileEntityPestKiller.java
Labels: enhancement, bug fix

#4433 Fluid link covers adjustments
  src/main/java/gregtech/common/gui/mui1/cover/EnderFluidLinkUIFactory.java
  src/main/java/tectech/thing/cover/CoverEnderFluidLink.java
Labels: bug fix, safe for stable

#4435 Fix large fluid extractor having a missing front overlay
  src/main/resources/assets/miscutils/textures/blocks/iconsets/controllerFaces/largeFluidExtractor.png.mcmeta
Labels: bug fix

#4436 Fix ME output bus/hatch not getting formed textures
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
Labels: bug fix

#4413 Tweak Vajra Right Click
  src/main/java/gregtech/common/tools/ToolVajra.java
Labels: bug fix

#3881 Void Miners Rebrand
  src/main/java/bwcrossmod/galacticgreg/MTEVoidMinerBase.java
  src/main/java/bwcrossmod/galacticgreg/MTEVoidMiners.java
  src/main/java/gregtech/api/casing/Casings.java
  src/main/java/gregtech/api/casing/ICasing.java
  src/main/java/gregtech/loaders/load/MTERecipeLoader.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement, new feature, :construction: Testing on Zeta

#4443 Soft Mallet Maintenance
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: bug fix, safe for stable

#4439 Add ctm compatibility to gt casings
  dependencies.gradle
  src/main/java/gregtech/common/render/GTCopiedBlockTextureRender.java
Labels: bug fix

#4446 Added back the Energy Hatch ctor with inventory size
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchEnergy.java
Labels: chore, :construction: Testing on Zeta

#4456 Fix Large Fluid Extractor not using any power
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeFluidExtractor.java
Labels: bug fix

#4454 Remove pollution fluid mentions from Advanced Muffler
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchMufflerAdvanced.java
Labels: enhancement

#4453 Add BlockCasings13
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/common/blocks/BlockCasings13.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
Labels: new feature

#4458 AL and AAL Fixes
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAssemblyLine.java
Labels: bug fix

#4457 Improve performance of registering EEC events
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeEntityCrusher.java
Labels: enhancement, bug fix

#4462 Implement ISurvivalConstructable in MTEVoidMinerBase
  src/main/java/bwcrossmod/galacticgreg/MTEVoidMinerBase.java
  src/main/java/bwcrossmod/galacticgreg/MTEVoidMiners.java
Labels: bug fix

#4451 Optimize monster repellent performance
  dependencies.gradle
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/util/GTSpawnEventHandler.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEMonsterRepellent.java
Labels: enhancement, bug fix, :construction: Testing on Zeta

#4289 Implement MagLev Pylon
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/api/net/GTPacketTether.java
  src/main/java/gregtech/api/net/GTPacketTypes.java
  src/main/java/gregtech/common/config/Client.java
  src/main/java/gregtech/common/data/maglev/Tether.java
  src/main/java/gregtech/common/data/maglev/TetherManager.java
  src/main/java/gregtech/common/items/ItemMagLevHarness.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEMagLevPylon.java
  src/main/java/gregtech/loaders/load/MTERecipeLoader.java
  src/main/java/gregtech/loaders/postload/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MAGLEV.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MAGLEV_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MAGLEV_ACTIVE.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MAGLEV_ACTIVE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_MAGLEV_ACTIVE_GLOW.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.MaglevHarness.png
Labels: Affects Balance, new feature, :construction: Testing on Zeta

#4281 Add Naquarite Insulator Line
  src/main/java/bartworks/common/loaders/recipes/Assembler.java
  src/main/java/bartworks/common/loaders/recipes/AssemblyLine.java
  src/main/java/goodgenerator/loader/RecipeLoader.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/common/items/IDMetaItem03.java
  src/main/java/gregtech/common/items/MetaGeneratedItem03.java
  src/main/java/gregtech/common/render/items/RainbowOverlayMetaItemRenderer.java
  src/main/java/gregtech/common/render/items/RainbowOverlayRenderer.java
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
  src/main/java/gregtech/loaders/postload/chains/NetheriteRecipes.java
  src/main/java/gregtech/loaders/postload/chains/PCBFactoryRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/ArcFurnaceRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblyLineRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/Pulverizer.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/java/gtPlusPlus/core/item/ModItems.java
  src/main/java/gtPlusPlus/core/item/chemistry/RecipeLoaderMilling.java
  src/main/java/gtPlusPlus/core/item/chemistry/general/ItemGenericChemBase.java
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/enums/GregtechItemList.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialPlatePress.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/MTEChemicalPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderChemicalSkips.java
  src/main/java/tectech/loader/recipe/ResearchStationAssemblyLine.java
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.fluid.prismaticacid.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.fluid.prismaticacid.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.03/248.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.03/249.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.03/249.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.03/250.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.03/251.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/prismaticacid/cell.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/prismaticacid/cell.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/prismaticacid/cell_OVERLAY.png
  src/main/resources/assets/miscutils/lang/en_US.lang
  src/main/resources/assets/miscutils/textures/items/science/general/MetaItem1/35.png
Labels: Affects Balance, new feature, :construction: Testing on Zeta

#4467 Remove second separator line from LINAC tooltip
  src/main/java/gtnhlanth/common/tileentity/MTELINAC.java
Labels: bug fix

#4478 Small Performance Improvement in `setMufflers`
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: refactor, Performance

#4479 Implement `GTUtility.log2` and `GTUtility.log4`
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/OverclockCalculator.java
  src/main/java/gregtech/common/items/ItemComb.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPlasmaForge.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEWormholeGenerator.java
  src/main/java/kubatech/api/helpers/GTHelper.java
  src/main/java/kubatech/api/implementations/KubaTechGTMultiBlockBase.java
  src/test/java/gregtech/api/util/GTUtilityTest.java
Labels: refactor, Performance

#4480 Improve WA Tooltip
  src/main/java/gregtech/common/tileentities/machines/basic/MTEWorldAccelerator.java
Labels: enhancement, safe for stable

#4463 Fix Linked Input Bus data stick interaction.
  src/main/java/ggfab/mte/MTELinkedInputBus.java
Labels: bug fix, safe for stable

#4488 Refactor MegLev Code
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/net/GTPacketTether.java
  src/main/java/gregtech/client/TetherLineRenderer.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/data/maglev/TetherManager.java
  src/main/java/gregtech/common/items/ItemMagLevHarness.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEMagLevPylon.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: refactor, bug fix

#4469 Introduce `cacheMap` for Recipe Search Optimization
  src/main/java/bartworks/common/tileentities/multis/MTEWindmill.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaVacuumFreezer.java
  src/main/java/gregtech/api/logic/ProcessingLogic.java
  src/main/java/gregtech/api/recipe/FindRecipeQuery.java
  src/main/java/gregtech/api/recipe/RecipeMapBackend.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEBoxinator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDecayWarehouse.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialElectromagneticSeparator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialExtractor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIntegratedOreFactory.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeFluidExtractor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiLathe.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEOreDrillingPlantBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEVacuumFreezer.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEHIPCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEIndustrialCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTENeutroniumCompressor.java
  src/main/java/gregtech/common/tileentities/machines/steam/MTESteamMaceratorBronze.java
  src/main/java/gregtech/common/tileentities/machines/steam/MTESteamMaceratorSteel.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/misc/MTEAmazonPackager.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialChisel.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialDehydrator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialMolecularTransformer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialSifter.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialThermalCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialVacuumFreezer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialWashPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEndustrialElectrolyzer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvImplosionCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
  src/main/java/gtnhlanth/common/tileentity/MTESourceChamber.java
Labels: enhancement, Performance

#4485 Improved a text of Drone Center
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: bug fix

#4482 Milling Machine Recipe Changes
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
Labels: Affects Balance

#4484 Remove broken TileEvent subscription
  src/main/java/goodgenerator/blocks/regularBlock/BlockTEContainer.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEEssentiaOutputHatchME.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
Labels: enhancement, bug fix, :construction: Testing on Zeta

#4494 Fix Mass Fabricator Scrapbox Recipe
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechIndustrialMassFabricator.java
Labels: Bug Fix

#4496 Fix EU Detection Covers for LSCs with UHV+ caps
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
Labels: Bug Fix, Safe for Stable

#4497 [Temp Fix] Dont hash null stacks
  src/main/java/gregtech/api/recipe/RecipeMapBackend.java
Labels: Bug Fix

#4507 Fix file name casing of custom tc4 aspects
  src/main/resources/assets/gregtech/textures/aspects/AEQUALITAS.png
  src/main/resources/assets/gregtech/textures/aspects/ASTRUM.png
  src/main/resources/assets/gregtech/textures/aspects/GLORIA.png
  src/main/resources/assets/gregtech/textures/aspects/PRIMORDIUM.png
  src/main/resources/assets/gregtech/textures/aspects/VESANIA.png
Labels: Bug Fix

#4470 added Data Orb copying for ME Output Bus
  src/main/java/gregtech/api/util/GTUtil.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
Labels: Enhancement, Bug Fix, :construction: Testing on Zeta

#4495 Fixed misaligned entries in MaterialsInit1.java
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
Labels: Bug Fix

#4510 Add laser & energy hatches to Large Naquadah Reactor
  src/main/java/goodgenerator/blocks/tileEntity/MTEMultiNqGenerator.java
Labels: Enhancement, :construction: Testing on Zeta

#4515 delete unused class FlowerSet.java
  src/main/java/bartworks/util/flowerset/FlowerSet.java
Labels: Refactor

#4518 fix output hatch partition
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
Labels: Bug Fix

#4448 Added Netherite Bee and Prismarine Bee
  src/main/java/gregtech/common/items/CombType.java
  src/main/java/gregtech/loaders/misc/GTBeeDefinition.java
Labels: Enhancement, Affects Balance

#4522 Rare Earth Bee Changes
  src/main/java/gregtech/common/items/CombType.java
  src/main/java/gregtech/loaders/misc/GTBeeDefinition.java
  src/main/java/gtPlusPlus/core/recipe/RecipesRareEarthProcessing.java
Labels: Enhancement

#4501 Add Nullity Annotations to GoodGenerator API
  src/main/java/goodgenerator/api/recipe/ExtremeHeatExchangerRecipe.java
Labels: Refactor

#4503 Add Nullity Annotations to GTPlusPlus API
  src/main/java/gtPlusPlus/api/objects/minecraft/BTF_FluidTank.java
  src/main/java/gtPlusPlus/api/objects/minecraft/BTF_Inventory.java
  src/main/java/gtPlusPlus/api/objects/minecraft/BlockPos.java
  src/main/java/gtPlusPlus/api/objects/minecraft/CubicObject.java
  src/main/java/gtPlusPlus/api/objects/minecraft/FluidGT6.java
  src/main/java/gtPlusPlus/api/objects/minecraft/ItemStackData.java
  src/main/java/gtPlusPlus/api/objects/minecraft/SafeTexture.java
  src/main/java/gtPlusPlus/api/objects/minecraft/ShapedRecipe.java
  src/main/java/gtPlusPlus/api/recipe/SpargeTowerFrontend.java
  src/main/java/gtPlusPlus/api/recipe/ZhuhaiFrontend.java
Labels: Refactor

#4505 Add Nullity Annotations to KubaTech API
  src/main/java/kubatech/api/DynamicInventory.java
  src/main/java/kubatech/api/EIGDynamicInventory.java
  src/main/java/kubatech/api/eig/EIGBucket.java
  src/main/java/kubatech/api/eig/EIGDropTable.java
  src/main/java/kubatech/api/eig/EIGMode.java
  src/main/java/kubatech/api/enums/EIGModes.java
  src/main/java/kubatech/api/enums/ItemList.java
  src/main/java/kubatech/api/gui/AutoScalingStackSizeText.java
  src/main/java/kubatech/api/helpers/GTHelper.java
  src/main/java/kubatech/api/implementations/KubaTechGTMultiBlockBase.java
  src/main/java/kubatech/api/tea/TeaNetwork.java
  src/main/java/kubatech/api/utils/ItemUtils.java
  src/main/java/kubatech/api/utils/StringUtils.java
Labels: Refactor

#4498 Add Null Annotations in `RecipeMapBackend` for Recipe Checks
  src/main/java/gregtech/api/recipe/RecipeMapBackend.java
Labels: Refactor

#4526 "Zeron-100 Reactor Shielding" Name-Change & Assembler Recipe Addition
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/GregtechMetaCasingBlocks.java
Labels: Enhancement

#4460 Improve cape renderer + use UUID map
  src/main/java/gregtech/client/capes/GTCapesEventHandler.java
  src/main/java/gregtech/client/capes/GTCapesLoader.java
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gregtech/common/render/GTCapeRenderer.java
  src/main/java/gregtech/mixin/Mixin.java
  src/main/java/gregtech/mixin/interfaces/accessors/AbstractClientPlayerAccessor.java
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/AbstractClientPlayerMixin.java
Labels: Enhancement, Refactor, Performance

#4521 Various minor ArrayList / array / boxed collections improvements
  src/main/java/bartworks/common/tileentities/tiered/MTEAcidGenerator.java
  src/main/java/bartworks/system/material/WerkstoffLoader.java
  src/main/java/bartworks/system/material/gtenhancement/BWGTMetaItems.java
  src/main/java/bwcrossmod/cls/CLSCompat.java
  src/main/java/bwcrossmod/galacticraft/atmosphere/BWAtmosphereManager.java
  src/main/java/gregtech/api/enums/TAE.java
  src/main/java/gregtech/api/interfaces/tileentity/IGregTechDeviceInformation.java
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CommonMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicTank.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEFluidPipe.java
  src/main/java/gregtech/api/util/GTOreDictUnificator.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/items/ItemComb.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIntegratedOreFactory.java
  src/main/java/gregtech/loaders/misc/bees/GTEffectTreeTwister.java
  src/main/java/gregtech/loaders/preload/GTPreLoad.java
  src/main/java/gtPlusPlus/api/objects/minecraft/ShapedRecipe.java
  src/main/java/gtPlusPlus/core/item/base/BaseItemTickable.java
  src/main/java/gtPlusPlus/core/item/base/CoreItem.java
  src/main/java/gtPlusPlus/core/item/base/misc/BaseItemParticle.java
  src/main/java/gtPlusPlus/core/item/chemistry/RecipeLoaderRocketFuels.java
  src/main/java/gtPlusPlus/core/material/Material.java
  src/main/java/gtPlusPlus/xmod/bop/blocks/base/LeavesBase.java
  src/main/java/gtPlusPlus/xmod/bop/blocks/base/LogBase.java
  src/main/java/gtPlusPlus/xmod/bop/blocks/base/SaplingBase.java
  src/main/java/gtPlusPlus/xmod/bop/blocks/pine/LeavesPineTree.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchTurbine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/automation/MTETesseractGenerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTEPollutionCreator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTEPollutionDetector.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTEWirelessCharger.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialChisel.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/algae/MTEAlgaePondBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/misc/MTESolarHeater.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/storage/MTEEnergyBuffer.java
  src/main/java/gtneioreplugin/util/GT5OreLayerHelper.java
  src/main/java/gtnhlanth/common/tileentity/MTESourceChamber.java
  src/main/java/gtnhlanth/common/tileentity/MTETargetChamber.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEExoticModule.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEBaseFactoryPipe.java
  src/main/java/toxiceverglades/biome/GenLayerEverglades.java
Labels: Refactor, Performance

#4528 Fix mapiary crash on removing bees
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEMegaIndustrialApiary.java
Labels: Bug Fix

#4529 Fix LSC structure preview crash
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
Labels: Bug Fix

#4524 Refactor `gregtech.api.enums.Dyes`
  src/main/java/bartworks/common/loaders/recipes/ChemicalBath.java
  src/main/java/bartworks/common/tileentities/multis/MTELESU.java
  src/main/java/gregtech/api/enums/Dyes.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/api/interfaces/metatileentity/IMetaTileEntity.java
  src/main/java/gregtech/api/interfaces/modularui/IGetTitleColor.java
  src/main/java/gregtech/api/interfaces/tileentity/IColoredTileEntity.java
  src/main/java/gregtech/api/metatileentity/BaseTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachineBronze.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachineSteel.java
  src/main/java/gregtech/api/metatileentity/implementations/MTECable.java
  src/main/java/gregtech/api/recipe/maps/PrinterBackend.java
  src/main/java/gregtech/api/util/GTUtil.java
  src/main/java/gregtech/api/util/GTUtilityClient.java
  src/main/java/gregtech/common/blocks/BlockCasings2.java
  src/main/java/gregtech/common/blocks/BlockCasingsNH.java
  src/main/java/gregtech/common/gui/modularui/uifactory/SelectItemUIFactory.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColorInfinite.java
  src/main/java/gregtech/common/render/GTTextureBuilder.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoilerLava.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoilerSolar.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoilerSolarSteel.java
  src/main/java/gregtech/common/tileentities/machines/MTEBasicHullBronze.java
  src/main/java/gregtech/common/tileentities/machines/MTEBasicHullBronzeBricks.java
  src/main/java/gregtech/common/tileentities/machines/MTEBasicHullSteel.java
  src/main/java/gregtech/common/tileentities/machines/MTEBasicHullSteelBricks.java
  src/main/java/gregtech/common/tools/ToolMortar.java
  src/main/java/gregtech/common/tools/ToolRollingPin.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/ChemicalBathRecipes.java
  src/main/java/gregtech/loaders/preload/GTPreLoad.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/GTPPMTECable.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvFusionMk4.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvFusionMk5.java
  src/main/java/gtnhlanth/common/beamline/MTEBeamlinePipe.java
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
  src/main/java/tectech/thing/metaTileEntity/Textures.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/render/TTRenderedExtendedFacingTexture.java
Labels: Refactor, Performance

#4532 Add BHC to Machine Type
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
Labels: Chore, :construction: Testing on Zeta, Safe for Stable
