Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2025-03, with the labels that each got.

#4009 Specify heat overclocks in Zyngen tooltip
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialAlloySmelter.java
Labels: enhancement

#4011 Fix integer division in LINAC energy calculation
  src/main/java/gtnhlanth/common/tileentity/MTELINAC.java
Labels: bug fix

#4017 Remove Hatch Placement Restriction on Large Thermal Refinery
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialThermalCentrifuge.java
Labels: enhancement

#4018 Add rotation + some fixes for Lead Lined Box
  src/main/java/gtPlusPlus/core/block/machine/BlockDecayablesChest.java
  src/main/java/gtPlusPlus/core/client/renderer/RenderDecayChest.java
  src/main/java/gtPlusPlus/core/tileentities/general/TileEntityDecayablesChest.java
Labels: enhancement, bug fix

#4021 Replace turbine casing textures
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_TURBINE_STAINLESSSTEEL.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_TURBINE_STEEL.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_TURBINE_TITANIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/MACHINE_CASING_TURBINE_TUNGSTENSTEEL.png
Labels: enhancement

#4019 Localization 250303
  src/main/java/gregtech/api/util/JubilanceMegaApiary.java
  src/main/java/gregtech/common/items/ItemComb.java
  src/main/java/gtPlusPlus/core/item/food/BaseItemMetaFood.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#3997 Re-enable wire up and down crafting for lategame wires
  src/main/java/gregtech/loaders/oreprocessing/ProcessingWire.java
Labels: enhancement

#4010 Fix level8 Purification Unit not consume ME inputs on successful catalyst insertion
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBaryonicPerfection.java
Labels: bug fix, :construction: Testing on Zeta

#4015 Better handle capacityless fluid containers
  src/main/java/gregtech/api/util/GTUtility.java
Labels: bug fix

#4006 Take DTPF catalyst discount into account on recipecheck
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPlasmaForge.java
Labels: enhancement

#4008 Merge itemstacks in some assline recipes 1/3
  src/main/java/goodgenerator/loader/RecipeLoader.java
  src/main/java/goodgenerator/loader/RecipeLoader2.java
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
  src/main/java/kekztech/common/recipeLoaders/AssemblyLine.java
  src/main/java/kekztech/common/recipeLoaders/ResearchableAssemblyLine.java
  src/main/java/kubatech/loaders/RecipeLoader.java
  src/main/java/tectech/loader/recipe/ResearchStationAssemblyLine.java
Labels: enhancement

#4026 Fix cover GUI
  dependencies.gradle
  src/main/java/gregtech/common/GTServer.java
Labels: bug fix

#4027 Fix Cover refactor mistakes
  src/main/java/gregtech/common/covers/CoverShutter.java
  src/main/java/gregtech/common/covers/redstone/CoverAdvancedRedstoneReceiverInternal.java
Labels: bug fix

#4028 Merge MTEBrickedBlastFurnace and MTEPrimitiveBlastFurnace
  src/main/java/gregtech/common/tileentities/machines/multi/MTEBrickedBlastFurnace.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPrimitiveBlastFurnace.java
  src/main/java/gregtech/nei/NEIGTConfig.java
  src/main/java/gtPlusPlus/nei/NEIGTPPConfig.java
Labels: refactor

#4031 Require sneaking to place cover
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/common/blocks/BlockMachines.java
Labels: enhancement

#4030 fix catalyst for crude rhodium in QFT
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderChemicalSkips.java
Labels: bug fix

#4024 Supplement locale
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#4034 Fix Fluid Regulator covers pipe connection
  src/main/java/gregtech/api/metatileentity/implementations/MTEFluidPipe.java
Labels: bug fix

#4035 Fix Shutter cover crash
  src/main/java/gregtech/common/covers/CoverShutter.java
Labels: bug fix

#4029 Simplify parallel calculations and tooltip for multi smelter
  src/main/java/gregtech/api/enums/HeatingCoilLevel.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiFurnace.java
Labels: enhancement, Affects Balance

#4041 Fix black hole utility hatch gui not opening
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleUtility.java
Labels: bug fix

#4044 Add recipes for tiny GTPP pipes
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechConduits.java
Labels: enhancement

#4045 Fix non gt item covers not working when sneaking
  src/main/java/gregtech/mixin/Mixin.java
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/ItemMixin.java
Labels: bug fix

#4040 Localization of item tooltips
  src/main/java/bartworks/common/tileentities/multis/MTEHighTempGasCooledReactor.java
  src/main/java/gregtech/api/items/GTGenericItem.java
  src/main/java/gtPlusPlus/core/item/base/BaseItemComponent.java
  src/main/java/gtPlusPlus/core/item/base/BaseItemTickable.java
  src/main/java/gtPlusPlus/core/item/chemistry/IonParticles.java
  src/main/java/gtPlusPlus/core/item/chemistry/StandardBaseParticles.java
  src/main/java/gtPlusPlus/core/item/circuit/GTPPIntegratedCircuitItem.java
  src/main/java/gtPlusPlus/core/item/general/ItemBasicScrubberTurbine.java
  src/main/java/gtPlusPlus/core/item/general/ItemBufferCore.java
  src/main/java/gtPlusPlus/core/item/general/ItemMagicFeather.java
  src/main/java/gtPlusPlus/core/item/general/books/ItemBaseBook.java
  src/main/java/gtPlusPlus/core/item/tool/misc/ItemGregtechPump.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/items/GTGenericItem.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/items/GTMetaItemBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/GregtechMetaCasingBlocks2.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/GregtechMetaCasingBlocks3.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/GregtechMetaTieredCasingBlocks1.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/items/MetaCustomCoverItem.java
  src/main/java/gtnhlanth/common/item/ItemParticle.java
  src/main/java/gtnhlanth/common/item/ItemPhotolithographicMask.java
  src/main/java/kekztech/common/itemBlocks/ItemBlockLapotronicEnergyUnit.java
  src/main/java/kekztech/common/itemBlocks/ItemBlockTFFTStorageField.java
  src/main/java/kekztech/common/items/ErrorItem.java
  src/main/java/kekztech/common/items/MetaItemCraftingComponent.java
  src/main/java/tectech/thing/casing/ItemCasingsTT.java
  src/main/java/tectech/thing/item/ItemParametrizerMemoryCard.java
  src/main/java/toxiceverglades/item/ItemBlockToxicEverglades.java
  src/main/java/toxiceverglades/item/ItemEvergladesPortalTrigger.java
  src/main/resources/assets/bartworks/lang/en_US.lang
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gtnhlanth/lang/en_US.lang
  src/main/resources/assets/kekztech/lang/en_US.lang
  src/main/resources/assets/miscutils/lang/en_US.lang
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement

#3828 Added the ability to filter outputs to ME Output Bus and Hatch
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/util/VoidProtectionHelper.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#4050 Fix ZPM Hull Recycling
  src/main/java/gregtech/loaders/load/MTERecipeLoader.java
Labels: bug fix

#4047 migrate fusion recipe startup energy thresholds to use long
  src/main/java/bartworks/system/material/processingLoaders/AdditionalRecipes.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer1.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer2.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer3.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer4.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer5.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeFusionComputer.java
  src/main/java/goodgenerator/loader/RecipeLoader.java
  src/main/java/goodgenerator/loader/RecipeLoader2.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEFusionComputer.java
  src/main/java/gregtech/loaders/postload/recipes/FusionReactorRecipes.java
  src/main/java/gregtech/nei/formatter/FusionSpecialValueFormatter.java
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderChemicalSkips.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderGTNH.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderNuclear.java
Labels: refactor, :construction: Testing on Zeta

#4053 Implement survival autoplace for tectech machines
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEnergyInfuser.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEMicrowave.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTENetworkSwitch.java
Labels: enhancement

#4022 Refactor pipe registration & move item pipes from coremod
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/loaders/preload/LoaderMetaPipeEntities.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechConduits.java
Labels: refactor

#4054 Fix Synchotron and Source Chamber block rendering issue
  src/main/java/goodgenerator/loader/Loaders.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/common/blocks/BlockCasings5.java
  src/main/java/gtnhlanth/common/register/LanthItemList.java
  src/main/java/gtnhlanth/common/tileentity/MTELINAC.java
  src/main/java/gtnhlanth/common/tileentity/MTESourceChamber.java
  src/main/java/gtnhlanth/common/tileentity/MTESynchrotron.java
  src/main/java/gtnhlanth/common/tileentity/MTETargetChamber.java
Labels: bug fix

#4048 Godforge graviton shard related fixes
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEExoticModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/util/GodforgeMath.java
Labels: bug fix

#4012 Add rotation support to the Bacterial Vat
  src/main/java/bartworks/common/tileentities/multis/MTEBioVat.java
Labels: enhancement

#4033 Fix texture orientation for some machine controllers
  src/main/java/goodgenerator/blocks/tileEntity/MTEFuelRefineFactory.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEMultiNqGenerator.java
  src/main/java/goodgenerator/blocks/tileEntity/MTENeutronActivator.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEPreciseAssembler.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEUniversalChemicalFuelEngine.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEYottaFluidTank.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMixer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/storage/MTEPowerSubStation.java
Labels: bug fix

#4057 AL Refactor Fixes
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/gregtech/api/util/AssemblyLineUtils.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAssemblyLine.java
Labels: bug fix

#4061 Typo: "ignot" -> "ingot"
  src/main/java/gtPlusPlus/core/item/base/BaseItemComponent.java
  src/main/resources/assets/miscutils/lang/en_US.lang
Labels: bug fix

#4069 Add missing Hot Ingot texture for Manasteel Texture Set
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/Manasteel/ingotHot.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/Manasteel/ingotHot_OVERLAY.png
Labels: enhancement

#4064 Creon & mellion mini rework
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/common/items/IDMetaItem03.java
  src/main/java/gregtech/common/items/MetaGeneratedItem03.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingCell.java
  src/main/java/gregtech/loaders/postload/chains/NaniteChain.java
  src/main/java/gregtech/loaders/postload/recipes/BlastFurnaceRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/VacuumFreezerRecipes.java
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.03/762.png
Labels: Affects Balance

#4051 Allow searching for Random Access Memory using "RAM"
  src/main/java/gregtech/common/items/MetaGeneratedItem03.java
Labels: bug fix

#4073 Allow distilled water in algae pond structure
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/algae/MTEAlgaePondBase.java
Labels: enhancement

#3973 zfighting free block overlay
  src/main/java/goodgenerator/blocks/regularBlock/BlockTurbineCasing.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeTurbineBase.java
  src/main/java/goodgenerator/client/render/BlockRenderHandler.java
  src/main/java/goodgenerator/loader/Loaders.java
  src/main/java/gregtech/api/enums/Mods.java
  src/main/java/gregtech/api/render/RenderOverlay.java
  src/main/java/gregtech/api/util/GTUtilityClient.java
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gregtech/common/blocks/BlockCasingsAbstract.java
  src/main/java/gregtech/common/render/GTRendererBlock.java
  src/main/java/gregtech/common/render/GTRendererCasing.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAirFilterBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
  src/main/java/gregtech/mixin/Mixin.java
  src/main/java/gregtech/mixin/interfaces/accessors/ChunkCacheAccessor.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchTurbine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialCentrifuge.java
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/accessors/ChunkCacheMixin.java
Labels: enhancement

#4013 Stocking hatch & bus disabling
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CommonMetaTileEntity.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputME.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#4052 Re-add multi-step californium recipe and make it faster
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderGTNH.java
Labels: Affects Balance

#4042 Fix output slot of quantum chest etc. not being recognized by AE
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchBulkCatalystHousing.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchNanite.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchNonConsumableBase.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/tileentities/storage/MTEDigitalChestBase.java
  src/main/java/gregtech/common/tileentities/storage/MTEQuantumChest.java
  src/main/java/gregtech/crossmod/ae2/IMEAwareItemInventory.java
  src/main/java/gregtech/crossmod/ae2/MEItemInventoryHandler.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/redstone/MTERedstoneCircuitBlock.java
Labels: bug fix

#4038 Refactor OverclockCalculator
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEComponentAssemblyLine.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEPreciseAssembler.java
  src/main/java/gregtech/api/logic/ProcessingLogic.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
  src/main/java/gregtech/api/objects/overclockdescriber/SteamOverclockDescriber.java
  src/main/java/gregtech/api/util/OverclockCalculator.java
  src/main/java/gregtech/api/util/ParallelHelper.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEMassfabricator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPCBFactory.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialAlloySmelter.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMixer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/mega/MTEMegaAlloyBlastSmelter.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEDEFusionCrafter.java
  src/test/java/gregtech/overclock/GT_OverclockCalculator_UnitTest.java
Labels: refactor, :construction: Testing on Zeta

#3703 Add MTESolarFactory
  src/main/java/gregtech/api/enums/GTValues.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/api/logic/ProcessingLogic.java
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/api/recipe/metadata/SolarFactoryRecipeDataKey.java
  src/main/java/gregtech/api/util/GTLanguageManager.java
  src/main/java/gregtech/api/util/recipe/SolarFactoryRecipeData.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTESolarFactory.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_SOLAR_FACTORY_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_SOLAR_FACTORY_ACTIVE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_SOLAR_FACTORY_INACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_SOLAR_FACTORY_INACTIVE_GLOW.png
Labels: new feature

#4081 Decrement single-use screwdriver on circuit change
  src/main/java/gregtech/common/items/ItemIntegratedCircuit.java
Labels: bug fix

#4079 fix crowbar train reversing/boosting compatibility
  src/main/java/gregtech/api/items/MetaGeneratedTool.java
Labels: bug fix

#4083 Fix pipe dupe
  src/main/java/gregtech/common/misc/DrillingLogicDelegate.java
Labels: bug fix

#4084 Fix tectech EnderFluidLink cover ghost loading
  src/main/java/tectech/mechanics/enderStorage/EnderLinkTank.java
  src/main/java/tectech/mechanics/enderStorage/EnderWorldSavedData.java
Labels: bug fix

#4080 add half mode to power transformers
  src/main/java/gregtech/api/metatileentity/implementations/MTEWetTransformer.java
Labels: enhancement

#4071 Remove BW Pair class
  src/main/java/bartworks/common/net/PacketOreDictCache.java
  src/main/java/bartworks/system/material/CircuitGeneration/CircuitImprintLoader.java
  src/main/java/bartworks/system/material/Werkstoff.java
  src/main/java/bartworks/system/material/WerkstoffLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/AspectLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/CellLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/DustLoader.java
  src/main/java/bartworks/system/oredict/OreDictAdder.java
  src/main/java/bartworks/system/oredict/OreDictHandler.java
  src/main/java/bartworks/system/oregen/BWOreLayer.java
  src/main/java/bartworks/system/worldgen/MapGenRuins.java
  src/main/java/bartworks/util/Pair.java
  src/main/java/bwcrossmod/galacticraft/atmosphere/BWAtmosphereManager.java
  src/main/java/bwcrossmod/thaumcraft/util/ThaumcraftHandler.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEMultiNqGenerator.java
  src/main/java/goodgenerator/items/GGMaterial.java
  src/main/java/gtnhlanth/common/register/BotWerkstoffMaterialPool.java
  src/main/java/gtnhlanth/common/register/WerkstoffMaterialPool.java
Labels: refactor

#4088 Change double plate max stack size to 64
  src/main/java/gtPlusPlus/core/item/base/plates/BaseItemPlateDouble.java
Labels: enhancement

#4089 Fix waila for steam machine parallel
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMixer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
Labels: bug fix

#4092 Lower large boiler pollution config defaults
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/pollution/PollutionConfig.java
Labels: enhancement

#4085 Modern Ore Textures
  src/main/resources/assets/gregtech/textures/blocks/materialicons/CUSTOM/bedrockium/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/CUSTOM/cosmicneutronium/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/DIAMOND/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/DIAMOND/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/DULL/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/EMERALD/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/EMERALD/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/FINE/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/FLINT/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/GEM_A/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/GEM_A/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/GEM_HORIZONTAL/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/GEM_HORIZONTAL/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/GEM_VERTICAL/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/GEM_VERTICAL/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/LAPIS/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/LIGNITE/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/METALLIC/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/METALLIC/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/NETHERSTAR/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/NETHERSTAR/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/NONE/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/NONE/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/OPAL/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/OPAL/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/POWDER/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/QUARTZ/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/ROUGH/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/ROUGH/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/RUBY/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/RUBY/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/SAND/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/SHARDS/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/SHINY/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/SHINY/oreSmall.png
Labels: enhancement, :construction: Testing on Zeta

#3982 Change aqua regia to follow real life composition
  src/main/java/bartworks/system/material/WerkstoffLoader.java
  src/main/java/bartworks/system/material/gtenhancement/PlatinumSludgeOverHaul.java
Labels: Affects Balance

#4090 Allow SLAM to be built faster with Hologram Projector
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
Labels: enhancement

#4093 Localization of additional tooltips
  src/main/java/bartworks/system/material/CircuitGeneration/BWMetaItems.java
  src/main/java/gregtech/api/items/MetaGeneratedTool.java
  src/main/java/gregtech/common/items/ItemVolumetricFlask.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/items/GTMetaTool.java
  src/main/resources/assets/bartworks/lang/en_US.lang
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/miscutils/lang/en_US.lang
Labels: enhancement

#4086 Fix efficiency not going down after disabling the multiblock
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: bug fix

#4036 Adding Proper Batch, Mask Parallel & Adjusting Focus Bus on Beamline
  src/main/java/gtnhlanth/common/hatch/MTEBusInputFocus.java
  src/main/java/gtnhlanth/common/tileentity/MTETargetChamber.java
Labels: enhancement, Affects Balance

#4091 New Later Recipe for Rhugnor
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
Labels: Affects Balance

#4094 Fix AL recipe packet NPE on world load
  src/main/java/tectech/mechanics/dataTransport/ALRecipeDataPacket.java
Labels: bug fix

#4101 Fix Antimatter Sequencer Tricoder info showing wrong information.
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
Labels: bug fix

#4104 Require sneaking to place cover on pipes, wires and frame boxes
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
Labels: enhancement, bug fix

#4106 Fix Degasser Scanner Info Bug
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitDegasser.java
Labels: bug fix

#4109 Fix Leftover wafers from beamline durability calculation
  src/main/java/gtnhlanth/common/tileentity/MTETargetChamber.java
Labels: bug fix, :construction: Testing on Zeta

#4108 Fix pipe collisions
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTECable.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEFluidPipe.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEFrame.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEItemPipe.java
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/GTPPMTECable.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/GTPPMTEFluidPipe.java
  src/main/java/gtnhlanth/common/beamline/MTEBeamlinePipe.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEBaseFactoryPipe.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeBlockData.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeBlockLaser.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeData.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeLaser.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeLaserMirror.java
Labels: bug fix, :construction: Testing on Zeta

#4066 MUI2 port part2: Widget Theme
  src/main/java/gregtech/api/metatileentity/CommonMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchMagnet.java
  src/main/java/gregtech/api/modularui2/GTGuiTextures.java
  src/main/java/gregtech/api/modularui2/GTGuiTheme.java
  src/main/java/gregtech/api/modularui2/GTGuiThemes.java
  src/main/java/gregtech/api/modularui2/GTTextureIds.java
  src/main/java/gregtech/api/modularui2/GTWidgetThemes.java
  src/main/java/gregtech/common/modularui2/factory/GTBaseGuiBuilder.java
  src/main/java/gregtech/common/modularui2/panel/GTPopUpPanel.java
  src/main/java/gregtech/common/modularui2/theme/ProgressbarWidgetTheme.java
  src/main/java/gregtech/common/modularui2/util/SteamTextureRegisterer.java
  src/main/java/gregtech/common/modularui2/widget/CoverTabButton.java
  src/main/java/gregtech/common/modularui2/widget/GTProgressWidget.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoiler.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoilerBronze.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoilerLava.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoilerSolar.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoilerSolarSteel.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoilerSteel.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEBrickedBlastFurnace.java
  src/main/java/gtPlusPlus/core/common/CommonProxy.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/modularui2/GTPPGuiTextures.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/modularui2/GTPPTextureIds.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/generators/MTEAdvancedBoilerBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/generators/MTEAdvancedBoilerHV.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/generators/MTEAdvancedBoilerLV.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/generators/MTEAdvancedBoilerMV.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechAdvancedBoilers.java
  src/main/resources/assets/gregtech/textures/gui/background/popup_bronze.png
  src/main/resources/assets/gregtech/textures/gui/background/popup_primitive.png
  src/main/resources/assets/gregtech/textures/gui/background/popup_steel.png
  src/main/resources/assets/gregtech/textures/gui/button/bronze.png
  src/main/resources/assets/gregtech/textures/gui/button/bronze_pressed.png
  src/main/resources/assets/gregtech/textures/gui/button/primitive.png
  src/main/resources/assets/gregtech/textures/gui/button/primitive_pressed.png
  src/main/resources/assets/gregtech/textures/gui/button/steel.png
  src/main/resources/assets/gregtech/textures/gui/button/steel_pressed.png
  src/main/resources/assets/gregtech/textures/gui/overlay_slot/coal.png
  src/main/resources/assets/gregtech/textures/gui/progressbar/arrow_2_bronze.png
  src/main/resources/assets/gregtech/textures/gui/progressbar/arrow_bbf.png
  src/main/resources/assets/gregtech/textures/gui/progressbar/fuel.png
Labels: refactor

#4111 fix rendering issues introduced by #3973
  src/main/java/gregtech/common/render/GTRendererCasing.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAirFilterBase.java
Labels: bug fix

#4020 Refactoring GT++ 2025-03-03
  src/main/java/gregtech/api/enums/ToolDictNames.java
  src/main/java/gregtech/common/blocks/ItemMachines.java
  src/main/java/gtPlusPlus/core/fluids/GTPPFluids.java
  src/main/java/gtPlusPlus/core/handler/CompatIntermodStaging.java
  src/main/java/gtPlusPlus/core/lib/GTPPCore.java
  src/main/java/gtPlusPlus/core/util/Utils.java
  src/main/java/gtPlusPlus/core/util/minecraft/FluidUtils.java
  src/main/java/gtPlusPlus/xmod/gregtech/HandlerGT.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/enums/GregtechOrePrefixes.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/enums/GregtechToolDictNames.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/GTPPMTEFluidPipe.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/fluid/GregtechFluidHandler.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/items/MetaGeneratedGregtechTools.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechConduits.java
Labels: refactor

#4105 Some CommonBaseMetaTileEntity refactors
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CommonBaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
Labels: refactor, :construction: Testing on Zeta

#4067 Casing system
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/casing/Casings.java
  src/main/java/gregtech/api/casing/ICasing.java
  src/main/java/gregtech/common/blocks/BlockCasings1.java
  src/main/java/gregtech/common/blocks/BlockCasings10.java
  src/main/java/gregtech/common/blocks/BlockCasings11.java
  src/main/java/gregtech/common/blocks/BlockCasings12.java
  src/main/java/gregtech/common/blocks/BlockCasings2.java
  src/main/java/gregtech/common/blocks/BlockCasings3.java
  src/main/java/gregtech/common/blocks/BlockCasings4.java
  src/main/java/gregtech/common/blocks/BlockCasings5.java
  src/main/java/gregtech/common/blocks/BlockCasings6.java
  src/main/java/gregtech/common/blocks/BlockCasings8.java
  src/main/java/gregtech/common/blocks/BlockCasings9.java
  src/main/java/gregtech/common/blocks/BlockCasingsAbstract.java
  src/main/java/gregtech/common/blocks/BlockCasingsNH.java
  src/main/java/gregtech/common/blocks/BlockCyclotronCoils.java
  src/main/java/gregtech/common/blocks/BlockGlass1.java
  src/main/java/gregtech/common/blocks/BlockTintedIndustrialGlass.java
  src/main/java/gregtech/common/blocks/ItemCasings.java
  src/main/java/gregtech/common/blocks/ItemCasings1.java
  src/main/java/gregtech/common/blocks/ItemCasings10.java
  src/main/java/gregtech/common/blocks/ItemCasings11.java
  src/main/java/gregtech/common/blocks/ItemCasings12.java
  src/main/java/gregtech/common/blocks/ItemCasings2.java
  src/main/java/gregtech/common/blocks/ItemCasings3.java
  src/main/java/gregtech/common/blocks/ItemCasings4.java
  src/main/java/gregtech/common/blocks/ItemCasings5.java
  src/main/java/gregtech/common/blocks/ItemCasings6.java
  src/main/java/gregtech/common/blocks/ItemCasings8.java
  src/main/java/gregtech/common/blocks/ItemCasings9.java
  src/main/java/gregtech/common/blocks/ItemCasingsAbstract.java
  src/main/java/gregtech/common/blocks/ItemCasingsNH.java
  src/main/java/gregtech/common/blocks/ItemCyclotronCasings.java
  src/main/java/gregtech/common/blocks/ItemGlass1.java
  src/main/java/gregtech/common/blocks/ItemTintedIndustrialGlass.java
  src/main/java/kubatech/loaders/block/defc/BlockDEFCCasing.java
  src/main/java/kubatech/loaders/block/defc/ItemBlockDEFCCasing.java
  src/main/java/tectech/thing/casing/ItemCasingsBA0.java
  src/main/java/tectech/thing/casing/ItemCasingsGodforge.java
  src/main/java/tectech/thing/casing/ItemCasingsNH.java
  src/main/java/tectech/thing/casing/ItemCasingsSpacetime.java
  src/main/java/tectech/thing/casing/ItemCasingsStabilisation.java
  src/main/java/tectech/thing/casing/ItemCasingsTT.java
  src/main/java/tectech/thing/casing/ItemCasingsTimeAcceleration.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: refactor, :construction: Testing on Zeta

#4114 Enable power panel functionality for godforge modules
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/tectech/thing/gui/TecTechUITextures.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEBaseModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEExoticModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEMoltenModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEPlasmaModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTESmeltingModule.java
  src/main/resources/assets/tectech/lang/en_US.lang
  src/main/resources/assets/tectech/textures/gui/overlay_button/power_panel.png
Labels: enhancement

#4116 Fix merge conflicts
  src/main/java/gregtech/common/blocks/BlockCasings11.java
  src/main/java/gregtech/common/blocks/BlockCasings2.java
  src/main/java/gregtech/common/blocks/BlockCasings5.java
  src/main/java/gregtech/common/blocks/BlockCasingsAbstract.java
  src/main/java/gregtech/common/blocks/BlockCyclotronCoils.java
Labels: chore

#4095 Fix BlockRenderer6343 hatch face culling
  src/main/java/gregtech/common/render/GTRendererBlock.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/render/MachineBlockRenderer.java
Labels: bug fix

#4107 Fix/hazard api
  src/main/java/gregtech/api/hazards/HazardProtection.java
  src/main/java/gregtech/common/GTProxy.java
Labels: bug fix, :construction: Testing on Zeta

#4120 Remove Aluminium Oreberry fluid extraction
  src/main/java/gregtech/loaders/postload/recipes/FluidExtractorRecipes.java
Labels: bug fix

#4121 Fix EIC NPE
  src/main/java/bartworks/common/tileentities/multis/MTEElectricImplosionCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialExtractor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiAutoclave.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiLathe.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMixer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWaterPump.java
Labels: bug fix

#4113 Disable any automation of BBF
  src/main/java/gregtech/common/tileentities/machines/multi/MTEBrickedBlastFurnace.java
Labels: bug fix
