Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2025-02, with the labels that each got.

#3876 Replace Rhugnor with Radox in Compact MK4 Fusion Controller
  src/main/java/goodgenerator/loader/RecipeLoader2.java
Labels: Affects Balance

#3836 Add Pipe Swapping functionality
  src/main/java/gregtech/api/metatileentity/implementations/MTEFluid.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#3877 Change computation formula in Research Station for scanner mode
  src/main/java/tectech/thing/metaTileEntity/multi/MTEResearchStation.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: Affects Balance

#3879 EFR Tree simulator
  dependencies.gradle
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderTreeFarm.java
Labels: enhancement

#3880 Change liquid temperature
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
  src/main/java/gtPlusPlus/core/material/MaterialsElements.java
Labels: enhancement

#3713 Remove metal foils recipes to make cable
  src/main/java/gregtech/loaders/oreprocessing/ProcessingWire.java
Labels: enhancement

#3875 Add basalt to rock breaker
  src/main/java/gregtech/common/tileentities/machines/basic/MTERockBreaker.java
  src/main/java/gregtech/loaders/postload/GTPostLoad.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEIndustrialRockBreaker.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderIndustrialRockBreaker.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: new feature

#3882 Correct Steam Grinder and Squsher multi tooltips to note structures are hollow.
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMacerator.java
Labels: bug fix

#3874 Cover refactor, part 1
  src/main/java/ggfab/mte/MTELinkedInputBus.java
  src/main/java/gregtech/api/gui/modularui/GTUIInfos.java
  src/main/java/gregtech/api/interfaces/IRedstoneCircuitBlock.java
  src/main/java/gregtech/api/interfaces/covers/IControlsWorkCover.java
  src/main/java/gregtech/api/interfaces/tileentity/ICoverable.java
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
  src/main/java/gregtech/api/metatileentity/implementations/MTECable.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEFluid.java
  src/main/java/gregtech/api/util/CircuitryBehavior.java
  src/main/java/gregtech/api/util/CoverBehaviorBase.java
  src/main/java/gregtech/common/covers/CoverControlsWork.java
  src/main/java/gregtech/common/covers/CoverFacadeBase.java
  src/main/java/gregtech/common/covers/CoverInfo.java
  src/main/java/gregtech/common/covers/CoverRedstoneTransmitterExternal.java
  src/main/java/gregtech/common/items/behaviors/BehaviourCoverTool.java
  src/main/java/gtPlusPlus/core/tileentities/base/TileEntityBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTECropHarvestor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/redstone/MTERedstoneCircuitBlock.java
Labels: refactor

#3855 Include locked recipe information in WAILA tooltip
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/recipe/check/SingleRecipeCheck.java
Labels: enhancement

#3885 Fix line endings
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.03/86.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.03/87.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.03/88.png.mcmeta
Labels: chore

#3887 Update OreMixes.java
  src/main/java/gregtech/api/enums/OreMixes.java
Labels: bug fix

#3888 Remove broken ICoverable implementation
  src/main/java/gtPlusPlus/api/interfaces/ILazyCoverable.java
  src/main/java/gtPlusPlus/api/objects/minecraft/BTF_Inventory.java
  src/main/java/gtPlusPlus/core/tileentities/base/TileEntityBase.java
Labels: refactor

#3889 UV Pump and Field Generator recipe correction in CoAL
  src/main/java/goodgenerator/loader/ComponentAssemblyLineLoader.java
Labels: bug fix

#3891 Refactor/covers part 2
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/GemLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/MultipleMetalLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/SimpleMetalLoader.java
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/covers/CoverRegistry.java
  src/main/java/gregtech/api/interfaces/tileentity/ICoverable.java
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachineBronze.java
  src/main/java/gregtech/api/metatileentity/implementations/MTECable.java
  src/main/java/gregtech/api/net/GTPacketSendCoverData.java
  src/main/java/gregtech/api/util/CircuitryBehavior.java
  src/main/java/gregtech/api/util/CoverBehaviorBase.java
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gregtech/common/blocks/BlockFrameBox.java
  src/main/java/gregtech/common/covers/CoverInfo.java
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/common/items/MetaGeneratedItem02.java
  src/main/java/gregtech/common/items/MetaGeneratedItem03.java
  src/main/java/gregtech/common/items/behaviors/BehaviourCoverTool.java
  src/main/java/gregtech/common/redstonecircuits/CircuitBasicLogic.java
  src/main/java/gregtech/common/redstonecircuits/CircuitBitAnd.java
  src/main/java/gregtech/common/redstonecircuits/CircuitCombinationLock.java
  src/main/java/gregtech/common/redstonecircuits/CircuitEquals.java
  src/main/java/gregtech/common/redstonecircuits/CircuitPulser.java
  src/main/java/gregtech/common/redstonecircuits/CircuitRandomizer.java
  src/main/java/gregtech/common/redstonecircuits/CircuitRedstoneMeter.java
  src/main/java/gregtech/common/redstonecircuits/CircuitRepeater.java
  src/main/java/gregtech/common/redstonecircuits/CircuitTimer.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoiler.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTENameRemover.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPrimitiveBlastFurnace.java
  src/main/java/gregtech/loaders/misc/CoverLoader.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingCompressed.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingFoil.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingLens.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingPlate.java
  src/main/java/gtPlusPlus/core/item/base/BaseItemComponent.java
  src/main/java/gtPlusPlus/core/tileentities/base/TileEntityBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/items/MetaCustomCoverItem.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/items/MetaGeneratedGregtechItems.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/redstone/MTERedstoneCircuitBlock.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenPlates.java
  src/main/java/tectech/loader/thing/CoverLoader.java
Labels: refactor

#3892 Add `expediteRecipeCheck` to copy-paste for data sticks and data orbs
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputME.java
Labels: bug fix

#3893 Remove invalid CRIBs before use
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: bug fix

#3886 Add gunpowder centrifuging
  src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
Labels: Affects Balance

#3895 Was broke, Fix.
  src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
Labels: bug fix

#3899 Fix super tank fluid locking
  src/main/java/gregtech/common/tileentities/storage/MTEDigitalTankBase.java
Labels: bug fix

#3896 Fix tesla tower ignoring primary winding
  src/main/java/tectech/thing/metaTileEntity/multi/MTETeslaTower.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: bug fix

#3902 Parametrizer memory card enhancement
  src/main/java/tectech/thing/item/ItemParametrizerMemoryCard.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement

#3901 Introduce the Black Hole Utility Hatch
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleUtility.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement, new feature

#3894 Rebalance Americium and Europium Comb
  src/main/java/gregtech/common/items/ItemComb.java
  src/main/java/gregtech/loaders/misc/GTBeeDefinition.java
  src/main/java/gregtech/loaders/postload/recipes/ChemicalRecipes.java
Labels: Affects Balance, :construction: Testing on Zeta

#3904 Fix placing covers
  src/main/java/gregtech/api/covers/CoverRegistry.java
  src/main/java/gregtech/api/util/GTUtility.java
Labels: bug fix

#3906 Fix BHC Parallels
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
Labels: bug fix

#3909 Change a few tooltips
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEDEFusionCrafter.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEActiveTransformer.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement

#3907 Add sugar and cactus coke/charcoal to pyrolyse oven per issue #18969
  src/main/java/gtPlusPlus/recipes/CokeAndPyrolyseOven.java
  src/main/java/gtPlusPlus/xmod/railcraft/HandlerRailcraft.java
Labels: enhancement

#3905 Kill parametrizer hatch
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/tectech/loader/thing/MachineLoader.java
  src/main/java/tectech/thing/CustomItemList.java
  src/main/java/tectech/thing/gui/TecTechUITextures.java
  src/main/java/tectech/thing/item/ItemParametrizerMemoryCard.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchParam.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchParamText.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEMicrowave.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTETeslaTower.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
  src/main/resources/assets/tectech/lang/en_US.lang
  src/main/resources/assets/tectech/textures/gui/background/screen_blue_parametrizer_txt.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/parametrizer_0.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/parametrizer_1.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/parametrizer_c.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/parametrizer_id.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/parametrizer_if.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/parametrizer_s.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/parametrizer_t.png
  src/main/resources/assets/tectech/textures/gui/overlay_button/parametrizer_x.png
Labels: chore

#3897 Add `getInfoMap` method to `IGregTechDeviceInformation`
  src/main/java/gregtech/api/interfaces/metatileentity/IMetaTileEntity.java
  src/main/java/gregtech/api/interfaces/tileentity/IGregTechDeviceInformation.java
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CommonMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gtPlusPlus/core/tileentities/base/TileEntityBase.java
Labels: enhancement

#3910 Fix typo
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderTreeFarm.java
Labels: bug fix

#3912 Skip TGS recipes with null sapling
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTETreeFarm.java
Labels: bug fix

#3908 Data stick left click on crafting proxy support
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputSlave.java
Labels: enhancement

#3914 Resolver hatch shift method rewrite
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchCreativeUncertainty.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchUncertainty.java
Labels: enhancement

#3900 drop input bus compat for eec
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeEntityCrusher.java
Labels: bug fix

#3911 Fix yothatches spamming large network packets (while terminal open) when there is a lot of fluid movement
  src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/MTEYOTTAHatch.java
Labels: bug fix, :construction: Testing on Zeta

#3917 Add Waila info and Data Stick compatibility to the Cloud Computation Hatch
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchWirelessComputationInput.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: new feature

#3916 Let radio hatches be machine controllable
  src/main/java/bartworks/common/tileentities/tiered/GT_MetaTileEntity_RadioHatch.java
Labels: enhancement

#3920 Lower fluid for solidifying rounds from 18L to 16L
  src/main/java/gregtech/loaders/oreprocessing/ProcessingShaping.java
Labels: enhancement

#3919 Add a MultiAmp-only hatch identifier
  src/main/java/gregtech/api/enums/HatchElement.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialElectromagneticSeparator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchEnergyMulti.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchEnergyTunnel.java
Labels: enhancement

#3915 Improve how/when Crop Manager applies Weed-EX
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTECropHarvestor.java
Labels: enhancement

#3923 Prevent IC2 rubber logs from being rotated
  src/main/java/gregtech/common/items/behaviors/BehaviourWrench.java
Labels: bug fix

#3921 Refactor rock breaker for extensibility
  src/main/java/gregtech/common/tileentities/machines/basic/MTERockBreaker.java
  src/main/java/gregtech/loaders/postload/GTPostLoad.java
Labels: refactor

#3925 Fix excessive catalyst usage during convergence if subticking
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPlasmaForge.java
Labels: bug fix

#3933 Remove GT Empty Crate
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/common/items/IDMetaItem01.java
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingPlank.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/enums/GregtechItemList.java
Labels: chore

#3928 Fix multi smelter adding an empty output stack
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiFurnace.java
Labels: bug fix

#3930 Set extreme air intake hatch tier to ZPM
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechCustomHatches.java
Labels: bug fix

#3934 Fix HIP not voiding
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEHIPCompressor.java
Labels: bug fix

#3924 Add fake recipes for quantum computer components
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/api/recipe/maps/QuantumComputerFrontend.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/gregtech/api/util/recipe/QuantumComputerRecipeData.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchRack.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEQuantumComputer.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: new feature

#3931 Add missing super.invalidate()
  src/main/java/kubatech/tileentity/TeaStorageTile.java
Labels: bug fix

#3935 Fix an LCR collision
  src/main/java/gregtech/loaders/postload/recipes/ChemicalRecipes.java
Labels: bug fix

#3918 Improve sources of Cryotheum
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
  src/main/java/gregtech/loaders/postload/recipes/Pulverizer.java
  src/main/java/gregtech/loaders/preload/LoaderGTItemData.java
  src/main/java/gtPlusPlus/core/common/CommonProxy.java
  src/main/java/gtPlusPlus/xmod/thermalfoundation/recipe/TFGregtechRecipes.java
Labels: Affects Balance

#3932 Add item output slot to fluid heater
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
Labels: enhancement, :construction: Testing on Zeta

#3826 Refactor MTECable to update MTE without block swap
  src/main/java/gregtech/api/metatileentity/implementations/MTECable.java
  src/main/java/gregtech/api/util/GTLanguageManager.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#3929 Fix excessive catalyst usage in DTPF while using convergence and batch mode
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPlasmaForge.java
Labels: bug fix

#3883 Rock breaker
  src/main/java/gregtech/loaders/postload/GTPostLoad.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEIndustrialRockBreaker.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderIndustrialRockBreaker.java
Labels: enhancement

#3389 Remove Bio and Breakthrough circuits from the modpack
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/interfaces/IConfigurationCircuitSupport.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/items/ItemIntegratedCircuit.java
  src/main/java/gregtech/loaders/postload/PosteaTransformers.java
  src/main/java/gtPlusPlus/core/item/chemistry/AgriculturalChem.java
  src/main/java/gtPlusPlus/core/item/chemistry/CoalTar.java
  src/main/java/gtPlusPlus/core/item/chemistry/GenericChem.java
  src/main/java/gtPlusPlus/core/item/chemistry/MilledOreProcessing.java
  src/main/java/gtPlusPlus/core/item/chemistry/RocketFuels.java
  src/main/java/gtPlusPlus/core/item/circuit/GTPPIntegratedCircuitItem.java
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
  src/main/java/gtPlusPlus/core/recipe/RecipesRareEarthProcessing.java
  src/main/java/gtPlusPlus/core/recipe/common/CI.java
  src/main/java/gtPlusPlus/core/slots/SlotIntegratedCircuit.java
  src/main/java/gtPlusPlus/core/tileentities/general/TileEntityCircuitProgrammer.java
  src/main/java/gtPlusPlus/core/util/minecraft/ItemUtils.java
  src/main/java/gtPlusPlus/core/util/recipe/GTRecipeUtils.java
  src/main/java/gtPlusPlus/plugin/agrichem/BioRecipes.java
  src/main/java/gtPlusPlus/xmod/gregtech/HandlerGT.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/enums/GregtechItemList.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenFluorite.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderNuclear.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderNuclearFuelProcessing.java
  src/main/java/gtPlusPlus/xmod/ic2/recipe/RecipeIC2.java
Labels: enhancement

#3940 Fix Ztones Having craftingTank OreDict
  src/main/java/gregtech/loaders/load/GTItemIterator.java
Labels: bug fix

#3938 Fix Alchemical Furnace Polluting Without Burning
  src/mixin/java/gregtech/mixin/mixins/late/thaumcraft/MixinThaumcraftAlchemyFurnacePollution.java
Labels: bug fix

#3939 Improve state transitions for Machine Controller Cover
  src/main/java/gregtech/common/covers/CoverControlsWork.java
Labels: refactor

#3944 Fix broken cosmic neutronium plasma
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
Labels: bug fix

#3945 Add missing residue output to waterline catalyst recipes
  src/main/java/gregtech/loaders/postload/chains/PurifiedWaterRecipes.java
Labels: bug fix

#3947 Make circuit names more consistent
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/common/items/MetaGeneratedItem03.java
Labels: enhancement

#3941 Ring of Loki support for Cover Copy/Paste Tool
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/items/behaviors/BehaviourCoverTool.java
Labels: enhancement

#3937 Refactoring GT++ 2025-02-12
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/loaders/postload/chains/NaniteChain.java
  src/main/java/gtPlusPlus/core/block/ModBlocks.java
  src/main/java/gtPlusPlus/core/client/renderer/RenderMiningExplosivesPrimed.java
  src/main/java/gtPlusPlus/core/common/CommonProxy.java
  src/main/java/gtPlusPlus/core/container/ContainerFishTrap.java
  src/main/java/gtPlusPlus/core/container/ContainerPestKiller.java
  src/main/java/gtPlusPlus/core/handler/AchievementHandler.java
  src/main/java/gtPlusPlus/core/item/ModItems.java
  src/main/java/gtPlusPlus/core/item/general/ItemBufferCore.java
  src/main/java/gtPlusPlus/core/item/general/ItemMagicFeather.java
  src/main/java/gtPlusPlus/core/recipe/RecipesGeneral.java
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
  src/main/java/gtPlusPlus/core/recipe/RecipesLaserEngraver.java
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
  src/main/java/gtPlusPlus/core/tileentities/general/TileEntityFishTrap.java
  src/main/java/gtPlusPlus/recipes/CokeAndPyrolyseOven.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/enums/GregtechItemList.java
  src/main/java/gtPlusPlus/xmod/ic2/item/IC2Items.java
  src/main/java/gtPlusPlus/xmod/ic2/recipe/RecipeIC2.java
  src/main/java/gtPlusPlus/xmod/railcraft/HandlerRailcraft.java
Labels: refactor, :construction: Testing on Zeta

#3955 Fix NBT tag for "always use maximum" parallel setting
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: bug fix

#3898 Implement Capability system
  dependencies.gradle
  src/main/java/gregtech/api/interfaces/ICleanroomReceiver.java
  src/main/java/gregtech/api/interfaces/metatileentity/IMetaTileEntity.java
  src/main/java/gregtech/api/interfaces/tileentity/IGregTechTileEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CommonMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
  src/main/java/gregtech/common/capability/CleanroomReference.java
  src/main/java/gregtech/common/pollution/Pollution.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTECleanroom.java
Labels: refactor

#3957 Remove Sonictron
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/interfaces/internal/IGTMod.java
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/GTServer.java
  src/main/java/gregtech/common/items/IDMetaItem01.java
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSonictron.java
  src/main/java/gregtech/loaders/load/SonictronLoader.java
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/760.png
Labels: refactor

#3958 Fix position of chest cover gui to be to the left of the machine gui
  src/main/java/gregtech/common/covers/CoverChest.java
Labels: bug fix

#3956 Prevent crash from formatting machine items
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/blocks/ItemMachines.java
Labels: bug fix

#3959 Use capability for SoundP2P and CraftingIconProvider
  dependencies.gradle
  src/main/java/gregtech/api/interfaces/metatileentity/IMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CommonBaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEBetterJukebox.java
Labels: refactor

#3948 Refactoring GT++ 2025-02-13
  src/main/java/gregtech/api/util/SemiFluidFuelHandler.java
  src/main/java/gtPlusPlus/api/objects/data/Pair.java
  src/main/java/gtPlusPlus/api/objects/data/Quad.java
  src/main/java/gtPlusPlus/api/objects/data/Triplet.java
  src/main/java/gtPlusPlus/api/objects/data/TypeCounter.java
  src/main/java/gtPlusPlus/api/objects/minecraft/BTF_Inventory.java
  src/main/java/gtPlusPlus/api/objects/minecraft/ShapedRecipe.java
  src/main/java/gtPlusPlus/core/common/CommonProxy.java
  src/main/java/gtPlusPlus/core/common/compat/CompatIC2.java
  src/main/java/gtPlusPlus/core/common/compat/CompatThaumcraft.java
  src/main/java/gtPlusPlus/core/config/Configuration.java
  src/main/java/gtPlusPlus/core/handler/CompatHandler.java
  src/main/java/gtPlusPlus/core/handler/events/EntityDeathHandler.java
  src/main/java/gtPlusPlus/core/lib/GTPPCore.java
  src/main/java/gtPlusPlus/core/util/data/ArrayUtils.java
  src/main/java/gtPlusPlus/core/util/minecraft/ItemUtils.java
  src/main/java/gtPlusPlus/core/util/minecraft/MaterialUtils.java
  src/main/java/gtPlusPlus/core/util/minecraft/RecipeUtils.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/helpers/ChargingHelper.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/generators/MTEBoilerBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEIndustrialFishingPond.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/MTEChemicalPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenMaterialProcessing.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenOre.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenRecycling.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechSimpleWasher.java
  src/main/java/gtPlusPlus/xmod/thaumcraft/objects/ThreadAspectScanner.java
Labels: refactor, :construction: Testing on Zeta

#3964 Reduce volcanus minimum casing to 6
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvEBF.java
Labels: Affects Balance

#3960 Remove functionality to set capacity of ME hatches to max long
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
Labels: bug fix, :construction: Testing on Zeta

#3965 Waila multiblock improvement
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
Labels: enhancement

#3963 Adds new tool: Decorator's Trowel
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/common/items/IDMetaTool01.java
  src/main/java/gregtech/common/items/MetaGeneratedTool01.java
  src/main/java/gregtech/common/items/behaviors/BehaviorTrowel.java
  src/main/java/gregtech/common/tools/ToolTrowel.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingToolOther.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/items/iconsets/HANDLE_TROWEL.png
  src/main/resources/assets/gregtech/textures/items/iconsets/HANDLE_TROWEL_OVERLAY.png
  src/main/resources/assets/gregtech/textures/items/iconsets/TROWEL.png
  src/main/resources/assets/gregtech/textures/items/iconsets/TROWEL_OVERLAY.png
Labels: new feature

#3962 Register blocking mode ignore items
  dependencies.gradle
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchNonConsumableBase.java
  src/main/java/gregtech/api/util/GTModHandler.java
  src/main/java/gregtech/common/tileentities/storage/MTEDigitalChestBase.java
  src/main/java/gregtech/crossmod/ae2/AE2Compat.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingLens.java
Labels: refactor

#3966 Fix mistake with cactus coke and sugar charcoal
  src/main/java/gtPlusPlus/xmod/railcraft/HandlerRailcraft.java
Labels: bug fix

#3953 Remove recipe optimization
  src/main/java/bartworks/common/loaders/ArtificialMicaLine.java
  src/main/java/bartworks/common/loaders/BioRecipeLoader.java
  src/main/java/bartworks/common/loaders/ElectricImplosionCompressorRecipes.java
  src/main/java/bartworks/common/tileentities/multis/MTEHighTempGasCooledReactor.java
  src/main/java/bartworks/system/material/gtenhancement/PlatinumSludgeOverHaul.java
  src/main/java/bartworks/system/material/processingLoaders/AdditionalRecipes.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/CellLoader.java
  src/main/java/ggfab/api/GGFabRecipeMaps.java
  src/main/java/goodgenerator/api/recipe/GoodGeneratorRecipeMaps.java
  src/main/java/goodgenerator/loader/FuelRecipeLoader.java
  src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
  src/main/java/goodgenerator/loader/NeutronActivatorLoader.java
  src/main/java/goodgenerator/loader/RecipeLoader.java
  src/main/java/goodgenerator/loader/RecipeLoader2.java
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/api/recipe/RecipeMapBackendProperties.java
  src/main/java/gregtech/api/recipe/RecipeMapBackendPropertiesBuilder.java
  src/main/java/gregtech/api/recipe/RecipeMapBuilder.java
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/api/recipe/maps/FluidCannerBackend.java
  src/main/java/gregtech/api/recipe/maps/FuelBackend.java
  src/main/java/gregtech/api/recipe/maps/FurnaceBackend.java
  src/main/java/gregtech/api/recipe/maps/MicrowaveBackend.java
  src/main/java/gregtech/api/recipe/maps/RecyclerBackend.java
  src/main/java/gregtech/api/recipe/maps/ReplicatorBackend.java
  src/main/java/gregtech/api/util/GTForestryCompat.java
  src/main/java/gregtech/api/util/GTRecipeBuilder.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTERockBreaker.java
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingLog.java
  src/main/java/gregtech/loaders/postload/GTPostLoad.java
  src/main/java/gregtech/loaders/postload/chains/BauxiteRefineChain.java
  src/main/java/gregtech/loaders/postload/chains/PurifiedWaterRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/AutoclaveRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/BlastFurnaceRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/ChemicalBathRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/DistilleryRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/LaserEngraverRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/MixerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/TranscendentPlasmaMixerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/VacuumFreezerRecipes.java
  src/main/java/gtPlusPlus/api/recipe/GTPPRecipeMaps.java
  src/main/java/gtPlusPlus/core/item/chemistry/CoalTar.java
  src/main/java/gtPlusPlus/core/item/chemistry/GenericChem.java
  src/main/java/gtPlusPlus/core/item/chemistry/RocketFuels.java
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
  src/main/java/gtPlusPlus/core/recipe/RecipesRareEarthProcessing.java
  src/main/java/gtPlusPlus/core/recipe/RecipesSeleniumProcessing.java
  src/main/java/gtPlusPlus/plugin/agrichem/BioRecipes.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenFluorite.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechIndustrialMassFabricator.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechSolarTower.java
  src/main/java/gtPlusPlus/xmod/thermalfoundation/recipe/TFGregtechRecipes.java
  src/main/java/gtnhlanth/loader/RecipeLoader.java
  src/main/java/kubatech/loaders/DEFCRecipes.java
  src/main/java/tectech/loader/recipe/Godforge.java
  src/main/java/tectech/recipe/EyeOfHarmonyRecipeStorage.java
  src/main/java/tectech/recipe/TTRecipeAdder.java
Labels: refactor

#3968 Add Matter Manipulator to GT Mods enum
  src/main/java/gregtech/api/enums/Mods.java
Labels: chore

#3967 Refactoring GT++ 2025-02-17
  src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
  src/main/java/gtPlusPlus/GTplusplus.java
  src/main/java/gtPlusPlus/core/common/CommonProxy.java
  src/main/java/gtPlusPlus/core/fluids/GTPPFluids.java
  src/main/java/gtPlusPlus/core/handler/CompatHandler.java
  src/main/java/gtPlusPlus/core/item/ModItems.java
  src/main/java/gtPlusPlus/core/item/chemistry/AgriculturalChem.java
  src/main/java/gtPlusPlus/core/item/chemistry/CoalTar.java
  src/main/java/gtPlusPlus/core/item/chemistry/GenericChem.java
  src/main/java/gtPlusPlus/core/item/chemistry/MilledOreProcessing.java
  src/main/java/gtPlusPlus/core/item/chemistry/RecipeLoaderCoalTar.java
  src/main/java/gtPlusPlus/core/item/chemistry/RecipeLoaderGenericChem.java
  src/main/java/gtPlusPlus/core/item/chemistry/RocketFuels.java
  src/main/java/gtPlusPlus/core/item/chemistry/general/ItemGenericChemBase.java
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
  src/main/java/gtPlusPlus/core/recipe/common/CI.java
  src/main/java/gtPlusPlus/core/tileentities/machines/TileEntityAdvPooCollector.java
  src/main/java/gtPlusPlus/core/tileentities/machines/TileEntityPooCollector.java
  src/main/java/gtPlusPlus/core/tileentities/machines/TileEntityProjectTable.java
  src/main/java/gtPlusPlus/core/util/minecraft/ItemUtils.java
  src/main/java/gtPlusPlus/plugin/agrichem/BioRecipes.java
  src/main/java/gtPlusPlus/plugin/agrichem/block/AgrichemFluids.java
  src/main/java/gtPlusPlus/recipes/CokeAndPyrolyseOven.java
  src/main/java/gtPlusPlus/xmod/forestry/bees/items/FRItemRegistry.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/enums/GregtechItemList.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderChemicalSkips.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderGlueLine.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderNuclear.java
  src/main/java/gtPlusPlus/xmod/thermalfoundation/HandlerTF.java
  src/main/java/gtPlusPlus/xmod/thermalfoundation/item/TFItems.java
Labels: refactor

#3954 Add missing localization
  src/main/java/gregtech/api/enums/Dyes.java
  src/main/java/gregtech/api/items/ItemBreederCell.java
  src/main/java/gregtech/api/items/ItemRadioactiveCellIC.java
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicTank.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchOutput.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/recipe/maps/LargeBoilerFuelBackend.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/GTWaila.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColorInfinite.java
  src/main/java/gregtech/common/pollution/PollutionTooltip.java
  src/main/java/gregtech/loaders/postload/FakeRecipeLoader.java
  src/main/java/gtPlusPlus/core/item/base/BaseItemComponent.java
  src/main/java/gtPlusPlus/core/item/base/itemblock/ItemBlockBasicTile.java
  src/main/java/gtPlusPlus/core/item/base/itemblock/ItemBlockGtBlock.java
  src/main/java/gtPlusPlus/core/item/base/itemblock/ItemBlockOre.java
  src/main/java/gtPlusPlus/core/item/general/ItemAirFilter.java
  src/main/java/gtPlusPlus/core/item/wearable/armour/tinfoil/ItemArmourTinFoilHat.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/MTESteamMultiBase.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEResearchStation.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/lang/zh_CN.lang
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: refactor

#3971 Add general missing mappings handler
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/loaders/postload/MissingMappingsHandler.java
  src/main/java/gtPlusPlus/GTplusplus.java
  src/main/java/kekztech/KekzCore.java
  src/main/java/kubatech/kubatech.java
Labels: refactor

#3969 Remove autogen obsidian recipes
  src/main/java/gregtech/api/util/GTRecipeRegistrator.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingBlock.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingShaping.java
Labels: Affects Balance, bug fix

#3972 Add Dynamo Hatches to Naqfuel Refinery
  src/main/java/goodgenerator/blocks/tileEntity/MTEFuelRefineFactory.java
Labels: enhancement

#3977 if shift click on select item mui, then close after callback
  src/main/java/gregtech/common/gui/modularui/uifactory/SelectItemUIFactory.java
Labels: enhancement

#3884 Improve structure error feedback
  src/main/java/gregtech/api/enums/StructureError.java
  src/main/java/gregtech/api/gui/widgets/StructureErrorSyncer.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GTPPMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/MTESteamMultiBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialVacuumFreezer.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement, :construction: Testing on Zeta

#3976 Add missing localization-2
  src/main/java/gregtech/common/tileentities/generators/MTEMagicalEnergyAbsorber.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEIndustrialApiary.java
  src/main/java/gtPlusPlus/core/item/chemistry/general/ItemGenericChemBase.java
  src/main/java/gtPlusPlus/plugin/agrichem/item/algae/ItemAgrichemBase.java
  src/main/java/tectech/util/CommonValues.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement, :construction: Testing on Zeta

#3979 Localization 250222
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSwitchMode.java
  src/main/java/kubatech/loaders/block/kubablock/blocks/BlockTeaAcceptor.java
  src/main/java/kubatech/loaders/block/kubablock/blocks/BlockTeaStorage.java
  src/main/java/kubatech/loaders/item/items/ItemTea.java
  src/main/java/kubatech/loaders/item/items/ItemTeaIngredient.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/kubatech/lang/en_US.lang
Labels: enhancement

#3946 Unique Plasma and Molten Textures for Cosmic Neutronium
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.molten.cosmicneutronium.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.molten.cosmicneutronium.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.plasma.cosmicneutronium.png
Labels: enhancement

#3988 Allow toggling Antimatter hatch front face insertion with a screwdriver
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterOutputHatch.java
Labels: enhancement

#3990 add a config to run EEC in peaceful mode
  src/main/java/kubatech/config/Config.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeEntityCrusher.java
Labels: enhancement

#3992 fix localization of Fish Trap Tooltip
  src/main/java/gtPlusPlus/core/item/base/itemblock/ItemBlockBasicTile.java
Labels: bug fix

#3981 Fix bowl dupe
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenMultisUsingFluidInsteadOfCells.java
Labels: bug fix

#3986 Localization 250223
  src/main/java/bartworks/common/tileentities/multis/MTEWindmill.java
  src/main/java/gregtech/api/util/MultiblockTooltipBuilder.java
  src/main/java/gregtech/common/items/ItemFluidDisplay.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/GregtechMetaSpecialMultiCasings2.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTELargeRocketEngine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/MTEChemicalPlant.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/lang/zh_CN.lang
Labels: enhancement

#3993 Generate recycling recipes for nuclear gt++ mats
  src/main/java/gtPlusPlus/core/material/MaterialGenerator.java
Labels: bug fix

#3936 CoAL recipe changes
  src/main/java/goodgenerator/loader/ComponentAssemblyLineLoader.java
  src/main/java/tectech/loader/recipe/ResearchStationAssemblyLine.java
Labels: Affects Balance

#3994 Fix QFT not consuming fluids with stocking hatches
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEQuantumForceTransformer.java
Labels: bug fix

#3987 Localization of structure hints
  src/main/java/bartworks/common/tileentities/multis/MTEBioVat.java
  src/main/java/bartworks/common/tileentities/multis/MTECircuitAssemblyLine.java
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEExtremeHeatExchanger.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeEssentiaGenerator.java
  src/main/java/gregtech/api/util/MultiblockTooltipBuilder.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAssemblyLine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialElectromagneticSeparator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeChemicalReactor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiLathe.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEHIPCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitDegasser.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitOzonation.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitPhAdjustment.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitPlasmaHeater.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitUVTreatment.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEElementalDuplicator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/mega/MTEMegaAlloyBlastSmelter.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEMegaIndustrialApiary.java
  src/main/resources/assets/bartworks/lang/en_US.lang
  src/main/resources/assets/bartworks/lang/zh_CN.lang
  src/main/resources/assets/goodgenerator/lang/en_US.lang
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/kubatech/lang/en_US.lang
Labels: enhancement

#4000 Restore MTEHatchEnergy inventory size + description constructor
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchEnergy.java
Labels: chore

#4002 Distinguish wireless multiamp and wireless laser
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchWirelessMulti.java
Labels: bug fix

#3983 Rename MTE pipes to be more descriptive & cleanup bounding box
  src/main/java/bartworks/system/material/BWMetaGeneratedFrames.java
  src/main/java/bwcrossmod/tectech/tileentites/tiered/LowPowerLaser.java
  src/main/java/goodgenerator/util/CrackRecipeAdder.java
  src/main/java/gregtech/api/metatileentity/MetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTECable.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEFluidPipe.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEItemPipe.java
  src/main/java/gregtech/common/blocks/ItemMachines.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/GTPPMTEFluidPipe.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechConduits.java
  src/main/java/gtnhlanth/common/beamline/MTEBeamlinePipe.java
  src/main/java/tectech/loader/thing/MachineLoader.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchDynamoTunnel.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEBaseFactoryPipe.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeBlockData.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeBlockLaser.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeData.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeLaser.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeLaserMirror.java
  src/main/java/tectech/thing/metaTileEntity/single/MTEDebugPowerGenerator.java
Labels: refactor, :construction: Testing on Zeta

#4007 Fixed aDismantleable being Ignored in GTShapelessRecipe
  src/main/java/gregtech/api/util/GTModHandler.java
  src/main/java/gregtech/api/util/GTShapelessRecipe.java
Labels: bug fix

#3903 Refactor AL recipe system
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchDataAccess.java
  src/main/java/gregtech/api/util/AssemblyLineUtils.java
  src/main/java/gregtech/api/util/GTRecipe.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/gregtech/common/WirelessDataStore.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAssemblyLine.java
  src/main/java/tectech/mechanics/dataTransport/ALRecipeDataPacket.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchDataConnector.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchDataItemsInput.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchDataItemsOutput.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchWirelessDataItemsInput.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchWirelessDataItemsOutput.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEDataBank.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement, refactor, bug fix

#3980 Fix BW forms of capsules + refractory capsules having no container item
  src/main/java/bartworks/system/material/BWMetaGeneratedItems.java
Labels: bug fix

#3712 Godforge Rehab
  src/main/java/tectech/loader/recipe/Godforge.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEBaseModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEExoticModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEMoltenModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEPlasmaModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTESmeltingModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/upgrade/ForgeOfGodsUpgrade.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/upgrade/UpgradeStorage.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/util/GodforgeMath.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement, bug fix

#3984 Random deprecations cleanup
  src/main/java/bartworks/system/material/Werkstoff.java
  src/main/java/bartworks/util/BWTooltipReference.java
  src/main/java/bartworks/util/BWUtil.java
  src/main/java/bwcrossmod/galacticgreg/MTEVoidMinerBase.java
  src/main/java/bwcrossmod/tectech/tileentites/tiered/MTELowPowerLaserPipe.java
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/enums/GTValues.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/SoundResource.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/api/interfaces/metatileentity/IMetaTileEntityCable.java
  src/main/java/gregtech/api/metatileentity/implementations/MTECable.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatch.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchMuffler.java
  src/main/java/gregtech/api/objects/GTFluid.java
  src/main/java/gregtech/api/util/GTModHandler.java
  src/main/java/gregtech/api/util/MultiblockTooltipBuilder.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/items/IDMetaTool01.java
  src/main/java/gregtech/common/items/MetaGeneratedItem03.java
  src/main/java/gregtech/common/pollution/Pollution.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDrillerBase.java
  src/main/java/gtnhlanth/util/DescTextLocalization.java
  src/main/java/kubatech/api/Variables.java
  src/main/java/tectech/util/TTUtility.java
  src/main/java/toxiceverglades/GTPPEverglades.java
Labels: refactor
