Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2025-10, with the labels that each got.

#4617 Adds Backhand support to Infinite Spray Can (plus mouse event improvements)
  dependencies.gradle
  src/main/java/gregtech/api/interfaces/IItemBehaviour.java
  src/main/java/gregtech/api/items/MetaBaseItem.java
  src/main/java/gregtech/api/net/GTPacketInfiniteSpraycan.java
  src/main/java/gregtech/api/util/ColoredBlockContainer.java
  src/main/java/gregtech/client/GTMouseEventHandler.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/handlers/OffhandToolFunctionalityHandler.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColor.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColorInfinite.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSprayColorRemover.java
  src/main/java/gregtech/common/render/items/InfiniteSprayCanRenderer.java
  src/main/java/gregtech/crossmod/backhand/Backhand.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: New Feature, :construction: Testing on Zeta

#4945 Fix Large Boilers using fluid fuels
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeBoiler.java
Labels: Enhancement, Bug Fix, :construction: Testing on Zeta, Safe for Stable

#4969 Tweaks Void Hatch Recipe (#4967)
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
Labels: Bug Fix

#4925 MegaMultis Tooltip Unification
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaBlastFurnace.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaChemicalReactor.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaDistillTower.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaOilCracker.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaVacuumFreezer.java
  src/main/java/gregtech/api/util/tooltip/TooltipHelper.java
  src/main/java/gregtech/api/util/tooltip/TooltipTier.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/mega/MTEMegaAlloyBlastSmelter.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: Enhancement

#4975 Fix compact fusion not allowing cribs
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeFusionComputer.java
Labels: Bug Fix

#4979 Fix dynamism tablet not performing maintenance
  dependencies.gradle
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchMaintenance.java
Labels: Bug Fix, Safe for Stable

#4964 Fix Drown Downlink module not connecting on certain multiblocks
  src/main/java/goodgenerator/blocks/tileEntity/MTEPreciseAssembler.java
  src/main/java/gregtech/common/tileentities/machines/multi/drone/MTEHatchDroneDownLink.java
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTETeslaTower.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
Labels: Bug Fix, :construction: Testing on Zeta

#4988 Add sound muffling widget to Extreme Entity Crusher and Mega Apiary
  dependencies.gradle
  src/main/java/kubatech/api/implementations/KubaTechGTMultiBlockBase.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEMegaIndustrialApiary.java
Labels: Enhancement, Safe for Stable

#4989 2.8.1 Safe PR Merges Through September 30th
  dependencies.gradle
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/blocks/BlockMachines.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTECharcoalPit.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialBrewery.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchSteamBusOutput.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/mega/MTEMegaAlloyBlastSmelter.java
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: Bug Fix, Safe for Stable

#4990 Fixed crash caused by Pam's nether seeds and EIG interaction
  dependencies.gradle
  src/main/java/kubatech/tileentity/gregtech/multiblock/eigbuckets/EIGSeedBucket.java
Labels: Bug Fix

#4571 [MUI2] Port CoverAdvancedWirelessRedstoneBase and inheritors to mui2.
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/modularui2/GTGuiTextures.java
  src/main/java/gregtech/common/covers/Cover.java
  src/main/java/gregtech/common/covers/gui/CoverControlsWorkGui.java
  src/main/java/gregtech/common/covers/gui/CoverDoesWorkGui.java
  src/main/java/gregtech/common/covers/gui/CoverEUMeterGui.java
  src/main/java/gregtech/common/covers/gui/CoverFacadeBaseGui.java
  src/main/java/gregtech/common/covers/gui/CoverFluidRegulatorGui.java
  src/main/java/gregtech/common/covers/gui/CoverFluidfilterGui.java
  src/main/java/gregtech/common/covers/gui/CoverGui.java
  src/main/java/gregtech/common/covers/gui/CoverIOBaseGui.java
  src/main/java/gregtech/common/covers/gui/CoverItemFilterGui.java
  src/main/java/gregtech/common/covers/gui/CoverLiquidMeterGui.java
  src/main/java/gregtech/common/covers/gui/CoverNeedMaintenanceGui.java
  src/main/java/gregtech/common/covers/gui/CoverPlayerDetectorGui.java
  src/main/java/gregtech/common/covers/gui/CoverShutterGui.java
  src/main/java/gregtech/common/covers/gui/redstone/CoverAdvancedRedstoneReceiverBaseGui.java
  src/main/java/gregtech/common/covers/gui/redstone/CoverAdvancedRedstoneTransmitterBaseGui.java
  src/main/java/gregtech/common/covers/gui/redstone/CoverAdvancedWirelessRedstoneBaseGui.java
  src/main/java/gregtech/common/covers/gui/redstone/CoverWirelessDoesWorkDetectorGui.java
  src/main/java/gregtech/common/covers/gui/redstone/CoverWirelessFluidDetectorGui.java
  src/main/java/gregtech/common/covers/gui/redstone/CoverWirelessItemDetectorGui.java
  src/main/java/gregtech/common/covers/gui/redstone/CoverWirelessMaintenenceDetectorGui.java
  src/main/java/gregtech/common/covers/redstone/CoverAdvancedRedstoneReceiverBase.java
  src/main/java/gregtech/common/covers/redstone/CoverAdvancedRedstoneReceiverInternal.java
  src/main/java/gregtech/common/covers/redstone/CoverAdvancedRedstoneTransmitterBase.java
  src/main/java/gregtech/common/covers/redstone/CoverAdvancedWirelessRedstoneBase.java
  src/main/java/gregtech/common/covers/redstone/CoverWirelessDoesWorkDetector.java
  src/main/java/gregtech/common/covers/redstone/CoverWirelessFluidDetector.java
  src/main/java/gregtech/common/covers/redstone/CoverWirelessItemDetector.java
  src/main/java/gregtech/common/covers/redstone/CoverWirelessMaintenanceDetector.java
  src/main/java/gregtech/common/gui/mui1/cover/WirelessItemDetectorUIFactory.java
  src/main/java/gregtech/common/modularui2/factory/GTBaseGuiBuilder.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAirFilterBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/covers/gui/CoverOverflowValveGui.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: Refactor

#4548 [MUI2] Fluid Limiter GUI
  src/main/java/gregtech/common/covers/CoverFluidLimiter.java
  src/main/java/gregtech/common/covers/gui/CoverFluidLimiterGui.java
Labels: Refactor

#4993 Allow upside down IOF
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIntegratedOreFactory.java
Labels: Enhancement

#4992 Arm cover legacy removal
  src/main/java/gregtech/common/covers/CoverArm.java
  src/main/java/gregtech/common/gui/mui1/cover/ArmUIFactory.java
Labels: Refactor, Chore

#4997 Mui2 robot arm cover gui
  src/main/java/gregtech/api/modularui2/GTGuiTextures.java
  src/main/java/gregtech/common/covers/CoverArm.java
  src/main/java/gregtech/common/covers/gui/CoverArmGui.java
Labels: Chore, :construction: Testing on Zeta

#5000 Remove Unnecessary Circuits in Mega Recipes
  src/main/java/bartworks/common/loaders/recipes/Assembler.java
Labels: Chore

#5001 Suppress `PointlessArithmeticExpression` in Recipe Loaders
  src/main/java/bartworks/common/loaders/ArtificialMicaLine.java
  src/main/java/bartworks/common/loaders/BioRecipeLoader.java
  src/main/java/bartworks/common/loaders/ElectricImplosionCompressorRecipes.java
  src/main/java/bartworks/common/loaders/recipes/Assembler.java
  src/main/java/bartworks/common/loaders/recipes/AssemblyLine.java
  src/main/java/bartworks/common/loaders/recipes/Centrifuge.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblyLineRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/AutoclaveRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/BlastFurnaceRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/CannerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/ChemicalBathRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/ChemicalRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/CompressorRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/CropProcessingRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/CuttingRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/DistilleryRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/ElectrolyzerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/FermenterRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/FluidExtractorRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/FluidHeaterRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/FluidSolidifierRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/FusionReactorRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/ImplosionCompressorRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/MixerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/PlasmaForgeRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/PrinterRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/Pulverizer.java
  src/main/java/gregtech/loaders/postload/recipes/PyrolyseRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/VacuumFreezerRecipes.java
Labels: Chore

#5003 Mui2 cover chest gui
  src/main/java/gregtech/common/covers/CoverChest.java
  src/main/java/gregtech/common/covers/gui/CoverChestGui.java
  src/main/java/gregtech/common/gui/mui1/cover/ChestUIFactory.java
Labels: Chore

#5002 fix circuit imprint registration
  src/main/java/bartworks/system/material/CircuitGeneration/CircuitImprintLoader.java
Labels: Bug Fix

#5008 Power goggles ux improvements
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gregtech/common/powergoggles/DelayedGuiDisplayTicker.java
  src/main/java/gregtech/common/powergoggles/PowerGogglesCommand.java
  src/main/java/gregtech/common/powergoggles/handlers/PowerGogglesConfigHandler.java
  src/main/java/gregtech/common/powergoggles/handlers/PowerGogglesEventHandler.java
Labels: Enhancement

#5009 add Vending Machine Mod ID
  src/main/java/gregtech/api/enums/Mods.java
Labels: New Feature, :construction: Testing on Zeta

#5010 Remove CoverLegacyData from the ender fluid link cover
  src/main/java/gregtech/common/gui/mui1/cover/EnderFluidLinkUIFactory.java
  src/main/java/tectech/loader/thing/CoverLoader.java
  src/main/java/tectech/thing/cover/CoverEnderFluidLink.java
Labels: Chore

#5011 add phantom mold choice inside solidifier hatches
  src/main/java/gregtech/api/net/GTPacketSetMold.java
  src/main/java/gregtech/api/net/GTPacketTypes.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchSolidifier.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: Enhancement

#5014 Fixes 64A UHV Dynamo Hatch Recipe (S4Stable)
  src/main/java/tectech/loader/recipe/Assembler.java
Labels: Bug Fix, Safe for Stable

#5015 Fix Overclock Calculator Correction Multiplier
  src/main/java/gregtech/api/util/OverclockCalculator.java
Labels: Bug Fix

#5016 Port ender fluid link cover gui to mui2
  src/main/java/gregtech/api/modularui2/GTGuiTextures.java
  src/main/java/gregtech/common/covers/gui/CoverArmGui.java
  src/main/java/tectech/thing/cover/CoverEnderFluidLink.java
  src/main/java/tectech/thing/gui/CoverEnderFluidLinkGui.java
Labels: Chore
