Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2025-07, with the labels that each got.

#4533 Ur-Ghast, Platinum, Firestone, & Sulfur Bee Changes
  src/main/java/gregtech/common/items/CombType.java
  src/main/java/gregtech/common/items/ItemComb.java
  src/main/java/gregtech/loaders/misc/GTBeeDefinition.java
Labels: Enhancement, Bug Fix

#4534 Implement 'Batch Mode' for EEC and VM's to increase performance
  src/main/java/bwcrossmod/galacticgreg/MTEVoidMinerBase.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeEntityCrusher.java
Labels: Affects Balance

#4538 Extract commonly used methods from Commands to new parent class GTBaseCommand
  src/main/java/bartworks/common/commands/SummonRuin.java
  src/main/java/detrav/commands/DetravScannerCommand.java
  src/main/java/galacticgreg/command/AEStorageCommand.java
  src/main/java/galacticgreg/command/ProfilingCommand.java
  src/main/java/gregtech/commands/GTBaseCommand.java
  src/main/java/gregtech/common/misc/GTCommand.java
  src/main/java/gregtech/common/misc/spaceprojects/commands/SPCommand.java
  src/main/java/gregtech/common/misc/spaceprojects/commands/SPMCommand.java
  src/main/java/gtPlusPlus/core/commands/CommandUtils.java
  src/main/java/gtPlusPlus/core/util/minecraft/PlayerUtils.java
  src/main/java/gtPlusPlus/xmod/thaumcraft/commands/CommandDumpAspects.java
Labels: Refactor

#4542 Add a `Map<UUID,EntityPlayerMP>` in GTProxy
  src/main/java/gregtech/common/GTProxy.java
Labels: Refactor

#4547 Fix typo in localization key.
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAirFilterBase.java
Labels: Chore, Safe for Stable

#4546 fix incorrect glass tier registered to structurelib
  src/main/java/gregtech/api/util/GlassTier.java
Labels: Bug Fix

#4544 Added Perfect OC and Conditional Perfect OC to Tooltip builder
  src/main/java/bartworks/common/tileentities/multis/MTECircuitAssemblyLine.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaChemicalReactor.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEFuelRefineFactory.java
  src/main/java/gregtech/api/util/MultiblockTooltipBuilder.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeChemicalReactor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIsaMill.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEElementalDuplicator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEFrothFlotationCell.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEMassFabricator.java
  src/main/java/gtnhlanth/common/tileentity/MTEDigester.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: Enhancement

#4543 added a toggle for the input hatch filter
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchInput.java
  src/main/java/gregtech/api/net/GTPacketClientPreference.java
  src/main/java/gregtech/api/util/GTClientPreference.java
  src/main/java/gregtech/common/config/Client.java
Labels: Enhancement

#4553 Add Missing Units to NEI for Steam Machines
  src/main/java/gregtech/api/objects/overclockdescriber/SteamOverclockDescriber.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: Enhancement

#4554 Remove Chemical Plant Manual
  src/main/java/gtPlusPlus/core/handler/BookHandler.java
Labels: Chore

#4555 Add translation support for GT5U recipes
  src/main/java/bartworks/API/recipe/BacterialVatFrontend.java
  src/main/java/gregtech/api/objects/overclockdescriber/EUNoOverclockDescriber.java
  src/main/java/gregtech/api/objects/overclockdescriber/EUOverclockDescriber.java
  src/main/java/gregtech/api/objects/overclockdescriber/OverclockDescriber.java
  src/main/java/gregtech/api/objects/overclockdescriber/SteamOverclockDescriber.java
  src/main/java/gregtech/api/recipe/maps/TranscendentPlasmaMixerFrontend.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEMassfabricator.java
  src/main/java/gtnhlanth/common/tileentity/recipe/beamline/TargetChamberFrontend.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/lang/ru_RU.lang
Labels: Enhancement, :construction: Testing on Zeta

#4562 Add LMA Machine Type
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeMolecularAssembler.java
Labels: Enhancement

#4560 Delete usages of `SideReference$EffectiveSide`
  src/main/java/bartworks/API/SideReference.java
  src/main/java/bartworks/MainMod.java
  src/main/java/bartworks/common/loaders/BioLabLoader.java
  src/main/java/bartworks/common/loaders/FluidLoader.java
  src/main/java/bartworks/system/material/WerkstoffLoader.java
  src/main/java/bwcrossmod/BartWorksCrossmod.java
  src/main/java/bwcrossmod/galacticraft/GalacticraftProxy.java
Labels: Refactor

#4563 Removes Crib, Cribus, & Proxy Restriction on Molecular Transformer
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialMolecularTransformer.java
Labels: Bug Fix

#4559 Bump postea version
  dependencies.gradle
Labels: Chore

#4569 Expose playSound so that NEI autocrafting can toggle it
  src/main/java/gregtech/api/items/MetaGeneratedTool.java
Labels: Bug Fix

#4570 Add ability to disable play sound when crafting with tools
  src/main/java/gregtech/api/items/MetaGeneratedTool.java
  src/main/java/gregtech/common/GTProxy.java
Labels: Bug Fix, :construction: Testing on Zeta

#4566 Remove mention of wallsharing from Maintenance Hatch tooltip.
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchMaintenance.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: Chore, :construction: Testing on Zeta, Safe for Stable

#4572 Dragon Essence Altar Bee Mutation Bugfix
  src/main/java/gregtech/loaders/misc/GTBeeDefinition.java
Labels: Bug Fix

#4567 AAL NEI Data Access Hatch Bugfix
  src/main/java/ggfab/mte/MTEAdvAssLine.java
Labels: Enhancement, Bug Fix, :construction: Testing on Zeta

#3630 Add nano forge t4
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/api/util/GlassTier.java
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gregtech/common/blocks/BlockCasings13.java
  src/main/java/gregtech/common/blocks/BlockGlass1.java
  src/main/java/gregtech/common/blocks/BlockNanoForgeRenderer.java
  src/main/java/gregtech/common/render/NanoForgeRenderer.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTENanoForge.java
  src/main/java/gregtech/common/tileentities/render/TileEntityNanoForgeRenderer.java
  src/main/java/gregtech/loaders/postload/chains/NaniteChain.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/FormingPressRecipes.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
  src/main/java/tectech/loader/recipe/ResearchStationAssemblyLine.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/blocks/iconsets/NANITE_CORE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/NANITE_CORE.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/NANITE_SHIELDING_FRAME.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/NANO_FORGE_CASING_1.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/NANO_FORGE_CASING_2.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/NANO_FORGE_CASING_3.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/NANO_FORGE_CASING_4.png
  src/main/resources/assets/gregtech/textures/model/Core.png
  src/main/resources/assets/gregtech/textures/model/RING.png
  src/main/resources/assets/gregtech/textures/model/Shield.png
  src/main/resources/assets/gregtech/textures/model/nano-forge-render-core.obj
  src/main/resources/assets/gregtech/textures/model/nano-forge-render-ring-one.obj
  src/main/resources/assets/gregtech/textures/model/nano-forge-render-ring-three.obj
  src/main/resources/assets/gregtech/textures/model/nano-forge-render-ring-two.obj
  src/main/resources/assets/gregtech/textures/model/nano-forge-render-shield.obj
Labels: New Feature, :construction: Testing on Zeta

#4580 unbind power google keybind by default
  src/main/java/gregtech/common/handlers/PowerGogglesKeybindHandler.java
Labels: Enhancement

#4579 Add Cherry Plank Item (For EFR Recipes)
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/common/items/IDMetaItem02.java
  src/main/java/gregtech/common/items/MetaGeneratedItem02.java
  src/main/java/gregtech/loaders/postload/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/postload/recipes/CuttingRecipes.java
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.02/587.png
Labels: New Feature

#4545 Move tool mode switch to its own keybind
  src/main/java/gregtech/api/items/MetaGeneratedTool.java
  src/main/java/gregtech/api/net/GTPacketToolSwitchMode.java
  src/main/java/gregtech/api/net/GTPacketTypes.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSwitchMode.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/lang/ru_RU.lang
Labels: Enhancement, Bug Fix, :construction: Testing on Zeta

#4583 Split hasContainerItem and getContainerItem of MetaGeneratedTool
  src/main/java/gregtech/api/items/MetaGeneratedTool.java
Labels: Bug Fix

#4596 Improve wording of godforge power panel
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEBaseModule.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: Enhancement

#4576 Delete gt++ PlayerUtils class
  src/main/java/bartworks/common/tileentities/multis/MTEDeepEarthHeatingPump.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEWetTransformer.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/misc/WirelessChargerManager.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialElectromagneticSeparator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiCanner.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/java/gtPlusPlus/core/block/general/BlockFluidTankInfinite.java
  src/main/java/gtPlusPlus/core/block/machine/BlockCircuitProgrammer.java
  src/main/java/gtPlusPlus/core/block/machine/BlockFlaskSetter.java
  src/main/java/gtPlusPlus/core/block/machine/BlockPooCollector.java
  src/main/java/gtPlusPlus/core/block/machine/BlockProjectTable.java
  src/main/java/gtPlusPlus/core/handler/events/EnderDragonDeathHandler.java
  src/main/java/gtPlusPlus/core/handler/events/EntityDeathHandler.java
  src/main/java/gtPlusPlus/core/item/general/ItemBlueprint.java
  src/main/java/gtPlusPlus/core/item/general/ItemHealingDevice.java
  src/main/java/gtPlusPlus/core/item/tool/misc/ItemGregtechPump.java
  src/main/java/gtPlusPlus/core/tileentities/general/TileEntityCircuitProgrammer.java
  src/main/java/gtPlusPlus/core/tileentities/general/TileEntityVolumetricFlaskSetter.java
  src/main/java/gtPlusPlus/core/util/Utils.java
  src/main/java/gtPlusPlus/core/util/minecraft/PlayerUtils.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchTurbine.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchTurbineProvider.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GTPPMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/MTETransformerHiAmp.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverToggleVisual.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/automation/MTETesseractGenerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/automation/MTETesseractTerminal.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTEPollutionCreator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTEPollutionDetector.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/misc/MTEAmazonPackager.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialArcFurnace.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialCuttingMachine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialDehydrator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialPlatePress.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialWashPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIsaMill.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTESpargeTower.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvDistillationTower.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEMassFabricator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/storage/MTEPowerSubStation.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/storage/MTEEnergyBuffer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/storage/creative/MTEInfiniteItemHolder.java
  src/main/java/kubatech/FMLEventHandler.java
  src/main/java/kubatech/api/helpers/UUIDFinder.java
  src/main/java/kubatech/commands/CommandTea.java
  src/main/java/kubatech/savedata/PlayerDataManager.java
Labels: Refactor, :construction: Testing on Zeta

#4512 CAL imprinting recipes
  src/main/java/bartworks/common/net/PacketServerJoined.java
  src/main/java/bartworks/common/tileentities/multis/MTECircuitAssemblyLine.java
  src/main/java/bartworks/server/EventHandler/ServerEventHandler.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/recipes/CALImprintRecipe.java
  src/main/java/gregtech/nei/GTNEIImprintHandler.java
  src/main/java/gregtech/nei/NEIGTConfig.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: New Feature, :construction: Testing on Zeta, Safe for Stable

#4598 Fix overclock calculator speed overflow
  src/main/java/gregtech/api/util/OverclockCalculator.java
Labels: Bug Fix

#4600 Fix cribs inventory desync after ae2 last used pattern pr
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
Labels: Bug Fix

#4602 Adds recipe uses for Netherite and Prismatic combs
  src/main/java/gregtech/loaders/postload/chains/NetheriteRecipes.java
Labels: Affects Balance, :construction: Testing on Zeta

#4604 Add status of optional features in tooltip of UI buttons
  src/main/java/gregtech/api/interfaces/modularui/IControllerWithOptionalFeatures.java
  src/main/java/gregtech/api/metatileentity/implementations/gui/MTEMultiBlockBaseGui.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/util/ForgeOfGodsUI.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/lang/ru_RU.lang
Labels: Refactor

#4605 Removes Maintenance Hatch From Dyson Structure Completely
  src/main/java/gtnhintergalactic/tile/multi/TileEntityDysonSwarm.java
  src/main/resources/assets/gtnhintergalactic/lang/en_US.lang
Labels: Bug Fix, :construction: Testing on Zeta

#4606 Event handler fixes
  src/main/java/gregtech/api/modularui2/GTGuiTheme.java
  src/main/java/gtPlusPlus/core/proxy/ClientProxy.java
Labels: Bug Fix

#4612 Fix coloured machine hull textures
  src/main/java/tectech/thing/metaTileEntity/Textures.java
Labels: Bug Fix

#4614 Disable Dynamism Tablet Fortuning GT Ores
  src/main/java/bartworks/system/material/BWMetaGeneratedOres.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/blocks/BlockOres.java
  src/main/java/gtPlusPlus/core/block/base/BlockBaseOre.java
  src/main/java/gtPlusPlus/core/handler/events/EntityDeathHandler.java
Labels: Bug Fix

#4616 Add config for turning off trans metal rendering
  src/main/java/gregtech/common/config/Client.java
  src/main/java/gregtech/common/render/items/TranscendentMetalRenderer.java
  src/main/java/gregtech/common/render/items/TranscendentalMetaItemRenderer.java
Labels: New Feature

#4618 fix incorrect oredicts for RecipeLoaderAgriculturalChem
  src/main/java/gtPlusPlus/core/item/chemistry/RecipeLoaderAgriculturalChem.java
Labels: Bug Fix

#4621 Speed up forge event registration part 2
  src/main/java/gtPlusPlus/core/item/ModItems.java
Labels: Bug Fix, Performance

#4615 Tesseract Renderer
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/common/render/GTRenderUtil.java
  src/main/java/gregtech/common/render/items/WireFrameTesseractRenderer.java
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/415.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/415.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/417.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/417.png.mcmeta
Labels: Refactor, :construction: Testing on Zeta, Performance

#4613 Fixes Chemical Dye & Water Mixed Dye Recipes
  src/main/java/gregtech/loaders/oreprocessing/ProcessingDye.java
Labels: Bug Fix, :construction: Testing on Zeta

#4625 Refactor `MTECircuitAssemblyLine` Modes
  src/main/java/bartworks/common/tileentities/multis/MTECircuitAssemblyLine.java
Labels: Refactor

#4626 Adds Decompression Recipes for (Cactus & Sugar) Coal / Coke
  src/main/java/gtPlusPlus/core/recipe/RecipesGeneral.java
Labels: Enhancement

#4565 Delete a bunch of reflection
  src/main/java/bartworks/common/loaders/StaticRecipeChangeLoaders.java
  src/main/java/gregtech/api/enums/OrePrefixes.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/objects/GTUODimension.java
  src/main/java/gregtech/api/objects/GTUODimensionList.java
  src/main/java/gregtech/api/util/FishPondRecipes.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/GTUtilityClient.java
  src/main/java/gregtech/common/bees/GTBeeMutation.java
  src/main/java/gregtech/common/render/GTTextureBase.java
  src/main/java/gregtech/common/tileentities/automation/MTETypeFilter.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEIndustrialApiary.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTETeleporter.java
  src/main/java/gregtech/loaders/postload/BlockResistanceLoader.java
  src/main/java/gregtech/mixin/Mixin.java
  src/main/java/gregtech/mixin/TargetedMod.java
  src/main/java/gregtech/mixin/interfaces/accessors/AlleleEffectThrottledAccessor.java
  src/main/java/gregtech/mixin/interfaces/accessors/EntityAccessor.java
  src/main/java/gregtech/mixin/interfaces/accessors/EntityItemAccessor.java
  src/main/java/gregtech/mixin/interfaces/accessors/GuiTextFieldAccessor.java
  src/main/java/gregtech/mixin/interfaces/accessors/LanguageRegistryAccessor.java
  src/main/java/gregtech/mixin/interfaces/accessors/MutationAccessor.java
  src/main/java/gregtech/mixin/interfaces/accessors/TesselatorAccessor.java
  src/main/java/gregtech/mixin/interfaces/accessors/TreeDefinitionAccessor.java
  src/main/java/gregtech/mixin/interfaces/accessors/WeightedRandomFishableAccessor.java
  src/main/java/gtPlusPlus/GTplusplus.java
  src/main/java/gtPlusPlus/core/gui/machine/GUIVolumetricFlaskSetter.java
  src/main/java/gtPlusPlus/core/gui/widget/GuiValueField.java
  src/main/java/gtPlusPlus/core/item/bauble/FireProtectionBauble.java
  src/main/java/gtPlusPlus/core/util/minecraft/LangUtils.java
  src/main/java/gtPlusPlus/core/util/reflect/ReflectionUtils.java
  src/main/java/gtPlusPlus/plugin/fixes/vanilla/VanillaBedHeightFix.java
  src/main/java/gtPlusPlus/xmod/forestry/ForestryTreeHandler.java
  src/main/java/gtPlusPlus/xmod/forestry/bees/registry/GTPPBeeMutation.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/MetaGTProxy.java
  src/main/java/gtneioreplugin/util/GT5UndergroundFluidHelper.java
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/accessors/EntityItemMixin.java
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/accessors/EntityMixin.java
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/accessors/GuiTextFieldMixin.java
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/accessors/LanguageRegistryMixin.java
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/accessors/TessellatorMixin.java
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/accessors/WeightedRandomFishableMixin.java
  src/mixin/java/gregtech/mixin/mixins/late/forestry/AlleleEffectThrottledMixin.java
  src/mixin/java/gregtech/mixin/mixins/late/forestry/MutationMixin.java
  src/mixin/java/gregtech/mixin/mixins/late/forestry/TreeDefinitionMixin.java
Labels: Refactor, :construction: Testing on Zeta, Performance

#4639 Removes @SuppressWarnings("all")
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeMolecularAssembler.java
Labels: Chore, Safe for Stable

#4642 Remove Tier Class
  src/main/java/gregtech/api/enums/Tier.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachineWithRecipe.java
  src/main/java/gregtech/api/util/GTModHandler.java
Labels: Refactor

#4643 Refactor `MTEBasicMachineWithRecipe`
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachineWithRecipe.java
  src/main/java/gregtech/api/util/GTModHandler.java
  src/main/java/gregtech/loaders/load/MTERecipeLoader.java
Labels: Refactor

#4640 Fix Incorrect Bolt Rotation
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/crystalline/bolt.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/crystalline/bolt_OVERLAY.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/darksteel/bolt.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/energetic/bolt.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/energetic/bolt_OVERLAY.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/melodic/bolt.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/melodic/bolt_OVERLAY.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/spacetime/bolt.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/stellar/bolt.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/stellar/bolt_OVERLAY.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/vibrant/bolt.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/vibrant/bolt_OVERLAY.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/vivid/bolt.png
  src/main/resources/assets/gregtech/textures/items/materialicons/CUSTOM/vivid/bolt_OVERLAY.png
Labels: Enhancement, Safe for Stable

#4637 Adds Alternative HCl CBath Processing Path Rare Earth 2
  src/main/java/gtPlusPlus/core/recipe/RecipesRareEarthProcessing.java
Labels: Enhancement, Affects Balance

#4636 Unflip transcendent metal renderer
  src/main/java/gregtech/common/render/items/TranscendentMetalRenderer.java
  src/main/java/gregtech/common/render/items/TranscendentalMetaItemRenderer.java
Labels: Bug Fix, :construction: Testing on Zeta

#4645 Reduce allocations from Texture Building methods
  src/main/java/gregtech/api/interfaces/ITextureBuilder.java
  src/main/java/gregtech/api/render/TextureFactory.java
  src/main/java/gregtech/common/render/GTTextureBuilder.java
Labels: Refactor, Safe for Stable, Performance

#4648 Fix console error spam
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
Labels: Bug Fix

#4656 Fixes EFR Slab Conflict
  src/main/java/gregtech/loaders/postload/recipes/CuttingRecipes.java
Labels: Bug Fix

#4646 Add toggle for harvestable, but not fully grown crops.
  src/main/java/gtPlusPlus/xmod/gregtech/api/gui/GTPPUITextures.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTECropHarvestor.java
  src/main/resources/assets/miscutils/textures/gui/overlay_button/harvester_growth_toggle.png
Labels: Enhancement, :construction: Testing on Zeta

#4631 deprecate existing WIRELESS dynamo hatches
  src/main/java/gregtech/api/metatileentity/implementations/MTEWirelessDynamo.java
  src/main/java/tectech/loader/recipe/ResearchStationAssemblyLine.java
Labels: Enhancement, :construction: Testing on Zeta

#4660 Add performance as a valid label for the GHA label test
  .github/workflows/labels.yml
Labels: Chore

#4661 Add method overload for Mods.getResourcePath to avoid string array boxing
  src/main/java/bartworks/common/loaders/FluidLoader.java
  src/main/java/gregtech/api/enums/Mods.java
  src/main/java/gregtech/api/recipe/RecipeCategories.java
Labels: Performance

#4665 Fix Singleblock Distilled Water Recipe
  src/main/java/gregtech/api/recipe/RecipeMaps.java
Labels: Bug Fix, Safe for Stable

#4651 Ore overlay textures
  src/main/resources/assets/gregtech/textures/blocks/materialicons/DULL/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/DULL/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/DULL/oreSmall_OVERLAY.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/DULL/ore_OVERLAY.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/METALLIC/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/METALLIC/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/METALLIC/oreSmall_OVERLAY.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/METALLIC/ore_OVERLAY.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/ROUGH/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/ROUGH/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/ROUGH/oreSmall_OVERLAY.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/ROUGH/ore_OVERLAY.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/SHINY/ore.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/SHINY/oreSmall.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/SHINY/oreSmall_OVERLAY.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/SHINY/ore_OVERLAY.png
Labels: Enhancement, :construction: Testing on Zeta

#4668 fix(GTPP/BlockBaseOre): now render pass 1
  src/main/java/gtPlusPlus/core/block/base/BlockBaseOre.java
Labels: Bug Fix, Safe for Stable

#4609 Implement Void Hatches
  src/functionalTest/java/gregtech/test/mock/MockIVoidableMachine.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/api/interfaces/tileentity/IVoidable.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchOutput.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchOutputBus.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchVoid.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchVoidBus.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/util/VoidProtectionHelper.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchSteamBusOutput.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/MTESteamMultiBase.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/FLUID_VOID_SIGN.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/ITEM_VOID_SIGN.png
Labels: New Feature

#4674 Removes Duplicate Zirconium
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderChemicalSkips.java
  src/main/java/gtnhlanth/common/register/WerkstoffMaterialPool.java
Labels: Bug Fix

#4670 Fix(render): distinct pass for background and overlay
  src/main/java/bartworks/client/renderer/BWBlockOreRenderer.java
  src/main/java/bartworks/system/material/BWMetaGeneratedBlocks.java
  src/main/java/gregtech/api/interfaces/ITexture.java
  src/main/java/gregtech/common/render/GTCopiedBlockTextureRender.java
  src/main/java/gregtech/common/render/GTCopiedCTMBlockTexture.java
  src/main/java/gregtech/common/render/GTMultiTextureRender.java
  src/main/java/gregtech/common/render/GTRenderedTexture.java
  src/main/java/gregtech/common/render/GTRendererBlock.java
  src/main/java/gregtech/common/render/GTRendererCasing.java
  src/main/java/gregtech/common/render/GTSidedTextureRender.java
  src/main/java/gregtech/common/render/IRenderedBlock.java
  src/main/java/gtPlusPlus/core/client/renderer/CustomOreBlockRenderer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/render/MachineBlockRenderer.java
Labels: Bug Fix, :construction: Testing on Zeta, Safe for Stable, Performance

#4682 Hotfix(BlockFrameBox); getRenderBlockPass must return 0
  src/main/java/gregtech/common/blocks/BlockFrameBox.java
Labels: Bug Fix, Safe for Stable

#4684 Replace custom scientific notation methods with new GTUtility.scientificFormat()
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
Labels: Enhancement
