Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2025-08, with the labels that each got.

#4673 Add config for default value of batch mode & make it true by default
  src/main/java/gregtech/api/interfaces/modularui/IControllerWithOptionalFeatures.java
  src/main/java/gregtech/common/config/Gregtech.java
Labels: Chore

#4677 Fix plank to slab recipes for all mods currently in the pack
  src/main/java/gregtech/api/util/GTModHandler.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingPlank.java
Labels: Enhancement

#4683 Add "Insufficient Power" Message to Energy Infuser
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEnergyInfuser.java
Labels: Enhancement

#4675 Add recipes to make the GT Stones Marble, Red Granite and Black Granite
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/loaders/postload/recipes/AutoclaveRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/FluidSolidifierRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/MixerRecipes.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
Labels: Affects Balance

#4649 Add wallsharing support to drone downlink hatches and improve performance
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/drone/DroneConnection.java
  src/main/java/gregtech/common/tileentities/machines/multi/drone/MTEDroneCentre.java
  src/main/java/gregtech/common/tileentities/machines/multi/drone/MTEHatchDroneDownLink.java
Labels: Enhancement

#4692 Fix Antimatter Forge/Generator Scanner Localisation
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
  src/main/resources/assets/goodgenerator/lang/en_US.lang
Labels: Bug Fix, Safe for Stable

#4694 improve intake/reservoir hatches
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchAirIntake.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchAirIntakeAtmosphere.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchAirIntakeExtreme.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchFluidGenerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GTPPMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTELargeRocketEngine.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechCustomHatches.java
Labels: Enhancement, Chore, :construction: Testing on Zeta

#4691 Energy Infuser: Remove progress bar, we charge every tick
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEnergyInfuser.java
Labels: Enhancement, :construction: Testing on Zeta

#4688 Add the ability to disable rendering and setblock checks for Antimatter Forge (SSASS)
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: Enhancement, :construction: Testing on Zeta, Safe for Stable

#4680 Fix Energy Infuser charge items without using power
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEnergyInfuser.java
Labels: Bug Fix, :construction: Testing on Zeta

#4693 Allow energy infuser to charge stacked items
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEnergyInfuser.java
Labels: Enhancement, :construction: Testing on Zeta

#4687 refactor(ISBRH): Block rendering with a unified context class
  src/main/java/bartworks/client/renderer/BWBlockOreRenderer.java
  src/main/java/gregtech/api/enums/TextureSet.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/api/interfaces/IIconContainer.java
  src/main/java/gregtech/api/interfaces/ITexture.java
  src/main/java/gregtech/api/render/SBRContext.java
  src/main/java/gregtech/api/util/GTUtilityClient.java
  src/main/java/gregtech/common/blocks/BlockFrameBox.java
  src/main/java/gregtech/common/render/GTCopiedBlockTextureRender.java
  src/main/java/gregtech/common/render/GTCopiedCTMBlockTexture.java
  src/main/java/gregtech/common/render/GTMultiTextureRender.java
  src/main/java/gregtech/common/render/GTRenderedTexture.java
  src/main/java/gregtech/common/render/GTRendererBlock.java
  src/main/java/gregtech/common/render/GTRendererCasing.java
  src/main/java/gregtech/common/render/GTSidedTextureRender.java
  src/main/java/gregtech/common/render/IRenderedBlock.java
  src/main/java/gtPlusPlus/core/client/renderer/CustomOreBlockRenderer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/render/MachineBlockRenderer.java
Labels: Enhancement, Refactor

#4701 Fix localization for red mushroom seeds
  src/main/java/gregtech/loaders/postload/CropLoader.java
Labels: Bug Fix

#4706 hotfix(render): Gregtech Coil blocks don't render on GT5u
  src/main/java/gregtech/common/render/GTRendererBlock.java
Labels: Bug Fix, Safe for Stable

#4709 fix(render): correct inventory lighting
  src/main/java/gregtech/api/render/SBRContext.java
  src/main/java/gregtech/common/render/GTRenderedTexture.java
Labels: Bug Fix, Safe for Stable

#4695 Enhanced command suggestion of `/gt`
  src/main/java/gregtech/commands/GTBaseCommand.java
  src/main/java/gregtech/common/misc/GTCommand.java
Labels: Enhancement, :construction: Testing on Zeta, Safe for Stable

#4704 Muffler Upgrade fix. Fixes issue #20516
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/net/GTPacketBlockEvent.java
  src/main/java/gregtech/common/data/GTBlockEventTracker.java
Labels: Bug Fix

#4713 Speedup getBaseMetaTileEntity()
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
Labels: Performance

#4710 delete bartworks CrafingManager mixin
  src/main/java/bartworks/common/configs/Configuration.java
  src/main/java/bartworks/system/material/CircuitGeneration/CircuitImprintLoader.java
  src/main/java/bartworks/util/accessprioritylist/AccessPriorityList.java
  src/main/java/bartworks/util/accessprioritylist/AccessPriorityListIterators.java
  src/main/java/bartworks/util/accessprioritylist/AccessPriorityListNode.java
  src/main/java/gregtech/mixin/Mixin.java
  src/main/java/gregtech/mixin/hooks/BWCoreStaticReplacementMethodes.java
  src/mixin/java/gregtech/mixin/mixins/early/minecraft/CraftingManagerMixin.java
Labels: Refactor, :construction: Testing on Zeta

#4720 Fix: Center the Slotgroup and give the title a bit more padding ontop
  src/main/java/gtPlusPlus/core/tileentities/general/TileEntityDecayablesChest.java
Labels: Bug Fix

#4715 refactor(render): split rendering context
  src/main/java/bartworks/client/renderer/BWBlockOreRenderer.java
  src/main/java/gregtech/api/interfaces/ITexture.java
  src/main/java/gregtech/api/render/SBRContextBase.java
  src/main/java/gregtech/api/render/SBRInventoryContext.java
  src/main/java/gregtech/api/render/SBRWorldContext.java
  src/main/java/gregtech/api/util/GTUtilityClient.java
  src/main/java/gregtech/api/util/LightingHelper.java
  src/main/java/gregtech/common/render/GTCopiedBlockTextureRender.java
  src/main/java/gregtech/common/render/GTCopiedCTMBlockTexture.java
  src/main/java/gregtech/common/render/GTMultiTextureRender.java
  src/main/java/gregtech/common/render/GTRenderedTexture.java
  src/main/java/gregtech/common/render/GTRendererBlock.java
  src/main/java/gregtech/common/render/GTRendererCasing.java
  src/main/java/gregtech/common/render/GTSidedTextureRender.java
  src/main/java/gregtech/common/render/GTTextureBase.java
  src/main/java/gregtech/common/render/GTTextureBuilder.java
  src/main/java/gregtech/common/render/IRenderedBlock.java
  src/main/java/gtPlusPlus/core/client/renderer/CustomOreBlockRenderer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/render/MachineBlockRenderer.java
Labels: Refactor, :construction: Testing on Zeta, Performance

#4722 Fix Degasser Scanner Output
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitDegasser.java
Labels: Bug Fix

#4721 Add Item Pipe subchannel to Large Extractor
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialExtractor.java
Labels: Enhancement

#4723 Remove "advanced" from stocking inputs description for NEI search
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputBusME.java
Labels: Enhancement, Safe for Stable

#4700 Rocketdyne Form Fix
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GTPPMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTELargeRocketEngine.java
Labels: Bug Fix, :construction: Testing on Zeta

#4717 Solar boiler recipe changes
  src/main/java/gregtech/loaders/load/MTERecipeLoader.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
Labels: Affects Balance

#4725 Remove hard dep on Galacticraft
  dependencies.gradle
  src/main/java/gtnhintergalactic/GTNHIntergalactic.java
  src/main/java/gtnhintergalactic/block/BlockCasingGasSiphon.java
  src/main/java/gtnhintergalactic/item/ItemBlockSpaceElevatorCable.java
  src/main/java/gtnhintergalactic/item/ItemCasingSpaceElevator.java
  src/main/java/gtnhintergalactic/item/ItemCasingSpaceElevatorMotor.java
  src/main/java/gtnhintergalactic/loader/MachineLoader.java
  src/main/java/gtnhintergalactic/nei/GasSiphonRecipeHandler.java
  src/main/java/gtnhintergalactic/proxy/ClientProxy.java
  src/main/java/gtnhintergalactic/proxy/CommonProxy.java
  src/main/java/gtnhintergalactic/recipe/maps/SpaceAssemblerFrontend.java
  src/main/java/gtnhintergalactic/recipe/maps/SpaceMiningFrontend.java
  src/main/java/gtnhintergalactic/recipe/maps/SpaceResearchFrontend.java
  src/main/java/gtnhintergalactic/tile/multi/TileEntityPlanetaryGasSiphon.java
  src/main/java/gtnhintergalactic/tile/multi/elevator/TileEntitySpaceElevator.java
  src/main/java/gtnhintergalactic/tile/multi/elevatormodules/TileEntityModuleAssembler.java
  src/main/java/gtnhintergalactic/tile/multi/elevatormodules/TileEntityModuleManager.java
  src/main/java/gtnhintergalactic/tile/multi/elevatormodules/TileEntityModuleMiner.java
  src/main/java/gtnhintergalactic/tile/multi/elevatormodules/TileEntityModulePump.java
  src/main/java/gtnhintergalactic/tile/multi/elevatormodules/TileEntityModuleResearch.java
Labels: Refactor

#4727 Allows Only Water Into Crop Manager
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTECropHarvestor.java
Labels: Bug Fix

#4716 New feature: Maintenance sounds
  src/main/java/gregtech/api/enums/SoundResource.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchMaintenance.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/drone/MTEHatchDroneDownLink.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchCreativeMaintenance.java
  src/main/resources/assets/gregtech/sounds.json
  src/main/resources/assets/gregtech/sounds/MaintenanceAutoHatch.ogg
  src/main/resources/assets/gregtech/sounds/MaintenanceCreativeHatch.ogg
  src/main/resources/assets/gregtech/sounds/MaintenanceDroneDownLinkHatch.ogg
  src/main/resources/assets/gregtech/sounds/MaintenanceDuctTape.ogg
  src/main/resources/assets/gregtech/sounds/MaintenanceToolbox.ogg
Labels: Enhancement, :construction: Testing on Zeta

#4728 Fix GTPP and TT multiblock machines not registering themselves for the Drone Center's remote controll
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GTPPMultiBlockBase.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
Labels: Bug Fix

#4737 Rename Zeron-100 Reactor Shielding
  src/main/java/gtPlusPlus/core/handler/BookHandler.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTENuclearReactor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTERefinery.java
Labels: Bug Fix

#4738 Fix tooltip and structure preview for Large Molecular Assembler
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeMolecularAssembler.java
Labels: Bug Fix

#4740 Botania hard dep fix
  src/main/java/gregtech/loaders/misc/GTBeeDefinition.java
Labels: Bug Fix

#4741 Update YOTHatch description to include sticky mode addition
  src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/MTEYOTTAHatch.java
Labels: Enhancement

#4742 add recipe to allow titanium dust back into the titaniumline
  src/main/java/gregtech/loaders/postload/recipes/ChemicalRecipes.java
Labels: Affects Balance, Safe for Stable

#4743 Fix machineModeIcon logic
  src/main/java/bartworks/common/tileentities/multis/MTEDeepEarthHeatingPump.java
  src/main/java/gregtech/api/interfaces/modularui/IControllerWithOptionalFeatures.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/misc/MTEAmazonPackager.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialCuttingMachine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialDehydrator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialPlatePress.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialWashPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
Labels: Refactor, Bug Fix

#4745 Make ISBRH render ID static final and make registration explicit
  src/main/java/bartworks/client/renderer/BWBlockOreRenderer.java
  src/main/java/bartworks/client/renderer/RendererGlassBlock.java
  src/main/java/bartworks/common/loaders/FluidLoader.java
  src/main/java/bartworks/system/material/BWMetaGeneratedBlocks.java
  src/main/java/bartworks/system/material/WerkstoffLoader.java
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gregtech/common/blocks/BlockFrameBox.java
  src/main/java/gregtech/common/blocks/BlockMachines.java
  src/main/java/gregtech/common/blocks/BlockOresAbstract.java
  src/main/java/gregtech/common/render/GTRendererBlock.java
  src/main/java/gregtech/common/render/GTRendererCasing.java
  src/main/java/gtPlusPlus/core/block/base/BlockBaseOre.java
  src/main/java/gtPlusPlus/core/client/renderer/CustomOreBlockRenderer.java
  src/main/java/gtPlusPlus/core/proxy/ClientProxy.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/render/MachineBlockRenderer.java
  src/main/java/gtnhintergalactic/block/BlockSpaceElevatorCable.java
  src/main/java/gtnhintergalactic/proxy/ClientProxy.java
  src/main/java/gtnhintergalactic/render/RenderSpaceElevatorCable.java
  src/main/java/tectech/proxy/ClientProxy.java
  src/main/java/tectech/thing/block/BlockGodforgeGlass.java
  src/main/java/tectech/thing/block/BlockQuantumGlass.java
Labels: Refactor

#4734 impr(render): reuse SBR contexts instead of creating new instances
  src/main/java/bartworks/client/renderer/BWBlockOreRenderer.java
  src/main/java/gregtech/api/interfaces/ITexture.java
  src/main/java/gregtech/api/interfaces/metatileentity/IMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CommonMetaTileEntity.java
  src/main/java/gregtech/api/render/SBRContextBase.java
  src/main/java/gregtech/api/render/SBRContextHolder.java
  src/main/java/gregtech/api/render/SBRInventoryContext.java
  src/main/java/gregtech/api/render/SBRWorldContext.java
  src/main/java/gregtech/api/util/GTUtilityClient.java
  src/main/java/gregtech/common/render/GTCopiedBlockTextureRender.java
  src/main/java/gregtech/common/render/GTCopiedCTMBlockTexture.java
  src/main/java/gregtech/common/render/GTMultiTextureRender.java
  src/main/java/gregtech/common/render/GTRenderedTexture.java
  src/main/java/gregtech/common/render/GTRendererBlock.java
  src/main/java/gregtech/common/render/GTRendererCasing.java
  src/main/java/gregtech/common/render/GTSidedTextureRender.java
  src/main/java/gregtech/common/render/IRenderedBlock.java
  src/main/java/gtPlusPlus/core/client/renderer/CustomOreBlockRenderer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/render/MachineBlockRenderer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEQuantumForceTransformer.java
Labels: Refactor, Bug Fix, :construction: Testing on Zeta, Safe for Stable

#4744 Make Multi Solidifier follow shouldBeCached
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: Bug Fix

#4757 Update Netherite formula to not include the real symbol for Nihonium
  src/main/java/gregtech/api/enums/Materials.java
Labels: Bug Fix

#4759 fix AdvDebugStructureWriter rendering
  src/main/java/gregtech/common/tileentities/debug/MTEAdvDebugStructureWriter.java
Labels: Bug Fix, Safe for Stable

#4758 Standardize Machine Properties in MultiblockTooltipBuilder
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaBlastFurnace.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaChemicalReactor.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaDistillTower.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaOilCracker.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaVacuumFreezer.java
  src/main/java/gregtech/api/util/MultiblockTooltipBuilder.java
  src/main/java/gregtech/api/util/TooltipTier.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialBrewery.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialExtractor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiAutoclave.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiCanner.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiLathe.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/misc/MTEAmazonPackager.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialAlloySmelter.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialArcFurnace.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialChisel.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialCuttingMachine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialDehydrator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialExtruder.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialFluidHeater.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialMixer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialPlatePress.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialSifter.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialThermalCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialVacuumFreezer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialWashPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialWireMill.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTENuclearSaltProcessingPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEndustrialElectrolyzer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvEBF.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamAlloySmelter.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCentrifuge.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamForgeHammer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMacerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamMixer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEAutoCrafter.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/mega/MTEMegaAlloyBlastSmelter.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: Enhancement

#4773 Correct waterline T3 + T4 multiblock dimensions in tooltip
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitFlocculation.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitPhAdjustment.java
Labels: Bug Fix

#4788 Fix recipe time in netherite parts
  src/main/java/gregtech/loaders/postload/chains/NetheriteRecipes.java
Labels: Bug Fix, Safe for Stable

#4780 Fixes screw molding/extracting inconsistency
  src/main/java/gregtech/api/enums/OrePrefixes.java
Labels: Bug Fix

#4785 fix TT lines duplication, implement custom capacity method
  src/main/java/bartworks/common/tileentities/tiered/MTECompressedFluidHatch.java
  src/main/java/bartworks/common/tileentities/tiered/MTEHumongousInputHatch.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchInput.java
Labels: Enhancement, Safe for Stable

#4787 EEC Weapon Interaction + UI Improvements
  src/main/java/kubatech/api/enums/ItemList.java
  src/main/java/kubatech/api/gui/KubaTechUITextures.java
  src/main/java/kubatech/loaders/ItemLoader.java
  src/main/java/kubatech/loaders/MobHandlerLoader.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeEntityCrusher.java
  src/main/resources/assets/kubatech/lang/en_US.lang
  src/main/resources/assets/kubatech/textures/gui/overlay_button/machine_mode_eec_ritual_mode_off.png
  src/main/resources/assets/kubatech/textures/gui/overlay_button/machine_mode_eec_ritual_mode_on.png
  src/main/resources/assets/kubatech/textures/gui/overlay_button/machine_mode_eec_spawn_infernals_off.png
  src/main/resources/assets/kubatech/textures/gui/overlay_button/machine_mode_eec_spawn_infernals_on.png
  src/main/resources/assets/kubatech/textures/gui/overlay_button/machine_mode_eec_void_damaged_and_enchanted_off.png
  src/main/resources/assets/kubatech/textures/gui/overlay_button/machine_mode_eec_void_damaged_and_enchanted_on.png
  src/main/resources/assets/kubatech/textures/gui/overlay_button/machine_mode_eec_weapon_cycling_off.png
  src/main/resources/assets/kubatech/textures/gui/overlay_button/machine_mode_eec_weapon_cycling_on.png
  src/main/resources/assets/kubatech/textures/gui/overlay_button/machine_mode_eec_weapon_preservation_off.png
  src/main/resources/assets/kubatech/textures/gui/overlay_button/machine_mode_eec_weapon_preservation_on.png
  src/main/resources/assets/kubatech/textures/items/fakeitem_eecvoid.png
  src/main/resources/assets/kubatech/textures/items/fakeitem_eecvoid.png.mcmeta
Labels: Enhancement

#4771 Allow all ore variants in IsaMill
  src/main/java/gtPlusPlus/core/item/base/ore/BaseItemMilledOre.java
Labels: Enhancement

#4774 Only generate dust to fluid ABS recipes if they don't exist
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenBlastSmelterGTNH.java
Labels: Bug Fix

#4689 Fix TFFT NEI Preview
  src/main/java/kekztech/common/tileentities/MTETankTFFT.java
Labels: Bug Fix, :construction: Testing on Zeta

#4791 Add background texture to the Mega Apiary Dynamic Inventory
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEMegaIndustrialApiary.java
  src/main/resources/assets/kubatech/textures/gui/apiary_inventory_background.png
Labels: Enhancement

#4793 Re-tier ICO "coils" (heat proof/resistant casings)
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialCokeOven.java
Labels: Affects Balance, Safe for Stable

#4739 Fix a couple overlooked characters in material formulas
  src/main/java/gregtech/api/enums/Materials.java
Labels: Bug Fix

#4681 Fix Energy Infuser NEI Preview + add Input/Output Bus TT
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEnergyInfuser.java
Labels: Enhancement, Bug Fix, :construction: Testing on Zeta

#4641 Updated Block Tooltip Descriptions for Dissolution Tank, made it accept all glass types
  dependencies.gradle
  src/main/java/gtnhlanth/common/tileentity/MTEDissolutionTank.java
Labels: Bug Fix, :construction: Testing on Zeta

#4798 Add mte-centered rendering
  src/main/java/gregtech/common/GTClient.java
  src/main/java/gregtech/common/render/BaseMetaTileEntityRenderer.java
  src/main/java/gregtech/common/render/IMTERenderer.java
Labels: Enhancement

#4802 fixed bug with VM's
  src/main/java/bwcrossmod/galacticgreg/MTEVoidMinerBase.java
Labels: Bug Fix, Safe for Stable

#4806 netherite dupe fix
  src/main/java/gregtech/loaders/postload/chains/NetheriteRecipes.java
Labels: Bug Fix

#4732 rest of the deepslate changes
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/api/enums/MaterialsGTNH.java
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
Labels: Enhancement, Affects Balance

#4807 Extend Correct Domain for `GTUtility.powInt` for Bases 2 and 4
  src/main/java/gregtech/api/util/GTUtility.java
  src/test/java/gregtech/api/util/GTUtilityTest.java
Labels: Bug Fix
