Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2025-05, with the labels that each got.

#4246 Fixed tooltip for Primitive Water Pump (Dim: 3x3x5 -> 3x3x4)
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWaterPump.java
Labels: bug fix, :construction: Testing on Zeta

#4252 Remove BDM from SLAM, add MagMatter to and rebalance SSASS Magnetic Stab
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
Labels: enhancement, Affects Balance

#4258 Capitalize several fluid names
  src/main/java/gregtech/loaders/load/FuelLoader.java
Labels: bug fix

#4183 Add color-based input separation
  src/main/java/bartworks/common/tileentities/multis/MTECircuitAssemblyLine.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaOilCracker.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/api/logic/ProcessingLogic.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchInput.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchInputBus.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchMultiInput.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEOilCracker.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/MTESteamMultiBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIsaMill.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEElementalDuplicator.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_BLACK.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_BLUE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_BROWN.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_CYAN.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_GRAY.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_GREEN.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_LIGHTBLUE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_LIGHTGRAY.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_LIME.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_MAGENTA.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_ORANGE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_PINK.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_PURPLE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_RED.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_WHITE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_INPUT_HATCH_2x2_YELLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_BLACK.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_BLUE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_BROWN.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_CYAN.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_GRAY.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_GREEN.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_LIGHTBLUE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_LIGHTGRAY.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_LIME.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_MAGENTA.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_ORANGE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_PINK.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_PURPLE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_RED.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_WHITE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_PIPE_COLOR_YELLOW.png
Labels: new feature, :construction: Testing on Zeta

#4229 Improve SSASS and SLAM tooltips so they are more understandable
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
Labels: enhancement, :construction: Testing on Zeta

#4265 Remove automatic recipe generation and register MTEs
  dependencies.gradle
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/MTENanochipAssemblyComplex.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/MTENanochipAssemblyModuleBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/MTEVacuumConveyorPipe.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/hatches/MTEHatchVacuumConveyor.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/hatches/MTEHatchVacuumConveyorInput.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/hatches/MTEHatchVacuumConveyorOutput.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/util/CircuitComponent.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/util/CircuitComponentPacket.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/util/RecipeHandlers.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
Labels: enhancement

#4268 Deleting a dot at the end of a line
  src/main/java/bwcrossmod/galacticgreg/MTEVoidMinerBase.java
Labels: enhancement

#4270 Fix bad XL turbine muffler logic
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
Labels: bug fix

#4251 Let reinforced glass be harvested by silk touch
  src/main/java/gregtech/mixin/Mixin.java
  src/mixin/java/gregtech/mixin/mixins/late/ic2/MixinIc2ReinforcedGlass.java
Labels: enhancement, :construction: Testing on Zeta

#4245 Add Water pump base draw
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWaterPump.java
Labels: enhancement, :construction: Testing on Zeta

#4156 Add missing chemical formulas; Fix sub/superscript display
  src/main/java/bartworks/system/material/WerkstoffLoader.java
  src/main/java/bartworks/util/BWUtil.java
  src/main/java/goodgenerator/items/GGMaterial.java
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/api/enums/MaterialsBotania.java
  src/main/java/gregtech/api/util/CustomGlyphs.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gtPlusPlus/core/item/ModItems.java
  src/main/java/gtPlusPlus/core/material/MaterialsAlloy.java
  src/main/java/gtPlusPlus/core/util/data/StringUtils.java
  src/main/java/gtnhlanth/common/register/WerkstoffMaterialPool.java
  src/main/resources/assets/minecraft/font/glyph_sizes.bin
  src/main/resources/assets/minecraft/textures/font/unicode_page_e0.png
Labels: enhancement, bug fix

#4264 Improve Plasma Forge GetInfoData with additional catalyst usage and convergence advancements
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPlasmaForge.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#4260 Make drones not consumed again
  src/main/java/gtnhintergalactic/recipe/SpaceMiningRecipes.java
Labels: bug fix

#4255 Use StructureUtility's ofAnyWater in multiblock structures wherever relevant.
  src/main/java/gregtech/api/util/GTStructureUtility.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeIndustrialGreenhouse.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEMegaIndustrialApiary.java
Labels: refactor

#4253 Assorted Godforge fixes/enhancements
  src/main/java/tectech/loader/recipe/Godforge.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEBaseModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEMoltenModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTESmeltingModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/util/GodforgeMath.java
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: enhancement, bug fix

#4244 Fix pipe indicators
  src/main/java/gregtech/api/metatileentity/implementations/MTEFluidPipe.java
  src/main/java/gregtech/common/render/GTRenderedTexture.java
  src/main/java/gregtech/common/render/GTRendererBlock.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/GTPPMTEFluidPipe.java
Labels: refactor, bug fix

#4242 Fix rich fortune logic to be 2x instead of min 2 drops
  src/main/java/gregtech/common/blocks/TileEntityOres.java
Labels: bug fix

#4070 Add advanced network switch
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/structure/StructureWrapper.java
  src/main/java/gregtech/api/util/GTDataUtils.java
  src/main/java/tectech/loader/recipe/Assembler.java
  src/main/java/tectech/loader/recipe/AssemblyLine.java
  src/main/java/tectech/loader/thing/MachineLoader.java
  src/main/java/tectech/thing/CustomItemList.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchCreativeData.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchDataConnector.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchDataInput.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchDataOutput.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTENetworkSwitch.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTENetworkSwitchAdv.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: new feature, :construction: Testing on Zeta

#4263 Refactor Single Use Tools
  src/main/java/ggfab/GGItemList.java
  src/main/java/ggfab/GigaGramFab.java
  src/main/java/ggfab/SingleUseToolRecipeLoader.java
  src/main/java/ggfab/api/GGFabRecipeMaps.java
  src/main/java/ggfab/items/SingleUseTool.java
  src/main/java/gregtech/common/items/ItemIntegratedCircuit.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchSolidifier.java
Labels: refactor, Affects Balance

#4275 Register OOO module and fix EU/t module distribution
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/MTENanochipAssemblyComplex.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
Labels: enhancement

#4273 Don't use experimental EFR features
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderTreeFarm.java
Labels: chore

#4249 Fix centrifuges overlay on world joining
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialCentrifuge.java
Labels: bug fix

#4276 Support up to 8 energy hatches on Alloy Blast Smelter
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEAlloyBlastSmelter.java
Labels: Affects Balance

#4277 resolve access to logistic pipes UI with wrench
  src/main/java/gregtech/api/enums/Mods.java
  src/main/java/gregtech/api/items/MetaGeneratedTool.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/items/GTMetaTool.java
Labels: bug fix

#4283 MHDCSM Block
  src/main/java/bartworks/common/loaders/ElectricImplosionCompressorRecipes.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_MAGNETOHYDRODYNAMICALLYCONSTRAINEDSTARMATTER.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_MAGNETOHYDRODYNAMICALLYCONSTRAINEDSTARMATTER.png.mcmeta
Labels: new feature

#4122 Improve multiblock tooltip
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeIndustrialGreenhouse.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEMegaIndustrialApiary.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement, :construction: Testing on Zeta

#4284 Super Glue Graphene recipes buff
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderGlueLine.java
Labels: enhancement, Affects Balance

#4078 Enable MetaTileEntity with custom TileEntities (via sub-classes of BasicMachines)
  dependencies.gradle
  src/main/java/gregtech/common/blocks/BlockMachines.java
  src/test/java/gregtech/common/blocks/BlockMachinesSubclassTest.java
Labels: refactor

#4259 Reduce Excessive AL/Assembler Recipe Times, Make Regular AL Used More Often
  src/main/java/bartworks/common/loaders/recipes/AssemblyLine.java
  src/main/java/bwcrossmod/tectech/TecTechResearchLoader.java
  src/main/java/ggfab/ComponentRecipeLoader.java
  src/main/java/goodgenerator/loader/RecipeLoader.java
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
  src/main/java/kekztech/common/recipeLoaders/ResearchableAssemblyLine.java
  src/main/java/kubatech/loaders/DEFCRecipes.java
  src/main/java/tectech/loader/recipe/Assembler.java
  src/main/java/tectech/loader/recipe/AssemblyLine.java
  src/main/java/tectech/loader/recipe/ResearchStationAssemblyLine.java
Labels: Affects Balance

#4280 Add to available SIO2 reaction with Mg
  src/main/java/gregtech/loaders/postload/recipes/ChemicalRecipes.java
Labels: enhancement

#4123 Add power monitoring goggles
  src/main/java/bartworks/common/loaders/recipes/CraftingRecipes.java
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/net/GTPacketLinkPowerGoggles.java
  src/main/java/gregtech/api/net/GTPacketTypes.java
  src/main/java/gregtech/api/net/GTPacketUpdatePowerGoggles.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/handlers/PowerGogglesConfigHandler.java
  src/main/java/gregtech/common/handlers/PowerGogglesEventHandler.java
  src/main/java/gregtech/common/handlers/PowerGogglesHudHandler.java
  src/main/java/gregtech/common/handlers/PowerGogglesKeybindHandler.java
  src/main/java/gregtech/common/items/ItemPowerGoggles.java
  src/main/java/gregtech/common/items/MetaGeneratedItem03.java
  src/main/java/gregtech/common/items/gui/PowerGogglesGuiHudConfig.java
  src/main/java/gregtech/common/items/gui/PowerGogglesGuiOverlay.java
  src/main/java/gtPlusPlus/core/proxy/ClientProxy.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/items/gt.Power_Goggles.png
Labels: new feature, :construction: Testing on Zeta

#4278 Make High Density Fission Fuels Cheaper
  src/main/java/goodgenerator/loader/RecipeLoader2.java
Labels: Affects Balance

#4286 Fix crash when the Heat Exchanger causes a world save corruption after exploding with MTEHatchInputME
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputME.java
Labels: bug fix

#4239 Create ru_RU.lang
  src/main/resources/assets/bartworks/lang/ru_RU.lang
Labels: chore, :construction: Testing on Zeta

#4288 Fix basic redstone cover nullification on version migration
  src/main/java/gregtech/common/covers/CoverRedstoneTransmitterExternal.java
  src/main/java/gregtech/common/covers/CoverRedstoneTransmitterInternal.java
Labels: bug fix

#4290 THTR Tooltip and Default WA Mode
  src/main/java/bartworks/common/tileentities/multis/MTEThoriumHighTempReactor.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEWorldAccelerator.java
Labels: bug fix

#4293 Specify DTPF discount decay in its tooltip
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPlasmaForge.java
Labels: enhancement

#4261 Some NAC UI work
  src/main/java/bartworks/common/tileentities/tiered/MTERadioHatch.java
  src/main/java/gregtech/api/modularui2/GTGuiTextures.java
  src/main/java/gregtech/api/modularui2/GTGuis.java
  src/main/java/gregtech/api/modularui2/GTTextureIds.java
  src/main/java/gregtech/common/modularui2/widget/ColorGridWidget.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/MTENanochipAssemblyComplex.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/MTENanochipAssemblyModuleBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/Splitter.java
  src/main/resources/assets/gregtech/textures/gui/overlay_button/screwdriver.png
  src/main/resources/assets/gregtech/textures/gui/picture/brain.png
  src/main/resources/assets/gregtech/textures/gui/picture/electricity.png
  src/main/resources/assets/gregtech/textures/gui/progressbar/meter_mint.png
  src/main/resources/assets/gregtech/textures/gui/progressbar/meter_orange.png
  src/main/resources/assets/gregtech/textures/gui/progressbar/meter_rose.png
Labels: enhancement, new feature

#4137 Move Source/Target Chambers to RA2
  src/main/java/gtnhlanth/api/recipe/LanthanidesRecipeMaps.java
  src/main/java/gtnhlanth/common/beamline/Particle.java
  src/main/java/gtnhlanth/common/tileentity/MTESourceChamber.java
  src/main/java/gtnhlanth/common/tileentity/MTETargetChamber.java
  src/main/java/gtnhlanth/common/tileentity/recipe/beamline/BeamlineRecipeAdder2.java
  src/main/java/gtnhlanth/common/tileentity/recipe/beamline/BeamlineRecipeLoader.java
  src/main/java/gtnhlanth/common/tileentity/recipe/beamline/RecipeSC.java
  src/main/java/gtnhlanth/common/tileentity/recipe/beamline/RecipeTC.java
  src/main/java/gtnhlanth/common/tileentity/recipe/beamline/SourceChamberMetadata.java
  src/main/java/gtnhlanth/common/tileentity/recipe/beamline/TargetChamberMetadata.java
Labels: refactor, :construction: Testing on Zeta

#4298 Fix overflow when charging RF items with Wireless Charger
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTEWirelessCharger.java
Labels: bug fix

#4274 Ichorium Block/Framebox Texture Update
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_ICHORIUM.png
  src/main/resources/assets/gregtech/textures/blocks/materialicons/CUSTOM/ichorium/frameGt.png
Labels: enhancement, bug fix

#4271 Consistent Component Texture
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/17.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/21.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/25.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/29.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/33.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/37.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/41.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/45.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/49.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/49.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/50.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/50.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/51.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/595.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/595.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/596.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/596.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/618.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/618.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/619.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/619.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/638.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/638.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/639.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/639.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/648.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/648.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/649.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/649.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/658.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/658.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/659.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/659.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/678.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/678.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/679.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/679.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/688.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/688.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/689.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/689.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/698.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/698.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/699.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/699.png.mcmeta
Labels: enhancement, :construction: Testing on Zeta

#4204 Port vajra
  src/main/java/bartworks/common/loaders/recipes/CraftingRecipes.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/items/ItemTool.java
  src/main/java/gregtech/common/items/IDMetaItem02.java
  src/main/java/gregtech/common/items/MetaGeneratedItem02.java
  src/main/java/gregtech/common/items/MetaGeneratedTool01.java
  src/main/java/gregtech/common/tools/ToolVajra.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/items/gt.Tool_Vajra.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.02/585.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.02/586.png
Labels: new feature

#4272 Add sticky mode functionality to Yotta Hatch
  src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/MTEYOTTAHatch.java
  src/main/resources/assets/goodgenerator/lang/en_US.lang
Labels: enhancement, bug fix

#4287 MTEMultiblockBase MUI2
  src/main/java/bartworks/common/tileentities/multis/MTEDeepEarthHeatingPump.java
  src/main/java/bartworks/common/tileentities/multis/gui/MTEDeepEarthHeatingPumpGui.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEYottaFluidTank.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/metatileentity/implementations/gui/CheckRecipeResultAdapter.java
  src/main/java/gregtech/api/metatileentity/implementations/gui/MTEMultiBlockBaseGui.java
  src/main/java/gregtech/api/metatileentity/implementations/gui/ShutdownReasonAdapter.java
  src/main/java/gregtech/api/metatileentity/implementations/gui/StructureErrorAdapter.java
  src/main/java/gregtech/api/modularui2/GTGuiTextures.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDrillerBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialElectromagneticSeparator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiCanner.java
  src/main/java/gregtech/common/tileentities/machines/multi/gui/MTEIndustrialElectromagneticSeparatorGui.java
  src/main/java/gregtech/common/tileentities/machines/multi/gui/MTEMultiCannerGui.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/gui/MTEAmazonPackagerGui.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/gui/MTEIndustrialCuttingMachineGui.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/gui/MTEIndustrialDehydratorGui.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/gui/MTEIndustrialPlatePressGui.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/gui/MTEIndustrialWashPlantGui.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/gui/MTESteamWasherGui.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/misc/MTEAmazonPackager.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialCuttingMachine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialDehydrator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialPlatePress.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialWashPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/MTESteamWasher.java
Labels: refactor

#4178 Remove Tiny Ashes from BBF outputs
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/api/util/GTRecipe.java
Labels: enhancement

#4248 Various emissive coils fixes
  dependencies.gradle
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/interfaces/IBlockWithClientMeta.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/blocks/BlockCasings5.java
  src/main/java/gregtech/common/data/GTCoilTracker.java
Labels: bug fix

#4303 Add EoH pity
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEyeOfHarmony.java
Labels: enhancement

#4304 Remove redundant circuit for Samaric Residue Dust
  src/main/java/gtnhlanth/loader/RecipeLoader.java
Labels: enhancement

#4302 Add module structures to NAC
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/AssemblyMatrix.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/BoardProcessor.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/CuttingChamber.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/EtchingArray.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/OpticalOrganizer.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/SMDProcessor.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/Splitter.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/SuperconductorSplitter.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/WireTracer.java
Labels: enhancement

#4301 Make covers use global tick counter
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
Labels: enhancement

#4310 Nanochip assembly complex nei & waila changes
  src/main/java/gregtech/api/recipe/check/CheckRecipeResultRegistry.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/MTENanochipAssemblyComplex.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/AssemblyMatrix.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/BoardProcessor.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/CuttingChamber.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/EtchingArray.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/OpticalOrganizer.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/SMDProcessor.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/Splitter.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/SuperconductorSplitter.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/WireTracer.java
  src/main/resources/assets/gtnhlanth/lang/en_US.lang
Labels: enhancement

#4312 Fix DOB bee breed condition
  src/main/java/gregtech/loaders/misc/GTBeeDefinition.java
Labels: bug fix

#4311 Godforge fixes again
  src/main/java/tectech/loader/recipe/Godforge.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
Labels: bug fix

#4308 Fix issue where Advanced Muffler Hatch does not consume Air Filters from ME Input Bus
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaOilCracker.java
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEOilCracker.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchMufflerAdvanced.java
Labels: bug fix, :construction: Testing on Zeta

#4313 Fix godforge graviton shard world reload issue
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
Labels: bug fix

#4228 Separate Pattern Recipe Caching from Dual Inputs
  src/main/java/gregtech/api/logic/ProcessingLogic.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/objects/GTDualInputPattern.java
  src/main/java/gregtech/api/objects/GTDualInputs.java
  src/main/java/gregtech/common/tileentities/machines/IDualInputHatch.java
  src/main/java/gregtech/common/tileentities/machines/IDualInputHatchWithPattern.java
  src/main/java/gregtech/common/tileentities/machines/IDualInputInventory.java
  src/main/java/gregtech/common/tileentities/machines/IDualInputInventoryWithPattern.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputSlave.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialMultiMachine.java
Labels: refactor

#4314 Fix Cyclotron Tooltip
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTECyclotron.java
Labels: bug fix

#4307 Replace Baubles with Baubles-Expanded
  dependencies.gradle
Labels: chore

#4320 Remove my author tag
  src/main/java/gregtech/api/enums/GTValues.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchMagnet.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialBrewery.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialElectromagneticSeparator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialExtractor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiCanner.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEHIPCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEIndustrialCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTENeutroniumCompressor.java
Labels: enhancement

#4319 NAC Bug Fixes
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/MTENanochipAssemblyComplex.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/BoardProcessor.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/CuttingChamber.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/EtchingArray.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/OpticalOrganizer.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/util/CCInputConsumer.java
Labels: enhancement

#4321 Improve Un-coloured Material Block Textures
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_CAESIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_CERIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_DYSPROSIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_ERBIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_EUROPIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_GADOLINIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_HOLMIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_LANTHANUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_LUTETIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_PRASEODYMIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_PROMETHIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_SAMARIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_SCANDIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_TANTALUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_TELLURIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_THULIUM.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/BLOCK_YTTRBIUM.png
Labels: enhancement

#4309 NAC: sheet module
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/SheetSupervisor.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/util/CircuitComponent.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/util/RecipeHandlers.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
Labels: enhancement

#4325 Adapt code to MUI2 updates
  src/main/java/bartworks/common/tileentities/tiered/MTERadioHatch.java
  src/main/java/gregtech/api/metatileentity/CommonMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchMagnet.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/metatileentity/implementations/gui/MTEMultiBlockBaseGui.java
  src/main/java/gregtech/api/modularui2/GTGuis.java
  src/main/java/gregtech/api/modularui2/MetaTileEntityGuiHandler.java
  src/main/java/gregtech/common/covers/Cover.java
  src/main/java/gregtech/common/covers/gui/CoverFluidfilterGui.java
  src/main/java/gregtech/common/covers/gui/CoverGui.java
  src/main/java/gregtech/common/covers/gui/CoverItemFilterGui.java
  src/main/java/gregtech/common/items/ItemRedstoneSniffer.java
  src/main/java/gregtech/common/modularui2/factory/GTBaseGuiBuilder.java
  src/main/java/gregtech/common/modularui2/sync/GhostCircuitSyncHandler.java
  src/main/java/gregtech/common/modularui2/widget/GhostCircuitSlotWidget.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoiler.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoilerLava.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEBrickedBlastFurnace.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEHatchLensHousing.java
  src/main/java/gtPlusPlus/core/tileentities/general/TileEntityDecayablesChest.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchElementalDataOrbHolder.java
Labels: bug fix, chore

#4328 Removed a redundant block from ForgeOfGods
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/structure/ForgeOfGodsStructureString.java
Labels: bug fix, :construction: Testing on Zeta

#4330 Fix MUI2 phantom circuit slot
  src/main/java/gregtech/common/modularui2/sync/GhostCircuitSyncHandler.java
  src/main/java/gregtech/common/modularui2/widget/GhostCircuitSlotWidget.java
Labels: bug fix

#4316 Fix ME outputs trying to push when offline
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
Labels: bug fix, :construction: Testing on Zeta

#4337 Fix Industrial Apiaries Stackable Upgrades Always Using Max Values
  src/main/java/gregtech/api/util/GTApiaryUpgrade.java
Labels: bug fix

#4338 Fix T7 water quadratic parallel bonus
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitDegasser.java
Labels: bug fix

#4331 Add in recycling recipes for NewHorizonsCoreMod bars
  src/main/java/gregtech/loaders/preload/LoaderGTItemData.java
Labels: enhancement, :construction: Testing on Zeta

#4295 Create a few ru_RU.lang
  src/main/resources/assets/bartworks/lang/ru_RU.lang
  src/main/resources/assets/detravscannermod/lang/ru_RU.lang
  src/main/resources/assets/ggfab/lang/ru_RU.lang
  src/main/resources/assets/goodgenerator/lang/ru_RU.lang
  src/main/resources/assets/gregtech/lang/ru_RU.lang
  src/main/resources/assets/gtneioreplugin/lang/ru_RU.lang
  src/main/resources/assets/gtnhintergalactic/lang/ru_RU.lang
  src/main/resources/assets/gtnhlanth/lang/ru_RU.lang
  src/main/resources/assets/ic2/lang/ru_RU.lang
  src/main/resources/assets/kekztech/lang/ru_RU.lang
  src/main/resources/assets/kubatech/lang/ru_RU.lang
  src/main/resources/assets/miscutils/lang/ru_RU.lang
  src/main/resources/assets/stevescarts/lang/ru_RU.lang
  src/main/resources/assets/tectech/lang/ru_RU.lang
Labels: chore

#4335 Fix EoH NPE
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEyeOfHarmony.java
Labels: bug fix

#4339 Remove the Large Advanced Gas Turbine
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/common/blocks/BlockCasings8.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbineGasAdvanced.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
Labels: chore

#4329 NAC: VCI/VCO Item display
  src/main/java/gregtech/api/items/CircuitComponentFakeItem.java
  src/main/java/gregtech/common/tileentities/machines/multi/gui/nanochip/MTENanochipAssemblyComplexGui.java
  src/main/java/gregtech/common/tileentities/machines/multi/gui/nanochip/SplitterGui.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/hatches/MTEHatchVacuumConveyor.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/util/CircuitComponentPacket.java
Labels: enhancement

#4343 Adapting to breaking changes of GenericListSyncHandler constructor
  dependencies.gradle
  src/main/java/gregtech/api/metatileentity/implementations/gui/MTEMultiBlockBaseGui.java
  src/main/java/gregtech/common/gui/modularui/uifactory/RedstoneSnifferGuiBuilder.java
  src/main/java/gregtech/common/gui/modularui/uifactory/SnifferEntryListSyncHandler.java
  src/main/java/gregtech/common/items/ItemRedstoneSniffer.java
Labels: chore

#4332 Mega Apiary Enhancements
  src/main/java/gregtech/api/recipe/check/CheckRecipeResultRegistry.java
  src/main/java/gregtech/api/recipe/check/ResultMissingApiaryFlowers.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEMegaIndustrialApiary.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement, bug fix, :construction: Testing on Zeta

#4146 Change subtick calculator from duration to a multiplier calculator
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/gregtech/api/util/OverclockCalculator.java
  src/main/java/gregtech/api/util/ParallelHelper.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAssemblyLine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIntegratedOreFactory.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiFurnace.java
  src/test/java/gregtech/overclock/GT_OverclockCalculator_UnitTest.java
Labels: refactor

#4344 fix turbine overlay not changing when machine activity changes
  src/main/java/goodgenerator/blocks/tileEntity/MTESupercriticalFluidTurbine.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeTurbineBase.java
  src/main/java/gregtech/api/interfaces/metatileentity/IMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/common/blocks/BlockCasings4.java
  src/main/java/gregtech/common/blocks/BlockCasings8.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAirFilterBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchTurbine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialCentrifuge.java
Labels: bug fix

#4324 NAC: Cleaning up and add etching array particle mechanic
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/common/tileentities/machines/multi/gui/nanochip/MTENanochipAssemblyComplexGui.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/hatches/MTEHatchParticleSensor.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/modules/EtchingArray.java
  src/main/java/gregtech/common/tileentities/machines/multi/nanochip/util/RecipeHandlers.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/java/gtnhlanth/common/beamline/Particle.java
  src/main/java/gtnhlanth/common/tileentity/recipe/beamline/BeamlineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/items/gt.circuitcomponent/frameboxtritanium.png
  src/main/resources/assets/gtnhlanth/lang/en_US.lang
  src/main/resources/assets/gtnhlanth/textures/items/particle/Alpha.png
  src/main/resources/assets/gtnhlanth/textures/items/particle/Electron.png
  src/main/resources/assets/gtnhlanth/textures/items/particle/Neutron.png
  src/main/resources/assets/gtnhlanth/textures/items/particle/Photon.png
  src/main/resources/assets/gtnhlanth/textures/items/particle/Positron.png
  src/main/resources/assets/gtnhlanth/textures/items/particle/Proton.png
Labels: enhancement

#4349 Fix Barnarda C saplings AGAIN.
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderTreeFarm.java
Labels: bug fix

#4352 Glass tube machine recipes
  dependencies.gradle
  src/main/java/gregtech/loaders/postload/recipes/AlloySmelterRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/FluidSolidifierRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/FormingPressRecipes.java
Labels: enhancement

#4353 Minor MUI2 Cover theme update
  src/main/java/gregtech/api/modularui2/GTGuiThemes.java
  src/main/java/gregtech/common/covers/Cover.java
  src/main/java/gregtech/common/covers/gui/CoverDoesWorkGui.java
  src/main/java/gregtech/common/covers/gui/CoverFluidfilterGui.java
  src/main/java/gregtech/common/covers/gui/CoverIOBaseGui.java
  src/main/java/gregtech/common/covers/gui/CoverNeedMaintenanceGui.java
  src/main/java/gregtech/common/modularui2/sync/wrappers/WidgetResizer.java
  src/main/java/gregtech/common/modularui2/util/FlowActions.java
Labels: enhancement, refactor

#4358 Adapt to MUI2 changes
  dependencies.gradle
  src/main/java/gregtech/api/metatileentity/implementations/gui/MTEMultiBlockBaseGui.java
  src/main/java/gregtech/common/covers/gui/CoverDoesWorkGui.java
  src/main/java/gregtech/common/covers/gui/CoverFluidfilterGui.java
  src/main/java/gregtech/common/covers/gui/CoverIOBaseGui.java
  src/main/java/gregtech/common/covers/gui/CoverNeedMaintenanceGui.java
  src/main/java/gregtech/common/gui/modularui/uifactory/RedstoneSnifferGuiBuilder.java
  src/main/java/gregtech/common/modularui2/sync/wrappers/WidgetResizer.java
Labels: chore

#4357 Don't filter rocket engine hatches
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTELargeRocketEngine.java
Labels: bug fix

#4360 Fix Multis Missing Recipe Duration for Chance Based Recipes
  src/main/java/bartworks/common/tileentities/multis/MTEManualTrafo.java
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeEssentiaGenerator.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEMultiNqGenerator.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEUniversalChemicalFuelEngine.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDieselEngine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTELargeRocketEngine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTELargeSemifluidGenerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTENuclearReactor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
  src/main/java/gtnhintergalactic/tile/multi/TileEntityDysonSwarm.java
  src/main/java/kekztech/common/tileentities/MTESOFuelCellMK1.java
  src/main/java/kekztech/common/tileentities/MTESOFuelCellMK2.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEActiveTransformer.java
Labels: bug fix

#4362 Fixed GT++ Ores missing recipes
  src/main/java/gtPlusPlus/core/common/CommonProxy.java
Labels: bug fix

#4365 Fix Cover Text field text color
  src/main/java/gregtech/api/modularui2/GTGuiThemes.java
Labels: bug fix

#4367 Correct grammar on the bee overflow error
  src/main/resources/assets/kubatech/lang/en_US.lang
Labels: enhancement

#4291 Add MUI2 support for Cover Tabs
  src/main/java/gregtech/api/modularui2/CoverGuiData.java
  src/main/java/gregtech/api/modularui2/CoverUIFactory.java
  src/main/java/gregtech/api/modularui2/MetaTileEntityGuiHandler.java
  src/main/java/gregtech/common/covers/Cover.java
  src/main/java/gregtech/common/covers/CoverControlsWork.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverDoesWork.java
  src/main/java/gregtech/common/covers/CoverFacadeBase.java
  src/main/java/gregtech/common/covers/CoverFluidfilter.java
  src/main/java/gregtech/common/covers/CoverItemFilter.java
  src/main/java/gregtech/common/covers/CoverNeedMaintainance.java
  src/main/java/gregtech/common/covers/CoverPlayerDetector.java
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/java/gregtech/common/covers/CoverShutter.java
  src/main/java/gregtech/common/covers/gui/CoverControlsWorkGui.java
  src/main/java/gregtech/common/covers/gui/CoverDoesWorkGui.java
  src/main/java/gregtech/common/covers/gui/CoverFacadeBaseGui.java
  src/main/java/gregtech/common/covers/gui/CoverFluidfilterGui.java
  src/main/java/gregtech/common/covers/gui/CoverGui.java
  src/main/java/gregtech/common/covers/gui/CoverIOBaseGui.java
  src/main/java/gregtech/common/covers/gui/CoverItemFilterGui.java
  src/main/java/gregtech/common/covers/gui/CoverNeedMaintenanceGui.java
  src/main/java/gregtech/common/covers/gui/CoverPlayerDetectorGui.java
  src/main/java/gregtech/common/covers/gui/CoverShutterGui.java
  src/main/java/gregtech/common/modularui2/factory/GTBaseGuiBuilder.java
Labels: new feature, :construction: Testing on Zeta

#4366 [MUI2] Liquid Meter Cover
  src/main/java/gregtech/common/covers/CoverLiquidMeter.java
  src/main/java/gregtech/common/covers/gui/CoverGui.java
  src/main/java/gregtech/common/covers/gui/CoverLiquidMeterGui.java
  src/main/java/gregtech/common/gui/mui1/cover/LiquidMeterUIFactory.java
Labels: refactor

#4356 Mte base gui cleanup
  src/main/java/gregtech/api/enums/VoidingMode.java
  src/main/java/gregtech/api/interfaces/modularui/IControllerWithOptionalFeatures.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/metatileentity/implementations/gui/MTEMultiBlockBaseGui.java
  src/main/java/gregtech/api/modularui2/GTGuiTextures.java
  src/main/java/gregtech/api/modularui2/GTTextureIds.java
  src/main/java/gregtech/api/modularui2/GTWidgetThemes.java
  src/main/java/gregtech/common/modularui2/sync/Predicates.java
Labels: refactor, :construction: Testing on Zeta

#4347 Fix some bugs with the Machine Controller cover
  src/main/java/gregtech/common/covers/CoverControlsWork.java
  src/main/java/gregtech/common/covers/gui/CoverControlsWorkGui.java
Labels: bug fix

#4373 Fix enderium skip
  src/main/java/gregtech/loaders/postload/recipes/MixerRecipes.java
Labels: enhancement

#4267 add Data Orb item copying functionality for Research Station Scanner
  src/main/java/tectech/thing/metaTileEntity/multi/MTEResearchStation.java
Labels: enhancement

#4195 PR to fix void protection for multi smelters
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiFurnace.java
Labels: bug fix, :construction: Testing on Zeta

#4369 [MUI2] Fluid Regulator Cover
  src/main/java/gregtech/common/covers/CoverFluidRegulator.java
  src/main/java/gregtech/common/covers/gui/CoverFluidRegulatorGui.java
  src/main/java/gregtech/common/covers/gui/CoverGui.java
Labels: refactor, :construction: Testing on Zeta

#4374 [MUI2] Neutron Sensor Hatch
  src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/MTENeutronSensor.java
Labels: refactor

#4215 Remove Bartworks EBF hack
  dependencies.gradle
  src/main/java/bartworks/MainMod.java
  src/main/java/bartworks/common/loaders/StaticRecipeChangeLoaders.java
  src/main/java/bartworks/system/material/WerkstoffLoader.java
  src/main/java/bartworks/system/material/werkstoff_loaders/recipe/DustLoader.java
  src/main/java/bwcrossmod/galacticgreg/MTEVoidMinerBase.java
  src/main/java/bwcrossmod/galacticgreg/VoidMinerUtility.java
  src/main/java/goodgenerator/items/GGMaterial.java
  src/main/java/goodgenerator/loader/NaquadahReworkRecipeLoader.java
  src/main/java/goodgenerator/loader/RecipeLoader.java
  src/main/java/goodgenerator/util/CrackRecipeAdder.java
  src/main/java/gregtech/api/util/BlastFurnaceGasStat.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/gregtech/loaders/postload/recipes/BlastFurnaceRecipes.java
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
  src/main/java/gtnhlanth/loader/RecipeLoader.java
Labels: refactor, Affects Balance

#4236 Fix Crib voiding their inventory
  src/main/java/gregtech/common/config/Gregtech.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputSlave.java
Labels: bug fix

#4368 [MUI2] Overflow Valve Cover
  src/main/java/gregtech/common/covers/gui/CoverGui.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/covers/gui/CoverOverflowValveGui.java
Labels: refactor

#4379 Fix GT++ normal pipes not being craftable
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechConduits.java
Labels: bug fix

#4372 [MUI2] EU Meter Cover
  src/main/java/gregtech/api/modularui2/GTGuiTextures.java
  src/main/java/gregtech/common/covers/CoverEUMeter.java
  src/main/java/gregtech/common/covers/CoverLiquidMeter.java
  src/main/java/gregtech/common/covers/Invertable.java
  src/main/java/gregtech/common/covers/gui/CoverEUMeterGui.java
  src/main/java/gregtech/common/covers/gui/CoverLiquidMeterGui.java
  src/main/java/gregtech/common/covers/gui/Rows.java
Labels: refactor

#4381 Make some controllers use unique front overlay textures
  src/main/java/goodgenerator/blocks/tileEntity/MTEComponentAssemblyLine.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIntegratedOreFactory.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBaryonicPerfection.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_COMPONENT_ASSEMBLY_LINE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_COMPONENT_ASSEMBLY_LINE_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_COMPONENT_ASSEMBLY_LINE_ACTIVE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_COMPONENT_ASSEMBLY_LINE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_ORE_FACTORY.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_ORE_FACTORY_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_ORE_FACTORY_ACTIVE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_ORE_FACTORY_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_PURIFICATION_PLANT.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_PURIFICATION_PLANT_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_PURIFICATION_PLANT_ACTIVE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_PURIFICATION_PLANT_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_WATER_T8.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_WATER_T8_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_WATER_T8_ACTIVE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_WATER_T8_GLOW.png
Labels: refactor, :construction: Testing on Zeta

#4387 Remove Large Essentia Generator
  src/main/java/goodgenerator/blocks/regularBlock/BlockTEContainer.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEEssentiaHatch.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeEssentiaGenerator.java
  src/main/java/goodgenerator/crossmod/thaumcraft/LargeEssentiaEnergyData.java
  src/main/java/goodgenerator/crossmod/thaumcraft/Research.java
  src/main/java/goodgenerator/loader/Loaders.java
  src/main/java/goodgenerator/util/ItemRefer.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/resources/assets/goodgenerator/lang/en_US.lang
  src/main/resources/assets/goodgenerator/lang/ru_RU.lang
  src/main/resources/assets/goodgenerator/lang/zh_CN.lang
Labels: chore

#4389 Fix antimatter glass failing to apply umv glass oredict
  src/main/java/bartworks/MainMod.java
Labels: bug fix

#4397 Fix fuel values for rocket fuel
  src/main/java/gtPlusPlus/core/item/chemistry/RecipeLoaderRocketFuels.java
Labels: bug fix

#4395 Show YottaHatch online status in waila
  src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/MTEYOTTAHatch.java
Labels: enhancement

#4396 Make Lens Indicator in T6 Water Plant optional
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitUVTreatment.java
Labels: enhancement

#4404 fix voltage not using gt formatter for battery buffers
  src/main/java/gregtech/api/items/MetaBaseItem.java
Labels: enhancement

#4403 Seperate ME busses and hatches by color
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
Labels: enhancement, :construction: Testing on Zeta

#4408 Allowed Electric Implosion Compressor to have Hatches on the top.
  src/main/java/bartworks/common/tileentities/multis/MTEElectricImplosionCompressor.java
Labels: enhancement, :construction: Testing on Zeta

#4411 More consistent Batch Mode Activation with WireCutter
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEComponentAssemblyLine.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEFuelRefineFactory.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEPreciseAssembler.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDistillationTower.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEImplosionCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialElectromagneticSeparator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeChemicalReactor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeFluidExtractor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiAutoclave.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiFurnace.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiLathe.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTENanoForge.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPlasmaForge.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPyrolyseOven.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEQuantumForceTransformer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/mega/MTEMegaAlloyBlastSmelter.java
Labels: enhancement

#4412 Add LFE-controllerFaces
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeFluidExtractor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/textures/TexturesGtBlock.java
  src/main/resources/assets/miscutils/textures/blocks/iconsets/controllerFaces/largeFluidExtractor.mcmeta
  src/main/resources/assets/miscutils/textures/blocks/iconsets/controllerFaces/largeFluidExtractor.png
  src/main/resources/assets/miscutils/textures/blocks/iconsets/controllerFaces/largeFluidExtractorActive.png
  src/main/resources/assets/miscutils/textures/blocks/iconsets/controllerFaces/largeFluidExtractorActive.png.mcmeta
  src/main/resources/assets/miscutils/textures/blocks/iconsets/controllerFaces/largeFluidExtractorActiveGlow.png
  src/main/resources/assets/miscutils/textures/blocks/iconsets/controllerFaces/largeFluidExtractorActiveGlow.png.mcmeta
  src/main/resources/assets/miscutils/textures/blocks/iconsets/controllerFaces/largeFluidExtractorGlow.png
  src/main/resources/assets/miscutils/textures/blocks/iconsets/controllerFaces/largeFluidExtractorGlow.png.mcmeta
Labels: enhancement

#4409 Fix Infuser not Charging with All Available Amps
  src/main/java/tectech/TecTech.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEnergyInfuser.java
Labels: bug fix

#4376 [MUI2] Microwave Energy Transmitter
  src/main/java/gregtech/api/modularui2/GTGuiTextures.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEMicrowaveEnergyTransmitter.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: refactor

#4292 Add a steam pressure gauge to single and multiblocks
  src/main/java/gregtech/api/gui/modularui/CircularGaugeDrawable.java
  src/main/java/gregtech/api/gui/modularui/GTUITextures.java
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/MTESteamMultiBase.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/gui/background/steam_dial.png
  src/main/resources/assets/gregtech/textures/gui/background/steam_dial_steel.png
Labels: enhancement, :construction: Testing on Zeta

#4426 Minor strings fix
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputME.java
Labels: enhancement

#4388 Fix some fluids having the wrong tooltips
  src/main/java/gregtech/common/items/ItemFluidDisplay.java
Labels: bug fix

#4423 fix crash on invalid pattern replace
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
Labels: bug fix

#4394 Fix GT++ pipes not having solidifier recipes
  src/main/java/gtPlusPlus/core/recipe/RecipesGeneral.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechConduits.java
Labels: enhancement, bug fix, :construction: Testing on Zeta

#4393 Fix XL turbines blocking fluid input after switching fitting mode
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
Labels: bug fix

#4392 Fix TT multi hatch adders not setting interface terminal name
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
Labels: bug fix

#4383 Fix tool container item issues
  src/main/java/gregtech/api/items/MetaGeneratedTool.java
Labels: bug fix
