Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2025-01, with the labels that each got.

#3740 fix ptfe melting temp
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
Labels: bug fix

#3738 Cache last recipe done by Target Chamber
  src/main/java/gtnhlanth/common/tileentity/MTETargetChamber.java
Labels: enhancement

#3741 Cap waterline T3 success to avoid cheese
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitFlocculation.java
Labels: bug fix

#3743 Material chem balance fixes
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
Labels: bug fix

#3742 Reduce CAL recipe time
  src/main/java/bartworks/common/loaders/recipes/AssemblyLine.java
Labels: Affects Balance

#3709 Don't ignore Tinker's Construct blocks in ore registration.
  src/main/java/gregtech/common/GTProxy.java
Labels: bug fix, :construction: Testing on Zeta

#3744 fix chem formulas for a few lanth materials
  src/main/java/gtnhlanth/common/register/WerkstoffMaterialPool.java
Labels: bug fix

#3745 No Free Computation
  src/main/java/tectech/thing/metaTileEntity/multi/MTEQuantumComputer.java
Labels: bug fix

#3746 Update structure size tooltips for Large Electric Compressor / HIP
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEHIPCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEIndustrialCompressor.java
Labels: bug fix

#3747 fix Tooltip of Molecular Transformer
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialMolecularTransformer.java
Labels: bug fix

#3724 Simplified Multiblock Lathe
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiLathe.java
Labels: Affects Balance, :construction: Testing on Zeta

#3749 Fix AL output amount
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAssemblyLine.java
Labels: bug fix

#3748 some Multiblock Tooltip fixes
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaChemicalReactor.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaOilCracker.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEComponentAssemblyLine.java
  src/main/java/goodgenerator/blocks/tileEntity/MTECoolantTower.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEFuelRefineFactory.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEMultiNqGenerator.java
  src/main/java/goodgenerator/blocks/tileEntity/MTENeutronActivator.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEUniversalChemicalFuelEngine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIntegratedOreFactory.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTETranscendentPlasmaMixer.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEWormholeGenerator.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationPlant.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBaryonicPerfection.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitClarifier.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitDegasser.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitFlocculation.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitOzonation.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitPhAdjustment.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitPlasmaHeater.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitUVTreatment.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvDistillationTower.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/mega/MTEMegaAlloyBlastSmelter.java
  src/main/java/gtnhlanth/common/tileentity/MTEDigester.java
  src/main/java/gtnhlanth/common/tileentity/MTEDissolutionTank.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEDataBank.java
Labels: bug fix, :construction: Testing on Zeta

#3698 Clean up some deprecation usages
  src/main/java/bartworks/common/tileentities/multis/MTEBioVat.java
  src/main/java/bartworks/common/tileentities/multis/MTECircuitAssemblyLine.java
  src/main/java/bartworks/common/tileentities/multis/MTEElectricImplosionCompressor.java
  src/main/java/bartworks/common/tileentities/multis/MTEHighTempGasCooledReactor.java
  src/main/java/bartworks/common/tileentities/multis/MTELESU.java
  src/main/java/bartworks/common/tileentities/multis/MTEManualTrafo.java
  src/main/java/bartworks/common/tileentities/multis/MTEThoriumHighTempReactor.java
  src/main/java/bartworks/common/tileentities/multis/MTEWindmill.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaBlastFurnace.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaChemicalReactor.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaDistillTower.java
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaOilCracker.java
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEComponentAssemblyLine.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEFuelRefineFactory.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeEssentiaSmeltery.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEUniversalChemicalFuelEngine.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEEnhancedMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDrillerBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialElectromagneticSeparator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeChemicalReactor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeFluidExtractor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEResearchCompleter.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GTPPMultiBlockBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/mega/MTEMegaAlloyBlastSmelter.java
  src/main/java/gtnhlanth/common/tileentity/MTELINAC.java
  src/main/java/gtnhlanth/common/tileentity/MTESourceChamber.java
  src/main/java/gtnhlanth/common/tileentity/MTESynchrotron.java
  src/main/java/gtnhlanth/common/tileentity/MTETargetChamber.java
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
  src/main/java/kekztech/common/tileentities/MTETankTFFT.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeEntityCrusher.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEMicrowave.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: refactor, :construction: Testing on Zeta

#3750 Make degasser not form without control hatch
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitDegasser.java
Labels: bug fix

#3617 Enhance Wireless Detectors with toggle-able sided redstone manipulation
  src/main/java/gregtech/common/covers/redstone/CoverWirelessDoesWorkDetector.java
  src/main/java/gregtech/common/covers/redstone/CoverWirelessFluidDetector.java
  src/main/java/gregtech/common/covers/redstone/CoverWirelessItemDetector.java
  src/main/java/gregtech/common/covers/redstone/CoverWirelessMaintenanceDetector.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#3751 More batch mode
  src/main/java/goodgenerator/blocks/tileEntity/MTENeutronActivator.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeFusionComputer.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeFusionComputerPP.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDistillationTower.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEImplosionCompressor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPyrolyseOven.java
  src/main/resources/assets/goodgenerator/lang/en_US.lang
Labels: enhancement

#3757 remove froth recycling Circuits
  src/main/java/gtPlusPlus/api/recipe/GTPPRecipeMaps.java
  src/main/java/gtPlusPlus/core/item/chemistry/MilledOreProcessing.java
Labels: enhancement

#3753 fix HV tank recipes
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
Labels: bug fix

#3756 Changing name of MBF to MEBF
  src/main/resources/assets/bartworks/lang/en_US.lang
Labels: enhancement

#3732 Migrate coremod casings to GT5u
  src/main/java/goodgenerator/loader/RecipeLoader2.java
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/common/blocks/BlockCasingsNH.java
  src/main/java/gregtech/common/blocks/ItemCasingsNH.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPyrolyseOven.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/algae/MTEAlgaePondBase.java
  src/main/java/tectech/loader/MainLoader.java
  src/main/java/tectech/thing/CustomItemList.java
  src/main/java/tectech/thing/casing/BlockGTCasingsNH.java
  src/main/java/tectech/thing/casing/TTCasingsContainer.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: chore, :construction: Testing on Zeta

#3758 Added Assembler Recipe for the Distillation Tower
  src/main/java/bartworks/common/loaders/recipes/Assembler.java
Labels: enhancement

#3759 Allow pulling from the auto workbench's first byproduct slot (slot 9).
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/automation/MTEElectricAutoWorkbench.java
Labels: enhancement, :construction: Testing on Zeta

#3762 Disable redstone control on the superchest/quantumchest itself
  src/main/java/gregtech/common/tileentities/storage/MTEDigitalChestBase.java
Labels: enhancement, :construction: Testing on Zeta

#3752 Fixed GT++ Logs Missing Recipes
  src/main/java/gregtech/loaders/oreprocessing/ProcessingLog.java
  src/main/java/gtPlusPlus/xmod/bop/blocks/BOPBlockRegistrator.java
Labels: bug fix, :construction: Testing on Zeta

#3706 Remove metadata casts to byte
  src/main/java/bartworks/API/GlassTier.java
  src/main/java/bartworks/system/material/BWMetaGeneratedItems.java
  src/main/java/detrav/items/tools/DetravToolElectricProspectorBase.java
  src/main/java/gregtech/api/interfaces/IBlockContainer.java
  src/main/java/gregtech/api/interfaces/IRedstoneCircuitBlock.java
  src/main/java/gregtech/api/interfaces/IToolStats.java
  src/main/java/gregtech/api/interfaces/tileentity/IHasWorldObjectAndCoords.java
  src/main/java/gregtech/api/items/MetaGeneratedTool.java
  src/main/java/gregtech/api/metatileentity/BaseTileEntity.java
  src/main/java/gregtech/api/util/GTBlockMap.java
  src/main/java/gregtech/api/util/GTBlockSet.java
  src/main/java/gregtech/api/util/GTToolHarvestHelper.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/common/items/behaviors/BehaviourCrowbar.java
  src/main/java/gregtech/common/items/behaviors/BehaviourScrewdriver.java
  src/main/java/gregtech/common/items/behaviors/BehaviourSoftHammer.java
  src/main/java/gregtech/common/render/GTCopiedBlockTextureRender.java
  src/main/java/gregtech/common/render/GTCopiedCTMBlockTexture.java
  src/main/java/gregtech/common/render/GTTextureBuilder.java
  src/main/java/gregtech/common/tileentities/machines/long_distance/MTELongDistancePipelineBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEOilCracker.java
  src/main/java/gregtech/common/tools/GTTool.java
  src/main/java/gregtech/common/tools/ToolBranchCutter.java
  src/main/java/gregtech/common/tools/ToolButcheryKnife.java
  src/main/java/gregtech/common/tools/ToolBuzzSaw.java
  src/main/java/gregtech/common/tools/ToolChainsawLV.java
  src/main/java/gregtech/common/tools/ToolCrowbar.java
  src/main/java/gregtech/common/tools/ToolDrillLV.java
  src/main/java/gregtech/common/tools/ToolFile.java
  src/main/java/gregtech/common/tools/ToolHardHammer.java
  src/main/java/gregtech/common/tools/ToolJackHammer.java
  src/main/java/gregtech/common/tools/ToolKnife.java
  src/main/java/gregtech/common/tools/ToolMortar.java
  src/main/java/gregtech/common/tools/ToolPlunger.java
  src/main/java/gregtech/common/tools/ToolRollingPin.java
  src/main/java/gregtech/common/tools/ToolSaw.java
  src/main/java/gregtech/common/tools/ToolScoop.java
  src/main/java/gregtech/common/tools/ToolScrewdriver.java
  src/main/java/gregtech/common/tools/ToolSoftHammer.java
  src/main/java/gregtech/common/tools/ToolSolderingIron.java
  src/main/java/gregtech/common/tools/ToolTurbine.java
  src/main/java/gregtech/common/tools/ToolWireCutter.java
  src/main/java/gregtech/common/tools/ToolWrench.java
  src/main/java/gregtech/common/tools/pocket/ToolPocketMultitool.java
  src/main/java/gtPlusPlus/api/interfaces/ILazyCoverable.java
  src/main/java/gtPlusPlus/core/tileentities/base/TileEntityBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/interfaces/internal/IToolStats.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/items/GTMetaTool.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/GregtechMetaCasingBlocks4.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/GregtechMetaSpecialMultiCasings.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/GregtechMetaSpecialMultiCasings2.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/textures/turbine/LargeTurbineTextureHandler.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialWashPlant.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEIndustrialFishingPond.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/algae/MTEAlgaePondBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/storage/GregtechMetaTileEntity_PowerSubStationController.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/redstone/MTERedstoneCircuitBlock.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tools/ToolAngleGrinder.java
Labels: refactor, bug fix, :construction: Testing on Zeta

#3767 Migrate coremod machines to GT5u
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/gui/modularui/GTUITextures.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTENameRemover.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAirFilter1.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAirFilter2.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAirFilter3.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAirFilterBase.java
  src/main/java/gregtech/loaders/postload/PCBFactoryMaterialLoader.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/resources/assets/gregtech/textures/gui/progressbar/name_remover.png
Labels: refactor

#3760 Revert "Changing name of MBF to MEBF"
  src/main/resources/assets/bartworks/lang/en_US.lang
Labels: chore

#3768 Add perfect Isolation to CRIB Tooltip
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
Labels: enhancement

#3771 remove over 1000 recipes that were pure bloat
  src/main/java/gregtech/loaders/oreprocessing/ProcessingPlate.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenShapedCrafting.java
Labels: refactor

#3778 Allow name remover to remove muffler upgrades
  src/main/java/gregtech/common/tileentities/machines/basic/MTENameRemover.java
Labels: new feature

#3784 Combine duplicate Titansteel fluids in UHV charge pack recipe
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
Labels: bug fix

#3785 remove ic2 valuable ore compat, ic2 miner, and ic2 scanners
  src/main/java/bartworks/system/material/BWMetaGeneratedOres.java
  src/main/java/bartworks/system/material/BWMetaGeneratedSmallOres.java
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/util/GTModHandler.java
  src/main/java/gregtech/common/blocks/BlockOresAbstract.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingOre.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingRawOre.java
  src/main/java/gregtech/loaders/postload/MinableRegistrator.java
Labels: bug fix, chore

#3761 Rebalance scanning times
  src/main/java/bartworks/common/loaders/recipes/AssemblyLine.java
  src/main/java/ggfab/ComponentRecipeLoader.java
  src/main/java/goodgenerator/blocks/tileEntity/MTEFuelRefineFactory.java
  src/main/java/goodgenerator/loader/ComponentAssemblyLineMiscRecipes.java
  src/main/java/goodgenerator/loader/RecipeLoader.java
  src/main/java/goodgenerator/loader/RecipeLoader2.java
  src/main/java/gregtech/api/util/AssemblyLineUtils.java
  src/main/java/gregtech/api/util/GTRecipe.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/gregtech/api/util/recipe/Scanning.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEScanner.java
  src/main/java/gregtech/loaders/postload/chains/NaniteChain.java
  src/main/java/gregtech/loaders/postload/chains/PCBFactoryRecipes.java
  src/main/java/gregtech/loaders/postload/chains/PurifiedWaterRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblyLineRecipes.java
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIsaMill.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEElementalDuplicator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEFrothFlotationCell.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEMassFabricator.java
  src/main/java/gtnhlanth/common/tileentity/MTEDigester.java
  src/main/java/gtnhlanth/loader/RecipeLoader.java
  src/main/java/kekztech/common/recipeLoaders/AssemblyLine.java
  src/main/java/kubatech/loaders/RecipeLoader.java
  src/main/java/tectech/loader/recipe/AssemblyLine.java
  src/main/java/tectech/recipe/TTRecipeAdder.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEResearchStation.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: Affects Balance

#3777 Fix multiblock extruder playing bender sound
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialExtruder.java
Labels: bug fix

#3774 Add cells for missing coremod fluids
  src/main/java/gregtech/common/items/MetaGeneratedItem98.java
Labels: enhancement

#3779 Allow plunger to drain all fluid when sneaking
  src/main/java/gregtech/common/items/behaviors/BehaviourPlungerFluid.java
Labels: enhancement

#3780 Show "Working Disabled" instead of "Idle" when machine is soft malleted
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/util/GTWaila.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/MTESteamMultiBase.java
Labels: enhancement

#3781 Add tooltip to parameter copy paste card
  src/main/java/tectech/thing/item/ItemParametrizerMemoryCard.java
Labels: enhancement

#3782 Allow setting amperage with screwdriver on wireless lasers
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchWirelessMulti.java
Labels: enhancement

#3772 Renaming MEBF to MBF
  src/main/resources/assets/bartworks/lang/en_US.lang
Labels: enhancement

#3786 Remove more naqfuels
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
  src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/ChemicalRecipes.java
  src/main/java/gtPlusPlus/core/recipe/RecipesGeneral.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/enums/GregtechItemList.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/blocks/GregtechMetaCasingBlocks4.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechCustomHatches.java
Labels: chore

#3739 remove weak turbine cutoff
  src/main/java/gtPlusPlus/core/config/Configuration.java
  src/main/java/gtPlusPlus/core/handler/CompatIntermodStaging.java
  src/main/java/gtPlusPlus/recipes/RecipeRemovals.java
Labels: bug fix, :construction: Testing on Zeta

#3787 Widen Modifiers to `protected` in MTEHatchInputBusME and MTEHatchOutputBusME
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputBusME.java
Labels: chore

#3770 Add casing minimum to Chemical Plant tooltip
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/MTEChemicalPlant.java
Labels: enhancement

#3776 Show EEC current mob in WAILA and tricorder
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeEntityCrusher.java
  src/main/resources/assets/kubatech/lang/en_US.lang
Labels: new feature

#3728 Refactor Biovat and Radio Hatches
  src/main/java/bartworks/API/recipe/BacterialVatFrontend.java
  src/main/java/bartworks/API/recipe/BartWorksRecipeMaps.java
  src/main/java/bartworks/API/recipe/RadioHatchFrontend.java
  src/main/java/bartworks/common/loaders/BioRecipeLoader.java
  src/main/java/bartworks/common/loaders/RadioHatchMaterialLoader.java
  src/main/java/bartworks/common/loaders/recipes/CraftingRecipes.java
  src/main/java/bartworks/common/tileentities/multis/MTEBioVat.java
  src/main/java/bartworks/common/tileentities/tiered/GT_MetaTileEntity_RadioHatch.java
  src/main/java/bartworks/system/material/processingLoaders/AdditionalRecipes.java
  src/main/java/bartworks/util/BWRecipes.java
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/gregtech/api/util/recipe/Sievert.java
  src/main/resources/assets/bartworks/lang/de_DE.lang
  src/main/resources/assets/bartworks/lang/en_US.lang
  src/main/resources/assets/bartworks/lang/fr_FR.lang
Labels: refactor, bug fix, :construction: Testing on Zeta

#3764 Fix traversal order of `RecipeMap`.
  src/main/java/gregtech/api/recipe/RecipeMapBackend.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/recipe/RecipeLoaderChemicalSkips.java
Labels: enhancement, bug fix

#3790 Ender tank voiding fluids in gt tank input slot fix
  src/main/java/gregtech/api/util/GTUtility.java
Labels: bug fix

#3737 Add NC hatches for PCB Factory and QFT
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchBulkCatalystHousing.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchNanite.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchNonConsumableBase.java
  src/main/java/gregtech/api/objects/AE2NonconsumableHatchHandler.java
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/api/util/GTRecipeConstants.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPCBFactory.java
  src/main/java/gregtech/loaders/preload/LoaderMetaTileEntities.java
  src/main/java/gregtech/nei/NEIGTConfig.java
  src/main/java/gtPlusPlus/api/recipe/GTPPRecipeMaps.java
  src/main/java/gtPlusPlus/nei/NEIGTPPConfig.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/nbthandlers/MTEHatchCatalysts.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEQuantumForceTransformer.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_NANITE_HATCH.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_NANITE_HATCH_GLOW.png
Labels: enhancement, new feature, :construction: Testing on Zeta

#3608 Cribs super recipe check
  src/main/java/gregtech/api/logic/AbstractProcessingLogic.java
  src/main/java/gregtech/api/logic/ProcessingLogic.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/objects/GTDualInputs.java
  src/main/java/gregtech/common/tileentities/machines/IDualInputHatch.java
  src/main/java/gregtech/common/tileentities/machines/IDualInputInventory.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputSlave.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: enhancement, :construction: Testing on Zeta

#3794 Update super chests description
  src/main/java/gregtech/common/tileentities/storage/MTEDigitalChestBase.java
Labels: bug fix

#3793 fix end dust bee
  src/main/java/gregtech/common/items/ItemComb.java
Labels: bug fix

#3797 fix bw fluid names
  src/main/java/bartworks/common/loaders/FluidLoader.java
Labels: bug fix

#3802 Remove MuTE leftover & minor refactor around ProcessingLogic
  src/main/java/goodgenerator/blocks/tileEntity/MTENeutronActivator.java
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/enums/GTValues.java
  src/main/java/gregtech/api/enums/InventoryType.java
  src/main/java/gregtech/api/gui/GUIHost.java
  src/main/java/gregtech/api/gui/GUIProvider.java
  src/main/java/gregtech/api/interfaces/tileentity/IEnergyConnected.java
  src/main/java/gregtech/api/logic/AbstractProcessingLogic.java
  src/main/java/gregtech/api/logic/ComplexParallelProcessingLogic.java
  src/main/java/gregtech/api/logic/ControllerFluidLogic.java
  src/main/java/gregtech/api/logic/ControllerItemLogic.java
  src/main/java/gregtech/api/logic/FluidInventoryLogic.java
  src/main/java/gregtech/api/logic/ItemInventoryLogic.java
  src/main/java/gregtech/api/logic/ModelRenderLogic.java
  src/main/java/gregtech/api/logic/MuTEProcessingLogic.java
  src/main/java/gregtech/api/logic/NullPowerLogic.java
  src/main/java/gregtech/api/logic/PowerLogic.java
  src/main/java/gregtech/api/logic/ProcessingLogic.java
  src/main/java/gregtech/api/logic/interfaces/FluidInventoryLogicHost.java
  src/main/java/gregtech/api/logic/interfaces/ItemInventoryLogicHost.java
  src/main/java/gregtech/api/logic/interfaces/ModelRenderLogicHost.java
  src/main/java/gregtech/api/logic/interfaces/PowerLogicHost.java
  src/main/java/gregtech/api/logic/interfaces/ProcessingLogicHost.java
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTECable.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/objects/GTHashSet.java
  src/main/java/gregtech/api/objects/GTItemStack.java
  src/main/java/gregtech/api/objects/GTItemStack2.java
  src/main/java/gregtech/api/task/TaskHost.java
  src/main/java/gregtech/api/task/TickableTask.java
  src/main/java/gregtech/api/task/tasks/PollutionTask.java
  src/main/java/gregtech/api/task/tasks/PowerOutputTask.java
  src/main/java/gregtech/api/task/tasks/ProcessingTask.java
  src/main/java/gregtech/api/util/GTModHandler.java
  src/main/java/gregtech/api/util/GTRecipe.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/ParallelHelper.java
  src/main/java/gregtech/api/util/VoidProtectionHelper.java
  src/main/java/gregtech/api/util/item/ItemHolder.java
  src/main/java/gregtech/api/util/recipe/RecipeInputRequirements.java
  src/main/java/gregtech/common/gui/ComplexParallelMachineGUIProvider.java
  src/main/java/gregtech/common/gui/MachineGUIProvider.java
  src/main/java/gregtech/common/gui/PartGUIProvider.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialElectromagneticSeparator.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTETranscendentPlasmaMixer.java
  src/main/java/tectech/TecTech.java
  src/main/java/tectech/loader/thing/MuTeLoader.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchDynamoTunnel.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEExoticModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEMoltenModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEPlasmaModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTESmeltingModule.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeEnergy.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeEnergyMirror.java
Labels: refactor

#3795 Change tier textures for Auto-Taping, Uncertanty Resolver, and Wireless Data Hatches
  src/main/java/tectech/loader/thing/MachineLoader.java
Labels: enhancement

#3801 Remove Teflon
  src/main/java/goodgenerator/loader/RecipeLoader2.java
  src/main/java/gtPlusPlus/core/item/chemistry/GenericChem.java
  src/main/resources/assets/miscutils/lang/en_US.lang
  src/main/resources/assets/miscutils/lang/ru_RU.lang
  src/main/resources/assets/miscutils/lang/zh_CN.lang
Labels: enhancement

#3799 Allow GT++ apiary frames to be repaired
  src/main/java/gtPlusPlus/xmod/forestry/bees/items/MBItemFrame.java
Labels: enhancement

#3796 Order DTPF Recipes by Catalyst Tier
  src/main/java/gregtech/loaders/postload/recipes/PlasmaForgeRecipes.java
Labels: enhancement

#3792 Make multiblocks able to better modify their NEI preview
  src/main/java/bartworks/common/tileentities/multis/MTEElectricImplosionCompressor.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeTurbineBase.java
  src/main/java/gregtech/api/interfaces/INEIPreviewModifier.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPCBFactory.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialCentrifuge.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
Labels: refactor, bug fix

#3766 Retier CRIB, proxy, adv stocking hatch
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer1.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer2.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer3.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer4.java
  src/main/java/goodgenerator/blocks/tileEntity/MTELargeFusionComputer5.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeFusionComputer.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputSlave.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputME.java
Labels: enhancement, :construction: Testing on Zeta

#3798 Remove beamline mask repairing
  src/main/java/gtnhlanth/common/item/ItemPhotolithographicMask.java
Labels: bug fix

#3775 Allow screwdriver in toolbox for programmed circuit
  src/main/java/bartworks/common/items/ItemCircuitProgrammer.java
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/common/items/ItemIntegratedCircuit.java
  src/main/java/gtPlusPlus/core/item/circuit/GTPPIntegratedCircuitItem.java
Labels: new feature

#3806 Fix 1 tick research completer recipes not draining vis
  src/main/java/gregtech/common/tileentities/machines/multi/MTEResearchCompleter.java
Labels: bug fix

#3807 change busses to buses in Tooltips etc
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeChemicalReactor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTENanoForge.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPlasmaForge.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEProcessingArray.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/misc/MTEAmazonPackager.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEQuantumForceTransformer.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTETreeFarm.java
  src/main/java/kekztech/common/tileentities/MTETankTFFT.java
  src/main/resources/assets/ggfab/lang/en_US.lang
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/miscutils/lang/en_US.lang
  src/main/resources/assets/miscutils/lang/ru_RU.lang
Labels: enhancement

#3803 Restore stability waila info for black hole
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
Labels: enhancement

#3808 Add superstable black hole seed
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/common/items/IDMetaItem01.java
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/420.png
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.01/420.png.mcmeta
Labels: Affects Balance, new feature

#3810 Rotating machines break adjacent enets
  src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
Labels: bug fix, safe for stable

#3811 Update recipes to gt solar panels
  src/main/java/tectech/loader/recipe/ResearchStationAssemblyLine.java
Labels: enhancement

#3809 Add supercritical steams to steam valve and regulator
  src/main/java/gregtech/common/covers/CoverSteamRegulator.java
  src/main/java/gregtech/common/covers/CoverSteamValve.java
Labels: bug fix

#3621 Factory pipe system
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
  src/main/java/gregtech/api/factory/BlockData.java
  src/main/java/gregtech/api/factory/BlockGroup.java
  src/main/java/gregtech/api/factory/IFactoryElement.java
  src/main/java/gregtech/api/factory/IFactoryGrid.java
  src/main/java/gregtech/api/factory/IFactoryNetwork.java
  src/main/java/gregtech/api/factory/standard/StandardFactoryGrid.java
  src/main/java/gregtech/api/factory/standard/StandardFactoryNetwork.java
  src/main/java/gregtech/api/factory/test/TestFactoryElement.java
  src/main/java/gregtech/api/factory/test/TestFactoryGrid.java
  src/main/java/gregtech/api/factory/test/TestFactoryHatch.java
  src/main/java/gregtech/api/factory/test/TestFactoryNetwork.java
  src/main/java/gregtech/api/factory/test/TestFactoryPipe.java
  src/main/java/gregtech/api/interfaces/metatileentity/IMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatch.java
  src/main/java/tectech/loader/NetworkDispatcher.java
  src/main/java/tectech/loader/thing/MachineLoader.java
  src/main/java/tectech/mechanics/pipe/BatchedPipeActivityMessage.java
  src/main/java/tectech/mechanics/pipe/PipeActivity.java
  src/main/java/tectech/thing/CustomItemList.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEBaseFactoryHatch.java
  src/main/java/tectech/thing/metaTileEntity/pipe/MTEBaseFactoryPipe.java
Labels: new feature

#3280 Cleaned up Throwable try catches
  src/main/java/bartworks/util/BWUtil.java
  src/main/java/gregtech/GTMod.java
  src/main/java/gregtech/api/items/MetaBaseItem.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachineBronze.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEFluid.java
  src/main/java/gregtech/api/threads/RunnableSound.java
  src/main/java/gregtech/api/util/GTConfig.java
  src/main/java/gregtech/api/util/GTForestryCompat.java
  src/main/java/gregtech/api/util/GTModHandler.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/blocks/ItemMachines.java
  src/main/java/gregtech/common/items/ItemIntegratedCircuit.java
  src/main/java/gregtech/common/items/behaviors/BehaviourWrench.java
  src/main/java/gregtech/common/tileentities/boilers/MTEBoiler.java
  src/main/java/gtPlusPlus/core/block/machine/BlockPooCollector.java
  src/main/java/gtPlusPlus/core/handler/CompatHandler.java
  src/main/java/gtPlusPlus/core/material/Material.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenDustGeneration.java
  src/main/java/gtPlusPlus/xmod/gregtech/loaders/RecipeGenRecycling.java
  src/main/java/tectech/loader/MainLoader.java
Labels: refactor

#3804 Change block autogen to use material mass for duration
  src/main/java/gregtech/loaders/oreprocessing/ProcessingBlock.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingShaping.java
Labels: enhancement, Affects Balance

#3816 fix error in tooltip
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/MTELargerTurbineBase.java
Labels: bug fix

#3814 Lsc wireless mode improvements
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
  src/main/resources/assets/kekztech/lang/en_US.lang
Labels: enhancement, :construction: Testing on Zeta

#3818 Correct tengam for magnetic upgrade in Antimatter forge
  src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
Labels: bug fix, safe for stable

#3819 Remove Old GT++ UI from some multiblocks
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTECyclotron.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEElementalDuplicator.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTELargeRocketEngine.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTESolarTower.java
Labels: enhancement

#3820 Change recipe to output 2 sulfur dust instead of 8 small sulfur dust
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
Labels: enhancement

#3823 Fix T7 water crash on restart when using bonus output
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitDegasser.java
Labels: bug fix

#3822 Beamline fixes 5
  src/main/java/gtnhlanth/common/tileentity/MTELINAC.java
  src/main/java/gtnhlanth/common/tileentity/MTESynchrotron.java
  src/main/java/gtnhlanth/common/tileentity/MTETargetChamber.java
  src/main/java/gtnhlanth/util/Util.java
Labels: enhancement, bug fix

#3824 Add null check for current recipe on t5 water failure
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitPlasmaHeater.java
Labels: bug fix

#3813 Change QFT hatch requirements
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEQuantumForceTransformer.java
Labels: enhancement

#3827 Improve gt solars
  src/main/java/gregtech/common/tileentities/generators/MTESolarGenerator.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#3821 Add subtag for generating multi-plates
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/api/enums/OrePrefixes.java
  src/main/java/gregtech/api/enums/SubTag.java
Labels: refactor

#3788 Retexture RTG, Charcoal Pile Igniter, Seismic Prospector
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/common/tileentities/machines/basic/MTEAdvSeismicProspector.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTECharcoalPit.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/generators/MTERTGenerator.java
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_CHARCOAL_PIT.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_CHARCOAL_PIT_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_CHARCOAL_PIT_ACTIVE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_SEISMIC_PROSPECTOR.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_SEISMIC_PROSPECTOR_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_SEISMIC_PROSPECTOR_ACTIVE.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_FRONT_SEISMIC_PROSPECTOR_ACTIVE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_SIDE_RTG.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_SIDE_RTG_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_SIDE_RTG_ACTIVE_GLOW.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_TOP_RTG.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_TOP_RTG_ACTIVE.png
  src/main/resources/assets/gregtech/textures/blocks/iconsets/OVERLAY_TOP_RTG_ACTIVE_GLOW.png
Labels: enhancement

#3831 Buff HILE speed slightly
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
Labels: Affects Balance

#3829 Expose ME hatch additionalConnections for MM
  src/main/java/gregtech/api/interfaces/IMEConnectable.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchInputME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputBusME.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
Labels: enhancement

#3830 Disable CRIB pattern pushing when working disabled
  src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
Labels: enhancement

#3832 Allow limited multiamp on HILE
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialLaserEngraver.java
Labels: Affects Balance, safe for stable

#3833 Add missed materials to multi-plates
  src/main/java/gregtech/api/enums/Materials.java
Labels: bug fix

#3835 Add proper support for dense steam to steam valve and regulator
  src/main/java/gregtech/common/covers/CoverSteamRegulator.java
  src/main/java/gregtech/common/covers/CoverSteamValve.java
Labels: bug fix

#3838 Lock dust > tiny/small dust recipe to the top row
  src/main/java/gregtech/common/GTProxy.java
Labels: bug fix

#3840 Fix: PreciseAssembler accepts Bronze Plated Bricks as high tier machine blocks
  dependencies.gradle
  src/main/java/goodgenerator/blocks/tileEntity/MTEPreciseAssembler.java
Labels: bug fix

#3841 Add multiplate tag for Bartworks materials
  src/main/java/bartworks/system/material/Werkstoff.java
  src/main/java/bartworks/system/material/WerkstoffLoader.java
  src/main/java/goodgenerator/items/GGMaterial.java
  src/main/java/gtnhlanth/common/register/WerkstoffMaterialPool.java
Labels: refactor

#3842 Add total and usage back to Bacterial Vat
  src/main/java/bartworks/API/recipe/BacterialVatFrontend.java
Labels: bug fix

#3834 Consolidate IC2 item sourcing via existing ItemList entries in recipes
  src/main/java/goodgenerator/loader/RecipeLoader2.java
  src/main/java/goodgenerator/util/ItemRefer.java
  src/main/java/gregtech/api/util/GTRecipe.java
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/loaders/misc/GTAchievements.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingLog.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingShaping.java
  src/main/java/gregtech/loaders/postload/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/postload/ScrapboxDropLoader.java
  src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/BenderRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/CannerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/CompressorRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/ExtractorRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/FluidExtractorRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/MixerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/Pulverizer.java
  src/main/java/gregtech/loaders/postload/recipes/RecipeRemover.java
  src/main/java/gregtech/loaders/preload/GTPreLoad.java
  src/main/java/gregtech/loaders/preload/LoaderGTOreDictionary.java
  src/main/java/gtPlusPlus/core/item/ModItems.java
  src/main/java/gtPlusPlus/core/item/base/cell/BaseItemCell.java
  src/main/java/gtPlusPlus/core/item/chemistry/AgriculturalChem.java
  src/main/java/gtPlusPlus/core/util/Utils.java
  src/main/java/gtPlusPlus/plugin/agrichem/BioRecipes.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTECropHarvestor.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEMassFabricator.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechIndustrialMassFabricator.java
  src/main/java/gtnhlanth/loader/BotRecipes.java
  src/main/java/kubatech/loaders/RecipeLoader.java
Labels: refactor

#3839 Add Waila Pipe info
  src/main/java/gregtech/api/metatileentity/implementations/MTEFluid.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: enhancement

#3843 BHC Energy Hatch Limit and Parallel Calculations, Green TecTech Hatch Tooltip
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/MultiblockTooltipBuilder.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEIndustrialElectromagneticSeparator.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
Labels: enhancement

#3846 Add blank casings page 12
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/enums/Textures.java
  src/main/java/gregtech/common/blocks/BlockCasings12.java
  src/main/java/gregtech/common/blocks/ItemCasings12.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
Labels: enhancement

#3845 Fix black hole circuits
  src/main/java/gregtech/common/items/MetaGeneratedItem01.java
  src/main/java/gregtech/common/tileentities/machines/multi/compressor/MTEBlackHoleCompressor.java
Labels: bug fix

#3848 More accurate Waila status line for steam machines with obstructed vents
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: bug fix

#3850 Remove double plates from multiplate subtag
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/api/enums/OrePrefixes.java
  src/main/java/gregtech/api/enums/SubTag.java
Labels: bug fix

#3849 Change biolab recipes to be able to use any circuit o the tier and not just the item any circuit of the tier
  src/main/java/bartworks/common/loaders/recipes/CraftingRecipes.java
Labels: bug fix

#3851 Add multi_plate subtag to materials that are used to make gc and dreamcore compressed plates
  src/main/java/gregtech/api/enums/Materials.java
Labels: bug fix

#3853 Deprecate GTLanguageManager
  src/main/java/gregtech/api/util/GTLanguageManager.java
  src/main/java/gregtech/api/util/GTUtility.java
Labels: chore

#3854 Consolidate GoodGenerator MTE IDs enum
  src/main/java/goodgenerator/loader/IDs_GoodGenerator.java
  src/main/java/goodgenerator/loader/Loaders.java
  src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
Labels: refactor

#3856 Fix: tectech AL recipe adder does not reinit datasticks correctly
  src/main/java/tectech/recipe/TTRecipeAdder.java
Labels: bug fix

#3857 Fix Large HP Steam Turbine ignoring loose flow setting
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeTurbineHPSteam.java
Labels: bug fix

#3858 Capitalize "Station" in Research Station
  src/main/java/tectech/loader/thing/MachineLoader.java
Labels: bug fix

#3859 Fix cribusses dupe 2.8
  src/main/java/gregtech/api/logic/ProcessingLogic.java
Labels: bug fix, :construction: Testing on Zeta

#3837 Rewrite CoAL recipe loader
  src/main/java/goodgenerator/api/recipe/GoodGeneratorRecipeMaps.java
  src/main/java/goodgenerator/loader/ComponentAssemblyLineLoader.java
  src/main/java/goodgenerator/loader/ComponentAssemblyLineRecipeLoader.java
  src/main/java/goodgenerator/loader/Loaders.java
  src/main/java/gregtech/api/enums/OrePrefixes.java
Labels: refactor

#3861 Fix `TTUtility.toExponentForm()` throws with smaller inputs
  src/main/java/tectech/util/TTUtility.java
  src/test/java/tectech/util/TTUtilityTest.java
Labels: bug fix

#3862 Fix cribs in fluid shaper
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: bug fix

#3852 Replace Aluminum Gravel Ore with Zinc Gravel Ore, and deal with the consequences
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
  src/main/java/gregtech/loaders/postload/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/postload/recipes/MixerRecipes.java
Labels: Affects Balance

#3863 Better Assline checkresult
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAssemblyLine.java
Labels: bug fix, :construction: Testing on Zeta

#3865 This was supposed to be tea, not lemon juice/milk
  src/main/java/kubatech/loaders/RecipeLoader.java
Labels: bug fix

#3866 Remove Precious Metal Alloy recipe in ABS
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
Labels: enhancement

#3869 UV Motor Recipe Correction
  src/main/java/goodgenerator/loader/ComponentAssemblyLineLoader.java
Labels: bug fix

#3867 Add throughput info for Multi-Amp and Laser hatches to scanner and Waila
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchEnergyMulti.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchEnergyTunnel.java
  src/main/java/tectech/thing/metaTileEntity/hatch/MTEHatchWirelessMulti.java
Labels: enhancement

#3868 Multiblock Replicator Hatch Refactor
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEElementalDuplicator.java
Labels: refactor, Affects Balance

#3870 Correct recipe input order for UV motor CoAL recipe
  src/main/java/goodgenerator/loader/ComponentAssemblyLineLoader.java
Labels: chore

#3871 Fix ME hatches voiding
  src/main/java/bartworks/common/tileentities/multis/mega/MTEMegaDistillTower.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputME.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDistillationTower.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvDistillationTower.java
Labels: bug fix

#3873 Cover UI crash fixes
  src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java
  src/main/java/gregtech/api/objects/GTCoverNone.java
  src/main/java/gregtech/common/blocks/BlockMachines.java
Labels: bug fix
