Repository GTNewHorizons/GT5-Unofficial, pull requests merged in 2025-09, with the labels that each got.

#4811 Fix solidifier hatch duplication bug
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiSolidifier.java
Labels: Bug Fix

#4775 Fix some MBs missing hatches in the NEI preview and adds survival construct
  src/main/java/bartworks/common/tileentities/multis/MTEBioVat.java
  src/main/java/bartworks/common/tileentities/multis/MTEHighTempGasCooledReactor.java
  src/main/java/bartworks/common/tileentities/multis/MTEManualTrafo.java
  src/main/java/bartworks/common/tileentities/multis/MTEThoriumHighTempReactor.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEAirFilterBase.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeMolecularAssembler.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEResearchCompleter.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvHeatExchanger.java
  src/main/java/kekztech/common/tileentities/MTESOFuelCellMK1.java
  src/main/java/kekztech/common/tileentities/MTESOFuelCellMK2.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEMicrowave.java
Labels: Bug Fix

#4819 Clamp multi smelter energy usage to safe voltage
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiFurnace.java
Labels: Bug Fix

#4820 Centralize Kubatech UI textures all in one class
  src/main/java/kubatech/api/gui/KubaTechUITextures.java
  src/main/java/kubatech/api/implementations/KubaTechGTMultiBlockBase.java
  src/main/java/kubatech/loaders/DEFCRecipes.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeEntityCrusher.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEMegaIndustrialApiary.java
Labels: Refactor

#4825 Add categories for new machine and tool sounds
  src/main/resources/assets/gtceu/sounds.json
Labels: Bug Fix, Safe for Stable

#4824 Change all Mentions of "Semi-Fluid" to "Semifluid" in Game
  src/main/java/gregtech/api/util/SemiFluidFuelHandler.java
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
  src/main/java/gtPlusPlus/core/recipe/RecipesMachines.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/enums/GregtechItemList.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTELargeSemifluidGenerator.java
  src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechSemiFluidgenerators.java
Labels: Bug Fix

#4823 Fix YOTTA hatch connection
  src/main/java/goodgenerator/blocks/tileEntity/GTMetaTileEntity/MTEYOTTAHatch.java
Labels: Bug Fix

#4827 Fix random blocks being unharvestable on vajra left click in full pack
  src/main/java/gregtech/common/tools/ToolVajra.java
Labels: Bug Fix, Safe for Stable

#4831 Fixes Plutonium Fuel Rod Names
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
Labels: Bug Fix

#4833 Remove extra parallels line from Boldarnator WAILA tooltip
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEIndustrialRockBreaker.java
Labels: Bug Fix

#4832 Clamp purification unit fluid stack outputs to max int to avoid overflow at high parallels
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBase.java
Labels: Bug Fix

#4836 Gets Rid of Duplicate Netherrack Compression Recipe
  src/main/java/gregtech/loaders/oreprocessing/ProcessingDust.java
  src/main/java/gregtech/loaders/postload/recipes/CompressorRecipes.java
Labels: Bug Fix

#4829 Show same veins in different planet
  src/main/java/bartworks/system/oregen/BWOreLayer.java
Labels: Bug Fix

#4826 fix(EIG): Correctly simulate drops for entity-spawning seeds
  src/main/java/kubatech/tileentity/gregtech/multiblock/eigbuckets/EIGSeedBucket.java
Labels: Bug Fix

#4841 Netherrack Recipe Revert
  src/main/java/gregtech/loaders/postload/recipes/CompressorRecipes.java
Labels: Bug Fix

#4840 Hotfix - Muffler upgrades now work with Steam Boilers
  src/main/java/gregtech/common/tileentities/boilers/MTEBoiler.java
Labels: Bug Fix

#4843 Fix EEC ritual mode exception
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeEntityCrusher.java
Labels: Bug Fix, Safe for Stable

#4845 Update deps
  dependencies.gradle
Labels: Chore

#4852 Fix fusion overclocks (NEI + machines)
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeFusionComputer.java
  src/main/java/gregtech/api/objects/overclockdescriber/FusionOverclockDescriber.java
  src/main/java/gregtech/api/recipe/RecipeMaps.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEFusionComputer.java
Labels: Bug Fix

#4853 Add UCFE to GTPP Rocket Fuel NEI page
  src/main/java/goodgenerator/blocks/tileEntity/MTEUniversalChemicalFuelEngine.java
Labels: Enhancement

#4794 Remove upgrade mechanic from Dangote Distillus
  src/main/java/gtPlusPlus/core/recipe/RecipesGregTech.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/enums/GregtechItemList.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/items/MetaGeneratedGregtechItems.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/items/MetaGeneratedItemIDs.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/advanced/MTEAdvDistillationTower.java
  src/main/resources/assets/miscutils/textures/items/MU-metaitem.01/151.png
Labels: Enhancement, Safe for Stable

#4863 Allow ritual stone to be one block closer to the top of the EEC
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeEntityCrusher.java
Labels: Enhancement

#4859 Added Heatbonus variable to nuke fuel cells
  src/main/java/gregtech/api/items/ItemRadioactiveCellIC.java
  src/main/java/gregtech/common/items/ItemDepletedCell.java
  src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
Labels: Bug Fix

#4873 Remove gem recipes from Block to gem, ingot, and dust
  src/main/java/gregtech/loaders/oreprocessing/ProcessingBlock.java
  src/main/java/gregtech/loaders/oreprocessing/ProcessingDust.java
  src/main/java/gregtech/loaders/postload/recipes/ForgeHammerRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/Pulverizer.java
Labels: Bug Fix

#4874 Fix coil preview
  src/main/java/gregtech/common/blocks/BlockCasings5.java
Labels: Bug Fix, Safe for Stable

#4882 Add Thermic Heating Device Abbreviation
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialFluidHeater.java
Labels: Chore

#4875 Add Circuit 9 recipes for gem juice
  src/main/java/gregtech/loaders/postload/chains/BauxiteRefineChain.java
Labels: Affects Balance

#4883 Fix Steam Input Bus NEI preview corruption issue
  src/main/java/gregtech/api/enums/HatchElement.java
  src/main/java/gregtech/api/interfaces/IHatchElement.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/util/GTStructureUtility.java
  src/main/java/gregtech/api/util/HatchElementBuilder.java
Labels: Bug Fix

#4844 Buff Cryogenic Freezer
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/MTEIndustrialVacuumFreezer.java
Labels: Affects Balance

#4890 fix: consider the mothership dimension as low gravity
  src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachine.java
Labels: Bug Fix

#4892 Fixes Chemical Plant Tooltip
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/MTEChemicalPlant.java
Labels: Bug Fix

#4894 fix: PCBFactory tooltip should state that you can use any tiered glass
  src/main/java/gregtech/common/tileentities/machines/multi/MTEPCBFactory.java
Labels: Enhancement

#4893 Change maglevHarness pylons message color to blue
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: Enhancement, Safe for Stable

#4897 removed circular maceration of red and black granite
  src/main/java/gregtech/api/enums/Materials.java
  src/main/java/gregtech/loaders/postload/recipes/CompressorRecipes.java
  src/main/java/gregtech/loaders/postload/recipes/FluidExtractorRecipes.java
Labels: Bug Fix

#4905 Fix "Research Station wrong tooltips"
  src/main/resources/assets/tectech/lang/en_US.lang
Labels: Bug Fix

#4902 fix digital tank base UI spamming chat
  src/main/java/gregtech/common/tileentities/storage/MTEDigitalTankBase.java
Labels: Bug Fix

#4920 Powerfail fix
  dependencies.gradle
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/client/GTPowerfailRenderer.java
  src/main/java/gregtech/common/GTProxy.java
Labels: Bug Fix

#4921 #21408 Machine update propagation fix
  src/main/java/gregtech/api/threads/RunnableMachineUpdate.java
Labels: Bug Fix

#4929 Fix crash building higher tier LSC with Hologram Projector
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
Labels: Bug Fix

#4931 Fix power goggles crash where client map persists between worlds
  src/main/java/gregtech/common/GTProxy.java
  src/main/java/gregtech/common/powergoggles/PowerGogglesUtil.java
  src/main/java/gregtech/common/powergoggles/handlers/PowerGogglesEventHandler.java
Labels: Bug Fix, Safe for Stable

#4930 Fix broken LSC structure preview
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
Labels: Bug Fix

#4932 Fix LSC capacitor channel not showing in preview
  src/main/java/kekztech/common/tileentities/MTELapotronicSuperCapacitor.java
Labels: Bug Fix

#4936 fix copper plasma not showing up in NEI
  src/main/java/gregtech/loaders/materials/MaterialsInit1.java
Labels: Bug Fix, Safe for Stable

#4938 Fix Energy Infuser, Improve Tooltip
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEnergyInfuser.java
Labels: Chore

#4940 Powerfail events into lang
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/resources/assets/gregtech/lang/en_US.lang
Labels: Enhancement

#4941 Do the null check first
  src/main/java/gregtech/api/metatileentity/implementations/MTECable.java
Labels: Bug Fix

#4782 Added Breeding Trees for Botania Bees
  src/main/java/gregtech/api/enums/ItemList.java
  src/main/java/gregtech/common/items/CombType.java
  src/main/java/gregtech/common/items/IDMetaItem03.java
  src/main/java/gregtech/common/items/ItemComb.java
  src/main/java/gregtech/common/items/MetaGeneratedItem03.java
  src/main/java/gregtech/loaders/misc/GTBeeDefinition.java
  src/main/java/gregtech/loaders/misc/GTBees.java
  src/main/java/gregtech/loaders/misc/GTBranchDefinition.java
  src/main/resources/assets/gregtech/lang/en_US.lang
  src/main/resources/assets/gregtech/textures/items/gt.metaitem.03/252.png
Labels: Affects Balance, New Feature

#4671 Void protection refactor + improvements
  src/functionalTest/java/gregtech/test/mock/MockIVoidableMachine.java
  src/main/java/bartworks/common/tileentities/multis/MTEThoriumHighTempReactor.java
  src/main/java/bartworks/common/tileentities/multis/MTEWindmill.java
  src/main/java/bwcrossmod/galacticgreg/MTEVoidMinerBase.java
  src/main/java/ggfab/mte/MTEAdvAssLine.java
  src/main/java/goodgenerator/blocks/tileEntity/base/MTELargeFusionComputer.java
  src/main/java/gregtech/api/enums/GTValues.java
  src/main/java/gregtech/api/enums/OutputBusType.java
  src/main/java/gregtech/api/interfaces/IOutputBus.java
  src/main/java/gregtech/api/interfaces/IOutputBusTransaction.java
  src/main/java/gregtech/api/interfaces/tileentity/IVoidable.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchOutputBus.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEHatchVoidBus.java
  src/main/java/gregtech/api/metatileentity/implementations/MTEMultiBlockBase.java
  src/main/java/gregtech/api/objects/GTItemStack.java
  src/main/java/gregtech/api/util/GTDataUtils.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/ItemEjectionHelper.java
  src/main/java/gregtech/api/util/ParallelHelper.java
  src/main/java/gregtech/api/util/VoidProtectionHelper.java
  src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputBusME.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEDecayWarehouse.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEFusionComputer.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTELargeMolecularAssembler.java
  src/main/java/gregtech/common/tileentities/machines/multi/MTEMultiFurnace.java
  src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBaryonicPerfection.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/MTEHatchSteamBusOutput.java
  src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/MTESteamMultiBase.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTETreeFarm.java
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/MTEChemicalPlant.java
  src/main/java/kubatech/api/implementations/KubaTechGTMultiBlockBase.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeEntityCrusher.java
  src/main/java/kubatech/tileentity/gregtech/multiblock/MTEExtremeIndustrialGreenhouse.java
  src/main/java/tectech/thing/metaTileEntity/multi/MTEEnergyInfuser.java
  src/main/java/tectech/thing/metaTileEntity/multi/base/TTMultiblockBase.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEExoticModule.java
  src/main/java/tectech/thing/metaTileEntity/multi/godforge/MTEForgeOfGods.java
Labels: Refactor, Bug Fix

#4944 disable the hot netherite ingot
  src/main/java/gregtech/api/enums/Materials.java
Labels: Bug Fix

#4949 change MABS glass requirements
  src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/mega/MTEMegaAlloyBlastSmelter.java
Labels: Affects Balance

#4950 disable hot netherite ingot for 2.8.x
  src/main/java/gregtech/api/enums/Materials.java
Labels: Bug Fix

#4951 fix maths in polymerization
  src/main/java/gregtech/loaders/postload/recipes/ChemicalRecipes.java
Labels: Bug Fix

#4922 Fix StackOverflowExceptions when chunks with many machines are loaded
  src/main/java/gregtech/common/blocks/BlockMachines.java
Labels: Bug Fix

#4952 fix maths in polymerization
  src/main/java/gregtech/loaders/postload/recipes/ChemicalRecipes.java
Labels: Bug Fix

#4942 recognize all subclasses of BlockLog as wood log
  src/main/java/gregtech/common/tileentities/machines/multi/MTECharcoalPit.java
Labels: Bug Fix, Safe for Stable
